// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
)

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for QuestDifficulty.
const (
	Deadly  QuestDifficulty = "deadly"
	Easy    QuestDifficulty = "easy"
	Hard    QuestDifficulty = "hard"
	Medium  QuestDifficulty = "medium"
	Trivial QuestDifficulty = "trivial"
)

// Valid indicates whether the value is a known member of the QuestDifficulty enum.
func (e QuestDifficulty) Valid() bool {
	switch e {
	case Deadly:
		return true
	case Easy:
		return true
	case Hard:
		return true
	case Medium:
		return true
	case Trivial:
		return true
	default:
		return false
	}
}

// Defines values for QuestStatus.
const (
	Active    QuestStatus = "active"
	Available QuestStatus = "available"
	Completed QuestStatus = "completed"
	Failed    QuestStatus = "failed"
)

// Valid indicates whether the value is a known member of the QuestStatus enum.
func (e QuestStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Available:
		return true
	case Completed:
		return true
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for RewardType.
const (
	Gold       RewardType = "gold"
	Item       RewardType = "item"
	Other      RewardType = "other"
	Reputation RewardType = "reputation"
	Xp         RewardType = "xp"
)

// Valid indicates whether the value is a known member of the RewardType enum.
func (e RewardType) Valid() bool {
	switch e {
	case Gold:
		return true
	case Item:
		return true
	case Other:
		return true
	case Reputation:
		return true
	case Xp:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Dm     Role = "dm"
	Player Role = "player"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Dm:
		return true
	case Player:
		return true
	default:
		return false
	}
}

// Campaign defines model for Campaign.
type Campaign struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// InviteCode Shareable code players use to join the campaign.
	InviteCode  string             `json:"inviteCode"`
	Name        string             `json:"name"`
	OwnerUserId openapi_types.UUID `json:"ownerUserId"`
}

// CampaignMembership defines model for CampaignMembership.
type CampaignMembership struct {
	Campaign Campaign `json:"campaign"`
	Role     Role     `json:"role"`
}

// Character defines model for Character.
type Character struct {
	CampaignId openapi_types.UUID `json:"campaignId"`

	// Class Freeform class/ancestry line, e.g. "Half-Elf Bard".
	Class     string             `json:"class"`
	CreatedAt time.Time          `json:"createdAt"`
	HpCurrent int                `json:"hpCurrent"`
	HpMax     int                `json:"hpMax"`
	Id        openapi_types.UUID `json:"id"`
	Level     int                `json:"level"`

	// Mine True when the caller owns this character.
	Mine bool   `json:"mine"`
	Name string `json:"name"`

	// OwnerName Display name of the member who plays this character.
	OwnerName   string             `json:"ownerName"`
	OwnerUserId openapi_types.UUID `json:"ownerUserId"`
}

// CharacterInput defines model for CharacterInput.
type CharacterInput struct {
	Class     *string `json:"class,omitempty"`
	HpCurrent int     `json:"hpCurrent"`
	HpMax     int     `json:"hpMax"`
	Level     int     `json:"level"`
	Name      string  `json:"name"`
}

// CreateCampaignRequest defines model for CreateCampaignRequest.
type CreateCampaignRequest struct {
	Name string `json:"name"`
}

// CreateQuestRequest defines model for CreateQuestRequest.
type CreateQuestRequest struct {
	Description *string          `json:"description,omitempty"`
	Difficulty  *QuestDifficulty `json:"difficulty,omitempty"`
	Giver       *string          `json:"giver,omitempty"`
	Location    *string          `json:"location,omitempty"`
	Rewards     *[]RewardInput   `json:"rewards,omitempty"`
	Title       string           `json:"title"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	Campaigns []CampaignMembership `json:"campaigns"`
	User      User                 `json:"user"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// JoinCampaignRequest defines model for JoinCampaignRequest.
type JoinCampaignRequest struct {
	Code string `json:"code"`
}

// Quest defines model for Quest.
type Quest struct {
	CampaignId  openapi_types.UUID `json:"campaignId"`
	ClaimedByMe bool               `json:"claimedByMe"`
	Claims      []QuestClaim       `json:"claims"`
	CreatedAt   time.Time          `json:"createdAt"`
	Description string             `json:"description"`
	Difficulty  QuestDifficulty    `json:"difficulty"`
	Giver       *string            `json:"giver,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Location    *string            `json:"location,omitempty"`
	Rewards     []QuestReward      `json:"rewards"`
	Status      QuestStatus        `json:"status"`
	Title       string             `json:"title"`
}

// QuestClaim defines model for QuestClaim.
type QuestClaim struct {
	ClaimedAt time.Time          `json:"claimedAt"`
	UserId    openapi_types.UUID `json:"userId"`
	UserName  string             `json:"userName"`
}

// QuestDifficulty defines model for QuestDifficulty.
type QuestDifficulty string

// QuestReward defines model for QuestReward.
type QuestReward struct {
	Id    openapi_types.UUID `json:"id"`
	Label string             `json:"label"`
	Type  RewardType         `json:"type"`
	Value *string            `json:"value,omitempty"`
}

// QuestStatus defines model for QuestStatus.
type QuestStatus string

// RewardInput defines model for RewardInput.
type RewardInput struct {
	Label string     `json:"label"`
	Type  RewardType `json:"type"`
	Value *string    `json:"value,omitempty"`
}

// RewardType defines model for RewardType.
type RewardType string

// Role defines model for Role.
type Role string

// UpdateQuestRequest defines model for UpdateQuestRequest.
type UpdateQuestRequest struct {
	Description *string         `json:"description,omitempty"`
	Difficulty  QuestDifficulty `json:"difficulty"`
	Giver       *string         `json:"giver,omitempty"`
	Location    *string         `json:"location,omitempty"`
	Rewards     *[]RewardInput  `json:"rewards,omitempty"`
	Status      QuestStatus     `json:"status"`
	Title       string          `json:"title"`
}

// User defines model for User.
type User struct {
	Email *string            `json:"email,omitempty"`
	Id    openapi_types.UUID `json:"id"`
	Image *string            `json:"image,omitempty"`
	Name  string             `json:"name"`
}

// CampaignId defines model for CampaignId.
type CampaignId = openapi_types.UUID

// CharacterId defines model for CharacterId.
type CharacterId = openapi_types.UUID

// QuestId defines model for QuestId.
type QuestId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// CreateCampaignJSONRequestBody defines body for CreateCampaign for application/json ContentType.
type CreateCampaignJSONRequestBody = CreateCampaignRequest

// JoinCampaignJSONRequestBody defines body for JoinCampaign for application/json ContentType.
type JoinCampaignJSONRequestBody = JoinCampaignRequest

// CreateCharacterJSONRequestBody defines body for CreateCharacter for application/json ContentType.
type CreateCharacterJSONRequestBody = CharacterInput

// CreateQuestJSONRequestBody defines body for CreateQuest for application/json ContentType.
type CreateQuestJSONRequestBody = CreateQuestRequest

// UpdateCharacterJSONRequestBody defines body for UpdateCharacter for application/json ContentType.
type UpdateCharacterJSONRequestBody = CharacterInput

// UpdateQuestJSONRequestBody defines body for UpdateQuest for application/json ContentType.
type UpdateQuestJSONRequestBody = UpdateQuestRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Campaigns the current user belongs to
	// (GET /campaigns)
	ListCampaigns(w http.ResponseWriter, r *http.Request)
	// Create a campaign (caller becomes its DM)
	// (POST /campaigns)
	CreateCampaign(w http.ResponseWriter, r *http.Request)
	// Join a campaign as a player using its invite code
	// (POST /campaigns/join)
	JoinCampaign(w http.ResponseWriter, r *http.Request)
	// The campaign's party roster (members only)
	// (GET /campaigns/{campaignId}/characters)
	ListCharacters(w http.ResponseWriter, r *http.Request, campaignId CampaignId)
	// Add a character owned by the caller (any campaign member)
	// (POST /campaigns/{campaignId}/characters)
	CreateCharacter(w http.ResponseWriter, r *http.Request, campaignId CampaignId)
	// List quests on a campaign's board (members only)
	// (GET /campaigns/{campaignId}/quests)
	ListQuests(w http.ResponseWriter, r *http.Request, campaignId CampaignId)
	// Post a new quest (DM only)
	// (POST /campaigns/{campaignId}/quests)
	CreateQuest(w http.ResponseWriter, r *http.Request, campaignId CampaignId)
	// Generate a fresh invite code (DM only)
	// (POST /campaigns/{campaignId}/regenerate-invite)
	RegenerateInvite(w http.ResponseWriter, r *http.Request, campaignId CampaignId)
	// Remove a character (its owner or the DM)
	// (DELETE /characters/{characterId})
	DeleteCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId)
	// Update a character (its owner or the DM)
	// (PATCH /characters/{characterId})
	UpdateCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId)
	// Liveness / readiness probe
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// The currently authenticated user and their campaign memberships
	// (GET /me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Remove a quest (DM only)
	// (DELETE /quests/{questId})
	DeleteQuest(w http.ResponseWriter, r *http.Request, questId QuestId)
	// Update a quest, including its status and rewards (DM only)
	// (PATCH /quests/{questId})
	UpdateQuest(w http.ResponseWriter, r *http.Request, questId QuestId)
	// Release a previously claimed quest
	// (DELETE /quests/{questId}/claim)
	UnclaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId)
	// Claim a quest (any campaign member)
	// (POST /quests/{questId}/claim)
	ClaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Campaigns the current user belongs to
// (GET /campaigns)
func (_ Unimplemented) ListCampaigns(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a campaign (caller becomes its DM)
// (POST /campaigns)
func (_ Unimplemented) CreateCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Join a campaign as a player using its invite code
// (POST /campaigns/join)
func (_ Unimplemented) JoinCampaign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The campaign's party roster (members only)
// (GET /campaigns/{campaignId}/characters)
func (_ Unimplemented) ListCharacters(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a character owned by the caller (any campaign member)
// (POST /campaigns/{campaignId}/characters)
func (_ Unimplemented) CreateCharacter(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List quests on a campaign's board (members only)
// (GET /campaigns/{campaignId}/quests)
func (_ Unimplemented) ListQuests(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Post a new quest (DM only)
// (POST /campaigns/{campaignId}/quests)
func (_ Unimplemented) CreateQuest(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Generate a fresh invite code (DM only)
// (POST /campaigns/{campaignId}/regenerate-invite)
func (_ Unimplemented) RegenerateInvite(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a character (its owner or the DM)
// (DELETE /characters/{characterId})
func (_ Unimplemented) DeleteCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a character (its owner or the DM)
// (PATCH /characters/{characterId})
func (_ Unimplemented) UpdateCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness / readiness probe
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// The currently authenticated user and their campaign memberships
// (GET /me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a quest (DM only)
// (DELETE /quests/{questId})
func (_ Unimplemented) DeleteQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a quest, including its status and rewards (DM only)
// (PATCH /quests/{questId})
func (_ Unimplemented) UpdateQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Release a previously claimed quest
// (DELETE /quests/{questId}/claim)
func (_ Unimplemented) UnclaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Claim a quest (any campaign member)
// (POST /quests/{questId}/claim)
func (_ Unimplemented) ClaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCampaigns operation middleware
func (siw *ServerInterfaceWrapper) ListCampaigns(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCampaigns(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCampaign operation middleware
func (siw *ServerInterfaceWrapper) CreateCampaign(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinCampaign operation middleware
func (siw *ServerInterfaceWrapper) JoinCampaign(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinCampaign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCharacters operation middleware
func (siw *ServerInterfaceWrapper) ListCharacters(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "campaignId" -------------
	var campaignId CampaignId

	err = runtime.BindStyledParameterWithOptions("simple", "campaignId", chi.URLParam(r, "campaignId"), &campaignId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCharacters(w, r, campaignId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCharacter operation middleware
func (siw *ServerInterfaceWrapper) CreateCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "campaignId" -------------
	var campaignId CampaignId

	err = runtime.BindStyledParameterWithOptions("simple", "campaignId", chi.URLParam(r, "campaignId"), &campaignId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCharacter(w, r, campaignId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListQuests operation middleware
func (siw *ServerInterfaceWrapper) ListQuests(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "campaignId" -------------
	var campaignId CampaignId

	err = runtime.BindStyledParameterWithOptions("simple", "campaignId", chi.URLParam(r, "campaignId"), &campaignId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListQuests(w, r, campaignId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateQuest operation middleware
func (siw *ServerInterfaceWrapper) CreateQuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "campaignId" -------------
	var campaignId CampaignId

	err = runtime.BindStyledParameterWithOptions("simple", "campaignId", chi.URLParam(r, "campaignId"), &campaignId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateQuest(w, r, campaignId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegenerateInvite operation middleware
func (siw *ServerInterfaceWrapper) RegenerateInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "campaignId" -------------
	var campaignId CampaignId

	err = runtime.BindStyledParameterWithOptions("simple", "campaignId", chi.URLParam(r, "campaignId"), &campaignId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegenerateInvite(w, r, campaignId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCharacter operation middleware
func (siw *ServerInterfaceWrapper) DeleteCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "characterId" -------------
	var characterId CharacterId

	err = runtime.BindStyledParameterWithOptions("simple", "characterId", chi.URLParam(r, "characterId"), &characterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "characterId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCharacter(w, r, characterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCharacter operation middleware
func (siw *ServerInterfaceWrapper) UpdateCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "characterId" -------------
	var characterId CharacterId

	err = runtime.BindStyledParameterWithOptions("simple", "characterId", chi.URLParam(r, "characterId"), &characterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "characterId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCharacter(w, r, characterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteQuest operation middleware
func (siw *ServerInterfaceWrapper) DeleteQuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questId" -------------
	var questId QuestId

	err = runtime.BindStyledParameterWithOptions("simple", "questId", chi.URLParam(r, "questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteQuest(w, r, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateQuest operation middleware
func (siw *ServerInterfaceWrapper) UpdateQuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questId" -------------
	var questId QuestId

	err = runtime.BindStyledParameterWithOptions("simple", "questId", chi.URLParam(r, "questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateQuest(w, r, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnclaimQuest operation middleware
func (siw *ServerInterfaceWrapper) UnclaimQuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questId" -------------
	var questId QuestId

	err = runtime.BindStyledParameterWithOptions("simple", "questId", chi.URLParam(r, "questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnclaimQuest(w, r, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimQuest operation middleware
func (siw *ServerInterfaceWrapper) ClaimQuest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "questId" -------------
	var questId QuestId

	err = runtime.BindStyledParameterWithOptions("simple", "questId", chi.URLParam(r, "questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimQuest(w, r, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/campaigns", wrapper.ListCampaigns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/campaigns", wrapper.CreateCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/campaigns/join", wrapper.JoinCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/campaigns/{campaignId}/characters", wrapper.ListCharacters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/campaigns/{campaignId}/characters", wrapper.CreateCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/campaigns/{campaignId}/quests", wrapper.ListQuests)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/campaigns/{campaignId}/quests", wrapper.CreateQuest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/campaigns/{campaignId}/regenerate-invite", wrapper.RegenerateInvite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/characters/{characterId}", wrapper.DeleteCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/characters/{characterId}", wrapper.UpdateCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/quests/{questId}", wrapper.DeleteQuest)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/quests/{questId}", wrapper.UpdateQuest)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/quests/{questId}/claim", wrapper.UnclaimQuest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/quests/{questId}/claim", wrapper.ClaimQuest)
	})

	return r
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListCampaignsRequestObject struct {
}

type ListCampaignsResponseObject interface {
	VisitListCampaignsResponse(w http.ResponseWriter) error
}

type ListCampaigns200JSONResponse []CampaignMembership

func (response ListCampaigns200JSONResponse) VisitListCampaignsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCampaigns401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListCampaigns401JSONResponse) VisitListCampaignsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCampaignRequestObject struct {
	Body *CreateCampaignJSONRequestBody
}

type CreateCampaignResponseObject interface {
	VisitCreateCampaignResponse(w http.ResponseWriter) error
}

type CreateCampaign201JSONResponse Campaign

func (response CreateCampaign201JSONResponse) VisitCreateCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCampaign400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateCampaign400JSONResponse) VisitCreateCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCampaign401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateCampaign401JSONResponse) VisitCreateCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type JoinCampaignRequestObject struct {
	Body *JoinCampaignJSONRequestBody
}

type JoinCampaignResponseObject interface {
	VisitJoinCampaignResponse(w http.ResponseWriter) error
}

type JoinCampaign200JSONResponse CampaignMembership

func (response JoinCampaign200JSONResponse) VisitJoinCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type JoinCampaign400JSONResponse struct{ BadRequestJSONResponse }

func (response JoinCampaign400JSONResponse) VisitJoinCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type JoinCampaign401JSONResponse struct{ UnauthorizedJSONResponse }

func (response JoinCampaign401JSONResponse) VisitJoinCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type JoinCampaign404JSONResponse struct{ NotFoundJSONResponse }

func (response JoinCampaign404JSONResponse) VisitJoinCampaignResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListCharactersRequestObject struct {
	CampaignId CampaignId `json:"campaignId"`
}

type ListCharactersResponseObject interface {
	VisitListCharactersResponse(w http.ResponseWriter) error
}

type ListCharacters200JSONResponse []Character

func (response ListCharacters200JSONResponse) VisitListCharactersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCharacters401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListCharacters401JSONResponse) VisitListCharactersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListCharacters403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListCharacters403JSONResponse) VisitListCharactersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacterRequestObject struct {
	CampaignId CampaignId `json:"campaignId"`
	Body       *CreateCharacterJSONRequestBody
}

type CreateCharacterResponseObject interface {
	VisitCreateCharacterResponse(w http.ResponseWriter) error
}

type CreateCharacter201JSONResponse Character

func (response CreateCharacter201JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateCharacter400JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateCharacter401JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateCharacter403JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListQuestsRequestObject struct {
	CampaignId CampaignId `json:"campaignId"`
}

type ListQuestsResponseObject interface {
	VisitListQuestsResponse(w http.ResponseWriter) error
}

type ListQuests200JSONResponse []Quest

func (response ListQuests200JSONResponse) VisitListQuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListQuests401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListQuests401JSONResponse) VisitListQuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListQuests403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListQuests403JSONResponse) VisitListQuestsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuestRequestObject struct {
	CampaignId CampaignId `json:"campaignId"`
	Body       *CreateQuestJSONRequestBody
}

type CreateQuestResponseObject interface {
	VisitCreateQuestResponse(w http.ResponseWriter) error
}

type CreateQuest201JSONResponse Quest

func (response CreateQuest201JSONResponse) VisitCreateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuest400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateQuest400JSONResponse) VisitCreateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateQuest401JSONResponse) VisitCreateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateQuest403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateQuest403JSONResponse) VisitCreateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RegenerateInviteRequestObject struct {
	CampaignId CampaignId `json:"campaignId"`
}

type RegenerateInviteResponseObject interface {
	VisitRegenerateInviteResponse(w http.ResponseWriter) error
}

type RegenerateInvite200JSONResponse Campaign

func (response RegenerateInvite200JSONResponse) VisitRegenerateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegenerateInvite401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RegenerateInvite401JSONResponse) VisitRegenerateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegenerateInvite403JSONResponse struct{ ForbiddenJSONResponse }

func (response RegenerateInvite403JSONResponse) VisitRegenerateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RegenerateInvite404JSONResponse struct{ NotFoundJSONResponse }

func (response RegenerateInvite404JSONResponse) VisitRegenerateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacterRequestObject struct {
	CharacterId CharacterId `json:"characterId"`
}

type DeleteCharacterResponseObject interface {
	VisitDeleteCharacterResponse(w http.ResponseWriter) error
}

type DeleteCharacter204Response struct {
}

func (response DeleteCharacter204Response) VisitDeleteCharacterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCharacter401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteCharacter401JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacter403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteCharacter403JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacter404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCharacter404JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacterRequestObject struct {
	CharacterId CharacterId `json:"characterId"`
	Body        *UpdateCharacterJSONRequestBody
}

type UpdateCharacterResponseObject interface {
	VisitUpdateCharacterResponse(w http.ResponseWriter) error
}

type UpdateCharacter200JSONResponse Character

func (response UpdateCharacter200JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateCharacter400JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateCharacter401JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateCharacter403JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateCharacter404JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse CurrentUser

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuestRequestObject struct {
	QuestId QuestId `json:"questId"`
}

type DeleteQuestResponseObject interface {
	VisitDeleteQuestResponse(w http.ResponseWriter) error
}

type DeleteQuest204Response struct {
}

func (response DeleteQuest204Response) VisitDeleteQuestResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteQuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteQuest401JSONResponse) VisitDeleteQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuest403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteQuest403JSONResponse) VisitDeleteQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteQuest404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteQuest404JSONResponse) VisitDeleteQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateQuestRequestObject struct {
	QuestId QuestId `json:"questId"`
	Body    *UpdateQuestJSONRequestBody
}

type UpdateQuestResponseObject interface {
	VisitUpdateQuestResponse(w http.ResponseWriter) error
}

type UpdateQuest200JSONResponse Quest

func (response UpdateQuest200JSONResponse) VisitUpdateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateQuest400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateQuest400JSONResponse) VisitUpdateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateQuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateQuest401JSONResponse) VisitUpdateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateQuest403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateQuest403JSONResponse) VisitUpdateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateQuest404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateQuest404JSONResponse) VisitUpdateQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UnclaimQuestRequestObject struct {
	QuestId QuestId `json:"questId"`
}

type UnclaimQuestResponseObject interface {
	VisitUnclaimQuestResponse(w http.ResponseWriter) error
}

type UnclaimQuest200JSONResponse Quest

func (response UnclaimQuest200JSONResponse) VisitUnclaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UnclaimQuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnclaimQuest401JSONResponse) VisitUnclaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UnclaimQuest403JSONResponse struct{ ForbiddenJSONResponse }

func (response UnclaimQuest403JSONResponse) VisitUnclaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UnclaimQuest404JSONResponse struct{ NotFoundJSONResponse }

func (response UnclaimQuest404JSONResponse) VisitUnclaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimQuestRequestObject struct {
	QuestId QuestId `json:"questId"`
}

type ClaimQuestResponseObject interface {
	VisitClaimQuestResponse(w http.ResponseWriter) error
}

type ClaimQuest200JSONResponse Quest

func (response ClaimQuest200JSONResponse) VisitClaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimQuest401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimQuest401JSONResponse) VisitClaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimQuest403JSONResponse struct{ ForbiddenJSONResponse }

func (response ClaimQuest403JSONResponse) VisitClaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ClaimQuest404JSONResponse struct{ NotFoundJSONResponse }

func (response ClaimQuest404JSONResponse) VisitClaimQuestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Campaigns the current user belongs to
	// (GET /campaigns)
	ListCampaigns(ctx context.Context, request ListCampaignsRequestObject) (ListCampaignsResponseObject, error)
	// Create a campaign (caller becomes its DM)
	// (POST /campaigns)
	CreateCampaign(ctx context.Context, request CreateCampaignRequestObject) (CreateCampaignResponseObject, error)
	// Join a campaign as a player using its invite code
	// (POST /campaigns/join)
	JoinCampaign(ctx context.Context, request JoinCampaignRequestObject) (JoinCampaignResponseObject, error)
	// The campaign's party roster (members only)
	// (GET /campaigns/{campaignId}/characters)
	ListCharacters(ctx context.Context, request ListCharactersRequestObject) (ListCharactersResponseObject, error)
	// Add a character owned by the caller (any campaign member)
	// (POST /campaigns/{campaignId}/characters)
	CreateCharacter(ctx context.Context, request CreateCharacterRequestObject) (CreateCharacterResponseObject, error)
	// List quests on a campaign's board (members only)
	// (GET /campaigns/{campaignId}/quests)
	ListQuests(ctx context.Context, request ListQuestsRequestObject) (ListQuestsResponseObject, error)
	// Post a new quest (DM only)
	// (POST /campaigns/{campaignId}/quests)
	CreateQuest(ctx context.Context, request CreateQuestRequestObject) (CreateQuestResponseObject, error)
	// Generate a fresh invite code (DM only)
	// (POST /campaigns/{campaignId}/regenerate-invite)
	RegenerateInvite(ctx context.Context, request RegenerateInviteRequestObject) (RegenerateInviteResponseObject, error)
	// Remove a character (its owner or the DM)
	// (DELETE /characters/{characterId})
	DeleteCharacter(ctx context.Context, request DeleteCharacterRequestObject) (DeleteCharacterResponseObject, error)
	// Update a character (its owner or the DM)
	// (PATCH /characters/{characterId})
	UpdateCharacter(ctx context.Context, request UpdateCharacterRequestObject) (UpdateCharacterResponseObject, error)
	// Liveness / readiness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// The currently authenticated user and their campaign memberships
	// (GET /me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Remove a quest (DM only)
	// (DELETE /quests/{questId})
	DeleteQuest(ctx context.Context, request DeleteQuestRequestObject) (DeleteQuestResponseObject, error)
	// Update a quest, including its status and rewards (DM only)
	// (PATCH /quests/{questId})
	UpdateQuest(ctx context.Context, request UpdateQuestRequestObject) (UpdateQuestResponseObject, error)
	// Release a previously claimed quest
	// (DELETE /quests/{questId}/claim)
	UnclaimQuest(ctx context.Context, request UnclaimQuestRequestObject) (UnclaimQuestResponseObject, error)
	// Claim a quest (any campaign member)
	// (POST /quests/{questId}/claim)
	ClaimQuest(ctx context.Context, request ClaimQuestRequestObject) (ClaimQuestResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCampaigns operation middleware
func (sh *strictHandler) ListCampaigns(w http.ResponseWriter, r *http.Request) {
	var request ListCampaignsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCampaigns(ctx, request.(ListCampaignsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCampaigns")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCampaignsResponseObject); ok {
		if err := validResponse.VisitListCampaignsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCampaign operation middleware
func (sh *strictHandler) CreateCampaign(w http.ResponseWriter, r *http.Request) {
	var request CreateCampaignRequestObject

	var body CreateCampaignJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCampaign(ctx, request.(CreateCampaignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCampaign")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCampaignResponseObject); ok {
		if err := validResponse.VisitCreateCampaignResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinCampaign operation middleware
func (sh *strictHandler) JoinCampaign(w http.ResponseWriter, r *http.Request) {
	var request JoinCampaignRequestObject

	var body JoinCampaignJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinCampaign(ctx, request.(JoinCampaignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinCampaign")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinCampaignResponseObject); ok {
		if err := validResponse.VisitJoinCampaignResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCharacters operation middleware
func (sh *strictHandler) ListCharacters(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	var request ListCharactersRequestObject

	request.CampaignId = campaignId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCharacters(ctx, request.(ListCharactersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCharacters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCharactersResponseObject); ok {
		if err := validResponse.VisitListCharactersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCharacter operation middleware
func (sh *strictHandler) CreateCharacter(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	var request CreateCharacterRequestObject

	request.CampaignId = campaignId

	var body CreateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCharacter(ctx, request.(CreateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCharacterResponseObject); ok {
		if err := validResponse.VisitCreateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListQuests operation middleware
func (sh *strictHandler) ListQuests(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	var request ListQuestsRequestObject

	request.CampaignId = campaignId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListQuests(ctx, request.(ListQuestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListQuests")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListQuestsResponseObject); ok {
		if err := validResponse.VisitListQuestsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateQuest operation middleware
func (sh *strictHandler) CreateQuest(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	var request CreateQuestRequestObject

	request.CampaignId = campaignId

	var body CreateQuestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateQuest(ctx, request.(CreateQuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateQuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateQuestResponseObject); ok {
		if err := validResponse.VisitCreateQuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegenerateInvite operation middleware
func (sh *strictHandler) RegenerateInvite(w http.ResponseWriter, r *http.Request, campaignId CampaignId) {
	var request RegenerateInviteRequestObject

	request.CampaignId = campaignId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegenerateInvite(ctx, request.(RegenerateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegenerateInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegenerateInviteResponseObject); ok {
		if err := validResponse.VisitRegenerateInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCharacter operation middleware
func (sh *strictHandler) DeleteCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId) {
	var request DeleteCharacterRequestObject

	request.CharacterId = characterId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCharacter(ctx, request.(DeleteCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCharacterResponseObject); ok {
		if err := validResponse.VisitDeleteCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCharacter operation middleware
func (sh *strictHandler) UpdateCharacter(w http.ResponseWriter, r *http.Request, characterId CharacterId) {
	var request UpdateCharacterRequestObject

	request.CharacterId = characterId

	var body UpdateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCharacter(ctx, request.(UpdateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCharacterResponseObject); ok {
		if err := validResponse.VisitUpdateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteQuest operation middleware
func (sh *strictHandler) DeleteQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	var request DeleteQuestRequestObject

	request.QuestId = questId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteQuest(ctx, request.(DeleteQuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteQuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteQuestResponseObject); ok {
		if err := validResponse.VisitDeleteQuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateQuest operation middleware
func (sh *strictHandler) UpdateQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	var request UpdateQuestRequestObject

	request.QuestId = questId

	var body UpdateQuestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateQuest(ctx, request.(UpdateQuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateQuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateQuestResponseObject); ok {
		if err := validResponse.VisitUpdateQuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UnclaimQuest operation middleware
func (sh *strictHandler) UnclaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	var request UnclaimQuestRequestObject

	request.QuestId = questId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UnclaimQuest(ctx, request.(UnclaimQuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnclaimQuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UnclaimQuestResponseObject); ok {
		if err := validResponse.VisitUnclaimQuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClaimQuest operation middleware
func (sh *strictHandler) ClaimQuest(w http.ResponseWriter, r *http.Request, questId QuestId) {
	var request ClaimQuestRequestObject

	request.QuestId = questId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimQuest(ctx, request.(ClaimQuestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimQuest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ClaimQuestResponseObject); ok {
		if err := validResponse.VisitClaimQuestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptbxu5Ef4rA7ZAHGBjyUlaFPoW25ec23Nwfskn28BRuyMtEy65R3LlqIb+e0FyXyWuJMeyGhf9ZnmH",
	"nOHMM8OHQz6QWGa5FCiMJqMHklNFMzSo3K8TmuWUTcVZYn8xQUYkpyYlERE0QzIicSMQEYV/FkxhQkZG",
	"FRgRHaeYUTtyIlVGDRmRomBW0sxzO1obxcSULBYROUmporFB1a+qJfE0XRcFatOr58/y61N0LOxgnUuh",
	"0fnxmCaX6Ca2v2IpDAr3J81zzmJqmBSDr1oK+79GzV8VTsiI/GXQxGjgv+rBL0pJ5VUlqGPFcjsJGZEz",
	"MaOcJaBKhYuIfJRqzJIExfNr/ywNUM7lPSZwIOwPyDAbo4pAKmBCF5MJixkKA0pyfG3N+yzNR1mI5Pmt",
	"u0QtCxUjWMsmTuciIl8ELUwqFfs3JnvyUGFSFMbOjInDZDmsnXQuHZXMURnmYRQrtAM+mA4GE2rwjWEZ",
	"rgIxIizZAq8RYWLGDJ7IBK141+CrlCqkY44QywQh53SOSkOhEYyEr5IJMClCVQoOQ/P73HpY/SDvBaov",
	"usr7zcnbJOUNcSJu6u5EUctTnbXd1TPK8VeMXXJU7j53MNUpywOOb4VkXdDr0FlDJcdN8pdWZnlVtbJy",
	"jqDRVTHst/Vsu8jHnGq9GvSPCtGOBfd9QEWM2qg5cCYwAjycHsIt+ZXyyZtf+ASOqUpuSTDyP4DZND8p",
	"lCozsPzKhMEpKv/5nH4Pf9oS7RxnyMMzZEwEUuBaFQj3KVZI5xwVyHuhwaRMQ701tTwwlpIjFZvB/7n8",
	"2tV4yrRNNLBjQU6cXl9I4T6VLgnXKN9lfnW2+G6WNfbXaejhVLm4HcsqcN3kdP5ei/AzkRcmAPMKtxn9",
	"/huKqUnJ6B/DTWjKmGBZkZFRIxlCVi12FBKr4ZPR717s7TDaMKbCwJK1GRPVz6NN0Sg93O/ZoBudr6u6",
	"1CIhXW8GzDt6+yP29dvgWFevAR30B1IlYZY3FNzMN9VUp+e0EV9EZMpmvlKKgnO7k1WMbrUySL/ZbyWs",
	"8J6qxJnPDGZ6Y7V38h7Pi3o+qhR1Vhpm+HIQ3g4fGQQ/STAKHi02efs3je0XE9g2A2sqSm3rZnIWLa/D",
	"DYxadoWW5DnWymKw+vd6V3mx0Ly/IuXW28sTa0NN4VUIm+k3RH4jlt9NFU0wac3Vo7KcIKTzn5KJjWka",
	"lwTtMYiI+4jPRY+OR/MHlmFyPD9v73Gt3c8JbI8rZ9WJHRPC0w+wiZ+ksmxLTZ6zAJUl2A4KObeB98ZJ",
	"rrxou2o9lkr4gd34dKJRG9RlDNWia2R1MdiLdI+pEI+wYx+DqGJbOuVFP4fpX6DgOb/UQ6KWbb2rOu2g",
	"typLRrEZo5YlINXWkxkmrMgsU7Cxt06nCZ8HClY5bQmSFW9ti2I67hDs5ov/xzb75LWVXERkRnmBW6RD",
	"CHBOpDKn14dXK2WdzijzuiJCY8NmLhoyyznaA3tEJpTxYMGPSHuXX/Ff7Zi1FXyPbtrooZaWloOmkls3",
	"2KpDIvI9d3mZF4aWaSxNiirsnvJYXM2U2Al8TyEo/yVP/k8eN5PHp9XupzPOVrFueTsEqDABxYwyvsuN",
	"lGV0iltNKLaqz02vaXVR1v8YF4pZgN08EI1aMylOpPzGkIxu7hZ3jcSVjUXJJ7tyZTs69j/rhnQp1SyS",
	"5uxfOPe9RSYmMtCyQz55k0ptMIHT22I4fPv307pBBynyHNUhXKdMg84xBqZdg0EzMeUIZY9UTsCowqQw",
	"kepW2O8ffj+DWApjD+YjN+KTBI1qhgrsWVdNaIxAReK+2Zpx5YyCmLuOL1UIY2nSWzFFgcpu6TBRMgNm",
	"4OCPjH5DqD788frwVtQsYeQLNRxLqhJrBonIDJX2qx0eHh0OXbMjR0FzRkbk3eHw8J0tLNSkztWDzgln",
	"iq6KWAC6jLW7OfmNaXNSSy118N8Oh49qDe/sDLXaQLZ22uDUK4J7ZtJWZ+qVdr11YAKQxqmd8/3wqM+Y",
	"epmDTh/cgbrIMqrmZFQ3ST1OYn+UBEtVYIxciqkGI62iXOqAa7tdiPJqBbU5lsl8Zx33cKtj0U1kWwMW",
	"K7E92p0RdQd4NXDewKQOnA/McHNgWtdHu4ilMwNoUxAOyo7mGGOZoQZmNJyev3bjmsQZfJXMX0oEY9w+",
	"wD5ThENn5K3iO9x5fNspuxrp6xTdxUgr2D1Juj8M2EHvNw+qL+O6oLGub0OGaqDlVRAUdt9woPFXLe6e",
	"aBk8D83hbzGoe9YbqnEjtpdyXF+qbFGFG9tg6QLsCfF5t3lQc5fbDdB1y4JXGnKqzByUpQAKDvzNgQYp",
	"+Nxdubav+W/CKhuRQesZgGUya2t87cNnKvLda4F9V/cGIWvKextG+8vtJ2DnQ5LY3K7sBnlvK9d43r7t",
	"OqBi3qS/B9TrtUnuFrQ+wS+8yD6S+6Jy76bE9jb5cl0e0hylLbtN/5UAOcrn/QmyXYdfaRg7TrzHFPee",
	"fE4O1znt7znFLxql4fRu5ekLSO3fpTZAQeC9NxwOTs8rjKzJXYXVQeyN39OX34btCFGXtZ4zr2YP1C0Y",
	"3BWWZj3WoTN7it7TaNqn0ptAYaJQp+0lrIS+ZjCDh9bjuoVvJ3D0Qe/G69T9v7vJd8L1PvCUAX3X9GV4",
	"8BIzOcPOdnhgqa176wBSOXC4w9GjS2zrAaPLCGridNXFvuH5M/Ko4X54lHfAC+FRTwObX+o2YLMJm9bX",
	"0kFC9QlNeXH9jJErNQTCdoVqxmIEb6VrSv/NO3NPiutr+KV+7F2XSc1QoNYwAIU0Ye7vXMlxeWD1reA+",
	"/7bfUDxnerTUBBb8of161DXhdtEWum4ae3zefaHqG31lX5ep5WOATlmuvfs8Rx08lI+ot9hLGjb5P7qP",
	"rNCux+4b1XP1jXvGcxLzwDXcnveMXmJe7Rc/PTHf0V7hjI6AiZgXSdV587dvLkerQ+sS3VtOzUFcPYjo",
	"S9Avwon0ZOgeIusvfejE7ouFN6a8s3sRBYAj1TZgucIZk4XmcyhfdDRYfUIpCB/Rf56IvbB4Oc819bqn",
	"3bXlVa+aVREtFCcjMqA5I4u7xX8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
