/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness / readiness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The currently authenticated user and their campaign memberships */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaigns the current user belongs to */
        get: operations["listCampaigns"];
        put?: never;
        /** Create a campaign (caller becomes its DM) */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a campaign as a player using its invite code */
        post: operations["joinCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/regenerate-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a fresh invite code (DM only) */
        post: operations["regenerateInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/next-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Set or clear when the table gathers next (DM only) */
        put: operations["setNextSession"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/quests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        /** List quests on a campaign's board (members only) */
        get: operations["listQuests"];
        put?: never;
        /** Post a new quest (DM only) */
        post: operations["createQuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/{questId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a quest (DM only) */
        delete: operations["deleteQuest"];
        options?: never;
        head?: never;
        /** Update a quest, including its status and rewards (DM only) */
        patch: operations["updateQuest"];
        trace?: never;
    };
    "/campaigns/{campaignId}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        /** The campaign's party roster (members only) */
        get: operations["listCharacters"];
        put?: never;
        /** Add a character owned by the caller (any campaign member) */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a character (its owner or the DM) */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        /** Update a character (its owner or the DM) */
        patch: operations["updateCharacter"];
        trace?: never;
    };
    "/campaigns/{campaignId}/trees": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        /** The campaign's skill trees (members only) */
        get: operations["listTrees"];
        put?: never;
        /** Create a skill tree (DM only) */
        post: operations["createTree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trees/{treeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        /** A skill tree with its full web (members only) */
        get: operations["getTree"];
        put?: never;
        post?: never;
        /** Delete a skill tree and its web (DM only) */
        delete: operations["deleteTree"];
        options?: never;
        head?: never;
        /** Update a skill tree (DM only) */
        patch: operations["updateTree"];
        trace?: never;
    };
    "/trees/{treeId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a power node to a tree (DM only) */
        post: operations["createNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trees/{treeId}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the tree's web of connections (DM only) */
        put: operations["setEdges"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a power node (DM only) */
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        /** Update a power node (DM only) */
        patch: operations["updateNode"];
        trace?: never;
    };
    "/characters/{characterId}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /** A character's pact and web progress (members only) */
        get: operations["getCharacterTree"];
        /** Bind a character to a tree — the pact (DM only) */
        put: operations["setCharacterTree"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}/tree/grants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant unspent picks at a story beat (DM only) */
        post: operations["grantPicks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}/tree/picks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Spend a granted pick on a reachable node (owner or DM) */
        post: operations["spendPick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quests/{questId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a quest (any campaign member) */
        post: operations["claimQuest"];
        /** Release a previously claimed quest */
        delete: operations["unclaimQuest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
        };
        Error: {
            error: string;
        };
        /** @enum {string} */
        Role: "dm" | "player";
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            email?: string | null;
            image?: string | null;
        };
        Campaign: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            ownerUserId: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Shareable code players use to join the campaign. */
            inviteCode: string;
            /**
             * Format: date-time
             * @description When the table gathers next; null when unscheduled.
             */
            nextSessionAt?: string | null;
        };
        CampaignMembership: {
            campaign: components["schemas"]["Campaign"];
            role: components["schemas"]["Role"];
        };
        CurrentUser: {
            user: components["schemas"]["User"];
            campaigns: components["schemas"]["CampaignMembership"][];
        };
        CreateCampaignRequest: {
            name: string;
        };
        JoinCampaignRequest: {
            code: string;
        };
        SetNextSessionRequest: {
            /**
             * Format: date-time
             * @description Omit or send null to clear the scheduled session.
             */
            nextSessionAt?: string | null;
        };
        /** @enum {string} */
        QuestStatus: "available" | "active" | "completed" | "failed";
        /** @enum {string} */
        QuestDifficulty: "trivial" | "easy" | "medium" | "hard" | "deadly";
        /** @enum {string} */
        RewardType: "gold" | "item" | "xp" | "reputation" | "other";
        QuestReward: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["RewardType"];
            label: string;
            value?: string | null;
        };
        QuestClaim: {
            /** Format: uuid */
            userId: string;
            userName: string;
            /** Format: date-time */
            claimedAt: string;
        };
        Quest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaignId: string;
            title: string;
            description: string;
            giver?: string | null;
            location?: string | null;
            difficulty: components["schemas"]["QuestDifficulty"];
            status: components["schemas"]["QuestStatus"];
            /** Format: date-time */
            createdAt: string;
            rewards: components["schemas"]["QuestReward"][];
            claims: components["schemas"]["QuestClaim"][];
            claimedByMe: boolean;
        };
        Character: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaignId: string;
            /** Format: uuid */
            ownerUserId: string;
            /** @description Display name of the member who plays this character. */
            ownerName: string;
            name: string;
            /** @description Freeform class/ancestry line, e.g. "Half-Elf Bard". */
            class: string;
            level: number;
            hpCurrent: number;
            hpMax: number;
            /** Format: date-time */
            createdAt: string;
            /** @description True when the caller owns this character. */
            mine: boolean;
        };
        CharacterInput: {
            name: string;
            class?: string;
            level: number;
            hpCurrent: number;
            hpMax: number;
        };
        /** @enum {string} */
        NodeRarity: "minor" | "keystone";
        SkillTree: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaignId: string;
            name: string;
            description: string;
            /** @description How many picks a keystone eats (1 = gated only by the web). */
            keystonePickCost: number;
            /** Format: date-time */
            createdAt: string;
        };
        SkillTreeInput: {
            name: string;
            description?: string;
            /** @default 1 */
            keystonePickCost: number;
        };
        SkillNode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            treeId: string;
            name: string;
            description: string;
            /** @description The price baked into a keystone. */
            tradeoff?: string | null;
            rarity: components["schemas"]["NodeRarity"];
            /** @description Grouping label within the web, e.g. ENTROPY. */
            limb: string;
            /** @description Pickable with no prior picks in the tree. */
            isEntry: boolean;
            posX?: number | null;
            posY?: number | null;
        };
        SkillNodeInput: {
            name: string;
            description?: string;
            tradeoff?: string | null;
            rarity: components["schemas"]["NodeRarity"];
            limb?: string;
            /** @default false */
            isEntry: boolean;
            posX?: number | null;
            posY?: number | null;
        };
        SkillEdge: {
            /** Format: uuid */
            a: string;
            /** Format: uuid */
            b: string;
        };
        SkillEdgesInput: {
            edges: components["schemas"]["SkillEdge"][];
        };
        SkillTreeDetail: {
            tree: components["schemas"]["SkillTree"];
            nodes: components["schemas"]["SkillNode"][];
            edges: components["schemas"]["SkillEdge"][];
        };
        CharacterTreeState: {
            assigned: boolean;
            tree?: components["schemas"]["SkillTreeDetail"];
            picksGranted?: number;
            /** @description Picks consumed by taken nodes (keystones may cost more). */
            picksSpent?: number;
            picksRemaining?: number;
            takenNodeIds?: string[];
        };
        SetPactRequest: {
            /** Format: uuid */
            treeId: string;
        };
        GrantPicksRequest: {
            picks: number;
        };
        SpendPickRequest: {
            /** Format: uuid */
            nodeId: string;
        };
        RewardInput: {
            type: components["schemas"]["RewardType"];
            label: string;
            value?: string | null;
        };
        CreateQuestRequest: {
            title: string;
            description?: string;
            giver?: string | null;
            location?: string | null;
            difficulty?: components["schemas"]["QuestDifficulty"];
            rewards?: components["schemas"]["RewardInput"][];
        };
        UpdateQuestRequest: {
            title: string;
            description?: string;
            giver?: string | null;
            location?: string | null;
            difficulty: components["schemas"]["QuestDifficulty"];
            status: components["schemas"]["QuestStatus"];
            rewards?: components["schemas"]["RewardInput"][];
        };
    };
    responses: {
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed (not a member, or insufficient role) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CampaignId: string;
        QuestId: string;
        CharacterId: string;
        TreeId: string;
        NodeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of campaigns with the caller's role in each */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignMembership"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description Created campaign */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    joinCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinCampaignRequest"];
            };
        };
        responses: {
            /** @description The joined campaign with the caller's role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignMembership"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    regenerateInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign with the new invite code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setNextSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetNextSessionRequest"];
            };
        };
        responses: {
            /** @description Campaign with the updated next session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listQuests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quests with rewards and claims */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestRequest"];
            };
        };
        responses: {
            /** @description Created quest */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestRequest"];
            };
        };
        responses: {
            /** @description Updated quest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Characters in the campaign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterInput"];
            };
        };
        responses: {
            /** @description Created character */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterInput"];
            };
        };
        responses: {
            /** @description Updated character */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTrees: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill trees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTree"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillTreeInput"];
            };
        };
        responses: {
            /** @description Created tree */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tree with nodes and edges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTreeDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillTreeInput"];
            };
        };
        responses: {
            /** @description Updated tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTree"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillNodeInput"];
            };
        };
        responses: {
            /** @description Created node */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNode"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setEdges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: components["parameters"]["TreeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillEdgesInput"];
            };
        };
        responses: {
            /** @description Tree with the new web */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillTreeDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillNodeInput"];
            };
        };
        responses: {
            /** @description Updated node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillNode"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCharacterTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pact state (assigned=false when no tree is bound) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterTreeState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setCharacterTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPactRequest"];
            };
        };
        responses: {
            /** @description New pact state (a changed tree resets progress) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterTreeState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    grantPicks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantPicksRequest"];
            };
        };
        responses: {
            /** @description Pact state with the new grant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterTreeState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    spendPick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpendPickRequest"];
            };
        };
        responses: {
            /** @description Pact state including the new power */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterTreeState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    claimQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quest after claiming */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    unclaimQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quest after unclaiming */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
