// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLiveAPITokensByUser = `-- name: CountLiveAPITokensByUser :one
SELECT count(*) FROM api_tokens
WHERE user_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CountLiveAPITokensByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveAPITokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, name, prefix, token_hash, scopes, campaign_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, prefix, token_hash, scopes, campaign_id, created_at, last_used_at, expires_at, revoked_at, throttled_at
`

type CreateAPITokenParams struct {
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	TokenHash  string             `json:"token_hash"`
	Scopes     []string           `json:"scopes"`
	CampaignID pgtype.UUID        `json:"campaign_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// API tokens (#294). The secret never touches the database: every query keys
// on its hash.
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Scopes,
		arg.CampaignID,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scopes,
		&i.CampaignID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ThrottledAt,
	)
	return i, err
}

const getLiveAPITokenByHash = `-- name: GetLiveAPITokenByHash :one
SELECT id, user_id, name, prefix, token_hash, scopes, campaign_id, created_at, last_used_at, expires_at, revoked_at, throttled_at FROM api_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

// The one lookup the bearer loader makes: a revoked or expired token is no row.
func (q *Queries) GetLiveAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getLiveAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scopes,
		&i.CampaignID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ThrottledAt,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT t.id, t.user_id, t.name, t.prefix, t.token_hash, t.scopes, t.campaign_id, t.created_at, t.last_used_at, t.expires_at, t.revoked_at, t.throttled_at, c.name AS campaign_name
FROM api_tokens t
LEFT JOIN campaigns c ON c.id = t.campaign_id
WHERE t.user_id = $1 AND t.revoked_at IS NULL
ORDER BY t.created_at DESC
`

type ListAPITokensByUserRow struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Prefix       string             `json:"prefix"`
	TokenHash    string             `json:"token_hash"`
	Scopes       []string           `json:"scopes"`
	CampaignID   pgtype.UUID        `json:"campaign_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	ThrottledAt  pgtype.Timestamptz `json:"throttled_at"`
	CampaignName *string            `json:"campaign_name"`
}

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID uuid.UUID) ([]ListAPITokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensByUserRow
	for rows.Next() {
		var i ListAPITokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.TokenHash,
			&i.Scopes,
			&i.CampaignID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ThrottledAt,
			&i.CampaignName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeAPITokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const throttleAPIToken = `-- name: ThrottleAPIToken :exec
UPDATE api_tokens SET throttled_at = now()
WHERE id = $1 AND (throttled_at IS NULL OR throttled_at < now() - interval '1 minute')
`

// The ceiling badge (#314): written at most once a minute, like last_used_at.
func (q *Queries) ThrottleAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, throttleAPIToken, id)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// Written at most once a minute per token, so a busy script costs one UPDATE
// rather than one per request.
func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
