// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bestiary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addBestiaryNote = `-- name: AddBestiaryNote :one
INSERT INTO bestiary_notes (entry_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id
`

type AddBestiaryNoteParams struct {
	EntryID  uuid.UUID   `json:"entry_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) AddBestiaryNote(ctx context.Context, arg AddBestiaryNoteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addBestiaryNote, arg.EntryID, arg.AuthorID, arg.Body)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createBestiaryEntry = `-- name: CreateBestiaryEntry :one
INSERT INTO bestiary_entries (campaign_id, title, created_by)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateBestiaryEntryParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	Title      string      `json:"title"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateBestiaryEntry(ctx context.Context, arg CreateBestiaryEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBestiaryEntry, arg.CampaignID, arg.Title, arg.CreatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteBestiaryEntry = `-- name: DeleteBestiaryEntry :exec
DELETE FROM bestiary_entries WHERE id = $1
`

func (q *Queries) DeleteBestiaryEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBestiaryEntry, id)
	return err
}

const deleteBestiaryNote = `-- name: DeleteBestiaryNote :exec
DELETE FROM bestiary_notes WHERE id = $1
`

func (q *Queries) DeleteBestiaryNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBestiaryNote, id)
	return err
}

const getBestiaryEntry = `-- name: GetBestiaryEntry :one
SELECT be.id, be.campaign_id, be.content_id, be.title, be.revealed,
       be.created_by, be.created_at,
       rc.name AS monster_name, rc.data AS monster_data
FROM bestiary_entries be
LEFT JOIN rules_content rc ON rc.id = be.content_id
WHERE be.id = $1
`

type GetBestiaryEntryRow struct {
	ID          uuid.UUID          `json:"id"`
	CampaignID  uuid.UUID          `json:"campaign_id"`
	ContentID   pgtype.UUID        `json:"content_id"`
	Title       string             `json:"title"`
	Revealed    []string           `json:"revealed"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MonsterName *string            `json:"monster_name"`
	MonsterData []byte             `json:"monster_data"`
}

func (q *Queries) GetBestiaryEntry(ctx context.Context, id uuid.UUID) (GetBestiaryEntryRow, error) {
	row := q.db.QueryRow(ctx, getBestiaryEntry, id)
	var i GetBestiaryEntryRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContentID,
		&i.Title,
		&i.Revealed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.MonsterName,
		&i.MonsterData,
	)
	return i, err
}

const getBestiaryNote = `-- name: GetBestiaryNote :one
SELECT id, entry_id, author_id, body, created_at FROM bestiary_notes WHERE id = $1
`

func (q *Queries) GetBestiaryNote(ctx context.Context, id uuid.UUID) (BestiaryNote, error) {
	row := q.db.QueryRow(ctx, getBestiaryNote, id)
	var i BestiaryNote
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listBestiaryEntries = `-- name: ListBestiaryEntries :many
SELECT be.id, be.campaign_id, be.content_id, be.title, be.revealed,
       be.created_by, be.created_at,
       rc.name AS monster_name, rc.data AS monster_data
FROM bestiary_entries be
LEFT JOIN rules_content rc ON rc.id = be.content_id
WHERE be.campaign_id = $1
ORDER BY be.created_at DESC
`

type ListBestiaryEntriesRow struct {
	ID          uuid.UUID          `json:"id"`
	CampaignID  uuid.UUID          `json:"campaign_id"`
	ContentID   pgtype.UUID        `json:"content_id"`
	Title       string             `json:"title"`
	Revealed    []string           `json:"revealed"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MonsterName *string            `json:"monster_name"`
	MonsterData []byte             `json:"monster_data"`
}

// Every sighting in a campaign, with the linked monster's data when
// identified. Newest first; the creature's true name comes from content.
func (q *Queries) ListBestiaryEntries(ctx context.Context, campaignID uuid.UUID) ([]ListBestiaryEntriesRow, error) {
	rows, err := q.db.Query(ctx, listBestiaryEntries, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBestiaryEntriesRow
	for rows.Next() {
		var i ListBestiaryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContentID,
			&i.Title,
			&i.Revealed,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MonsterName,
			&i.MonsterData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBestiaryNotes = `-- name: ListBestiaryNotes :many
SELECT bn.id, bn.entry_id, bn.author_id, bn.body, bn.created_at,
       u.name AS author_name
FROM bestiary_notes bn
LEFT JOIN users u ON u.id = bn.author_id
WHERE bn.entry_id = ANY($1::uuid[])
ORDER BY bn.created_at ASC
`

type ListBestiaryNotesRow struct {
	ID         uuid.UUID          `json:"id"`
	EntryID    uuid.UUID          `json:"entry_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName *string            `json:"author_name"`
}

// Field notes across a set of entries, oldest first, with the author's name.
func (q *Queries) ListBestiaryNotes(ctx context.Context, dollar_1 []uuid.UUID) ([]ListBestiaryNotesRow, error) {
	rows, err := q.db.Query(ctx, listBestiaryNotes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBestiaryNotesRow
	for rows.Next() {
		var i ListBestiaryNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBestiaryEntry = `-- name: UpdateBestiaryEntry :exec
UPDATE bestiary_entries
SET title = $2, content_id = $3, revealed = $4, updated_at = now()
WHERE id = $1
`

type UpdateBestiaryEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	Title     string      `json:"title"`
	ContentID pgtype.UUID `json:"content_id"`
	Revealed  []string    `json:"revealed"`
}

func (q *Queries) UpdateBestiaryEntry(ctx context.Context, arg UpdateBestiaryEntryParams) error {
	_, err := q.db.Exec(ctx, updateBestiaryEntry,
		arg.ID,
		arg.Title,
		arg.ContentID,
		arg.Revealed,
	)
	return err
}
