// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :one
INSERT INTO memberships (user_id, campaign_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, campaign_id) DO UPDATE SET role = EXCLUDED.role
RETURNING user_id, campaign_id, role, created_at
`

type AddMembershipParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	CampaignID uuid.UUID      `json:"campaign_id"`
	Role       MembershipRole `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.UserID, arg.CampaignID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.CampaignID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, owner_user_id, invite_code, realm_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type CreateCampaignParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	InviteCode  string    `json:"invite_code"`
	RealmID     uuid.UUID `json:"realm_id"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.OwnerUserID,
		arg.InviteCode,
		arg.RealmID,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

// Everything scoped to the campaign cascades: memberships, quests, skill
// trees, codex rulings, chronicle events, bestiary notes, maps, encounters,
// bans, and seat requests. Characters are handled separately beforehand —
// table-born ones die with the table, seated heroes are unseated first.
func (q *Queries) DeleteCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const getCampaignByInviteCode = `-- name: GetCampaignByInviteCode :one
SELECT id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage FROM campaigns WHERE invite_code = $1
`

func (q *Queries) GetCampaignByInviteCode(ctx context.Context, inviteCode string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByInviteCode, inviteCode)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, campaign_id, role, created_at FROM memberships WHERE user_id = $1 AND campaign_id = $2
`

type GetMembershipParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

// Used by role guards: returns the caller's role in a campaign, if any.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.CampaignID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.CampaignID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const joinCampaign = `-- name: JoinCampaign :exec
INSERT INTO memberships (user_id, campaign_id, role)
VALUES ($1, $2, 'player')
ON CONFLICT (user_id, campaign_id) DO NOTHING
`

type JoinCampaignParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

// Add the user as a player; never downgrades an existing (e.g. DM) membership.
func (q *Queries) JoinCampaign(ctx context.Context, arg JoinCampaignParams) error {
	_, err := q.db.Exec(ctx, joinCampaign, arg.UserID, arg.CampaignID)
	return err
}

const listCampaignsForUser = `-- name: ListCampaignsForUser :many
SELECT c.id, c.name, c.owner_user_id, c.created_at, c.invite_code, c.next_session_at, c.progression, c.max_level, c.require_seating_approval, c.hidden_sheets, c.max_seated_per_player, c.realm_id, c.coinage, m.role, r.name AS realm_name
FROM campaigns c
JOIN memberships m ON m.campaign_id = c.id
JOIN realms r ON r.id = c.realm_id
WHERE m.user_id = $1
ORDER BY c.created_at
`

type ListCampaignsForUserRow struct {
	ID                     uuid.UUID          `json:"id"`
	Name                   string             `json:"name"`
	OwnerUserID            uuid.UUID          `json:"owner_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	InviteCode             string             `json:"invite_code"`
	NextSessionAt          pgtype.Timestamptz `json:"next_session_at"`
	Progression            ProgressionMode    `json:"progression"`
	MaxLevel               *int16             `json:"max_level"`
	RequireSeatingApproval bool               `json:"require_seating_approval"`
	HiddenSheets           bool               `json:"hidden_sheets"`
	MaxSeatedPerPlayer     int16              `json:"max_seated_per_player"`
	RealmID                uuid.UUID          `json:"realm_id"`
	Coinage                []byte             `json:"coinage"`
	Role                   MembershipRole     `json:"role"`
	RealmName              string             `json:"realm_name"`
}

// Campaigns the user belongs to, with their per-campaign role and the realm
// they stand in (#233). The realm's NAME rides along for everyone, DM and
// player alike: a table knowing the name of its setting is not a secret, and
// it is the only way a player ever learns it. Who may LIST, rename, move or
// strike a realm is a separate question, and the answer is its owner.
func (q *Queries) ListCampaignsForUser(ctx context.Context, userID uuid.UUID) ([]ListCampaignsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsForUserRow
	for rows.Next() {
		var i ListCampaignsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.InviteCode,
			&i.NextSessionAt,
			&i.Progression,
			&i.MaxLevel,
			&i.RequireSeatingApproval,
			&i.HiddenSheets,
			&i.MaxSeatedPerPlayer,
			&i.RealmID,
			&i.Coinage,
			&i.Role,
			&i.RealmName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateInviteCode = `-- name: RegenerateInviteCode :one
UPDATE campaigns SET invite_code = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type RegenerateInviteCodeParams struct {
	ID         uuid.UUID `json:"id"`
	InviteCode string    `json:"invite_code"`
}

func (q *Queries) RegenerateInviteCode(ctx context.Context, arg RegenerateInviteCodeParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, regenerateInviteCode, arg.ID, arg.InviteCode)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setCoinage = `-- name: SetCoinage :one
UPDATE campaigns SET coinage = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetCoinageParams struct {
	ID      uuid.UUID `json:"id"`
	Coinage []byte    `json:"coinage"`
}

// The coins a table counts in (#195). NULL puts it back on the standard ladder.
func (q *Queries) SetCoinage(ctx context.Context, arg SetCoinageParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCoinage, arg.ID, arg.Coinage)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setHiddenSheets = `-- name: SetHiddenSheets :one
UPDATE campaigns SET hidden_sheets = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetHiddenSheetsParams struct {
	ID           uuid.UUID `json:"id"`
	HiddenSheets bool      `json:"hidden_sheets"`
}

// Draw or lift the veil over the table's character sheets.
func (q *Queries) SetHiddenSheets(ctx context.Context, arg SetHiddenSheetsParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setHiddenSheets, arg.ID, arg.HiddenSheets)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setMaxLevel = `-- name: SetMaxLevel :one
UPDATE campaigns SET max_level = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetMaxLevelParams struct {
	ID       uuid.UUID `json:"id"`
	MaxLevel *int16    `json:"max_level"`
}

func (q *Queries) SetMaxLevel(ctx context.Context, arg SetMaxLevelParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setMaxLevel, arg.ID, arg.MaxLevel)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setMaxSeatedPerPlayer = `-- name: SetMaxSeatedPerPlayer :one
UPDATE campaigns SET max_seated_per_player = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetMaxSeatedPerPlayerParams struct {
	ID                 uuid.UUID `json:"id"`
	MaxSeatedPerPlayer int16     `json:"max_seated_per_player"`
}

func (q *Queries) SetMaxSeatedPerPlayer(ctx context.Context, arg SetMaxSeatedPerPlayerParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setMaxSeatedPerPlayer, arg.ID, arg.MaxSeatedPerPlayer)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setNextSession = `-- name: SetNextSession :one
UPDATE campaigns SET next_session_at = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetNextSessionParams struct {
	ID            uuid.UUID          `json:"id"`
	NextSessionAt pgtype.Timestamptz `json:"next_session_at"`
}

func (q *Queries) SetNextSession(ctx context.Context, arg SetNextSessionParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setNextSession, arg.ID, arg.NextSessionAt)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}

const setProgression = `-- name: SetProgression :one
UPDATE campaigns SET progression = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetProgressionParams struct {
	ID          uuid.UUID       `json:"id"`
	Progression ProgressionMode `json:"progression"`
}

func (q *Queries) SetProgression(ctx context.Context, arg SetProgressionParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setProgression, arg.ID, arg.Progression)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}
