// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :one
INSERT INTO memberships (user_id, campaign_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, campaign_id) DO UPDATE SET role = EXCLUDED.role
RETURNING user_id, campaign_id, role, created_at
`

type AddMembershipParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	CampaignID uuid.UUID      `json:"campaign_id"`
	Role       MembershipRole `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.UserID, arg.CampaignID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.CampaignID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (name, owner_user_id)
VALUES ($1, $2)
RETURNING id, name, owner_user_id, created_at
`

type CreateCampaignParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign, arg.Name, arg.OwnerUserID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, owner_user_id, created_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, campaign_id, role, created_at FROM memberships WHERE user_id = $1 AND campaign_id = $2
`

type GetMembershipParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

// Used by role guards: returns the caller's role in a campaign, if any.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.CampaignID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.CampaignID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaignsForUser = `-- name: ListCampaignsForUser :many
SELECT c.id, c.name, c.owner_user_id, c.created_at, m.role
FROM campaigns c
JOIN memberships m ON m.campaign_id = c.id
WHERE m.user_id = $1
ORDER BY c.created_at
`

type ListCampaignsForUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Role        MembershipRole     `json:"role"`
}

// Campaigns the user belongs to, with their per-campaign role.
func (q *Queries) ListCampaignsForUser(ctx context.Context, userID uuid.UUID) ([]ListCampaignsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsForUserRow
	for rows.Next() {
		var i ListCampaignsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
