// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const characterByForgeKey = `-- name: CharacterByForgeKey :one
SELECT id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used FROM characters
WHERE owner_user_id = $1 AND forge_key = $2
`

type CharacterByForgeKeyParams struct {
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	ForgeKey    pgtype.UUID `json:"forge_key"`
}

// The hero a previous forge attempt already made with this key, if any. A
// timed-out forge that in fact landed is found here, so the retry returns the
// twin's older sibling instead of making one.
func (q *Queries) CharacterByForgeKey(ctx context.Context, arg CharacterByForgeKeyParams) (Character, error) {
	row := q.db.QueryRow(ctx, characterByForgeKey, arg.OwnerUserID, arg.ForgeKey)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const concealCharacter = `-- name: ConcealCharacter :exec
DELETE FROM character_reveals WHERE campaign_id = $1 AND character_id = $2
`

type ConcealCharacterParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) ConcealCharacter(ctx context.Context, arg ConcealCharacterParams) error {
	_, err := q.db.Exec(ctx, concealCharacter, arg.CampaignID, arg.CharacterID)
	return err
}

const countSeatedByOwner = `-- name: CountSeatedByOwner :one
SELECT COUNT(*) FROM characters
WHERE owner_user_id = $1 AND campaign_id = $2 AND NOT table_born AND id <> $3
`

type CountSeatedByOwnerParams struct {
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
	ID          uuid.UUID   `json:"id"`
}

// How many of a player's heroes already hold a seat at this table, besides
// the one asking. Table-born characters are the DM's roster, not a seat taken.
func (q *Queries) CountSeatedByOwner(ctx context.Context, arg CountSeatedByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSeatedByOwner, arg.OwnerUserID, arg.CampaignID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountCharacter = `-- name: CreateAccountCharacter :one
INSERT INTO characters (campaign_id, owner_user_id, name, class, level, hp_current, hp_max)
VALUES (NULL, $1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type CreateAccountCharacterParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Class       string    `json:"class"`
	Level       int32     `json:"level"`
	HpCurrent   int32     `json:"hp_current"`
	HpMax       int32     `json:"hp_max"`
}

// A hero created in My Heroes, not yet seated anywhere.
func (q *Queries) CreateAccountCharacter(ctx context.Context, arg CreateAccountCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createAccountCharacter,
		arg.OwnerUserID,
		arg.Name,
		arg.Class,
		arg.Level,
		arg.HpCurrent,
		arg.HpMax,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (campaign_id, owner_user_id, name, class, level, hp_current, hp_max, table_born)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type CreateCharacterParams struct {
	CampaignID  pgtype.UUID `json:"campaign_id"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	Name        string      `json:"name"`
	Class       string      `json:"class"`
	Level       int32       `json:"level"`
	HpCurrent   int32       `json:"hp_current"`
	HpMax       int32       `json:"hp_max"`
}

// Quick-add straight onto a roster: the character is born of the table.
func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.CampaignID,
		arg.OwnerUserID,
		arg.Name,
		arg.Class,
		arg.Level,
		arg.HpCurrent,
		arg.HpMax,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const deleteTableBornOfCampaign = `-- name: DeleteTableBornOfCampaign :exec
DELETE FROM characters
WHERE campaign_id = $1 AND table_born
`

// A struck campaign's table-born characters die with the table.
func (q *Queries) DeleteTableBornOfCampaign(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTableBornOfCampaign, campaignID)
	return err
}

const deleteTableBornOfUser = `-- name: DeleteTableBornOfUser :exec
DELETE FROM characters
WHERE owner_user_id = $1 AND campaign_id = $2 AND table_born
`

type DeleteTableBornOfUserParams struct {
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	CampaignID  pgtype.UUID `json:"campaign_id"`
}

// A kicked player's table-born characters die with their seat.
func (q *Queries) DeleteTableBornOfUser(ctx context.Context, arg DeleteTableBornOfUserParams) error {
	_, err := q.db.Exec(ctx, deleteTableBornOfUser, arg.OwnerUserID, arg.CampaignID)
	return err
}

const forgeCharacter = `-- name: ForgeCharacter :one
INSERT INTO characters (
    campaign_id, owner_user_id, name, class, level, hp_current, hp_max,
    strength, dexterity, constitution, intelligence, wisdom, charisma,
    skills, class_id, species_id, background_id, feats, species_choices, forge_key
) VALUES (NULL, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type ForgeCharacterParams struct {
	OwnerUserID    uuid.UUID   `json:"owner_user_id"`
	Name           string      `json:"name"`
	Class          string      `json:"class"`
	Level          int32       `json:"level"`
	HpCurrent      int32       `json:"hp_current"`
	HpMax          int32       `json:"hp_max"`
	Strength       *int16      `json:"strength"`
	Dexterity      *int16      `json:"dexterity"`
	Constitution   *int16      `json:"constitution"`
	Intelligence   *int16      `json:"intelligence"`
	Wisdom         *int16      `json:"wisdom"`
	Charisma       *int16      `json:"charisma"`
	Skills         []string    `json:"skills"`
	ClassID        pgtype.UUID `json:"class_id"`
	SpeciesID      pgtype.UUID `json:"species_id"`
	BackgroundID   pgtype.UUID `json:"background_id"`
	Feats          []string    `json:"feats"`
	SpeciesChoices []byte      `json:"species_choices"`
	ForgeKey       pgtype.UUID `json:"forge_key"`
}

// A wizard-built hero: full sheet, created unseated in My Heroes.
func (q *Queries) ForgeCharacter(ctx context.Context, arg ForgeCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, forgeCharacter,
		arg.OwnerUserID,
		arg.Name,
		arg.Class,
		arg.Level,
		arg.HpCurrent,
		arg.HpMax,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		arg.Skills,
		arg.ClassID,
		arg.SpeciesID,
		arg.BackgroundID,
		arg.Feats,
		arg.SpeciesChoices,
		arg.ForgeKey,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used FROM characters WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const grantMilestone = `-- name: GrantMilestone :exec
UPDATE characters
SET pending_levels = pending_levels + 1, updated_at = now()
WHERE campaign_id = $1 AND level < $2
`

type GrantMilestoneParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Level      int32       `json:"level"`
}

// One pending level-up for every hero seated at the campaign, except those
// already standing at the table's ceiling.
func (q *Queries) GrantMilestone(ctx context.Context, arg GrantMilestoneParams) error {
	_, err := q.db.Exec(ctx, grantMilestone, arg.CampaignID, arg.Level)
	return err
}

const grantMilestoneTo = `-- name: GrantMilestoneTo :exec
UPDATE characters
SET pending_levels = pending_levels + 1, updated_at = now()
WHERE campaign_id = $1
  AND level < $2
  AND id = ANY($3::uuid[])
`

type GrantMilestoneToParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Ceiling    int32       `json:"ceiling"`
	Ids        []uuid.UUID `json:"ids"`
}

// One pending level-up for the chosen seated heroes, ceiling respected.
func (q *Queries) GrantMilestoneTo(ctx context.Context, arg GrantMilestoneToParams) error {
	_, err := q.db.Exec(ctx, grantMilestoneTo, arg.CampaignID, arg.Ceiling, arg.Ids)
	return err
}

const grantXP = `-- name: GrantXP :many
UPDATE characters
SET xp = GREATEST(xp + $2, 0), updated_at = now()
WHERE campaign_id = $1 AND id = ANY($3::uuid[])
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type GrantXPParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Xp         int32       `json:"xp"`
	Column3    []uuid.UUID `json:"column_3"`
}

// Add (or dock) XP for a set of seated heroes; totals never go below zero.
func (q *Queries) GrantXP(ctx context.Context, arg GrantXPParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, grantXP, arg.CampaignID, arg.Xp, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.OwnerUserID,
			&i.Name,
			&i.Class,
			&i.Level,
			&i.HpCurrent,
			&i.HpMax,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.Skills,
			&i.ClassID,
			&i.SpeciesID,
			&i.BackgroundID,
			&i.SubclassID,
			&i.Feats,
			&i.SpellSlotsUsed,
			&i.Xp,
			&i.PendingLevels,
			&i.TableBorn,
			&i.SpeciesChoices,
			&i.ForgeKey,
			&i.HitDiceUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const levelUpCharacter = `-- name: LevelUpCharacter :one
UPDATE characters
SET level = $2,
    hp_max = $3,
    hp_current = $4,
    strength = $5, dexterity = $6, constitution = $7,
    intelligence = $8, wisdom = $9, charisma = $10,
    subclass_id = $11,
    feats = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type LevelUpCharacterParams struct {
	ID           uuid.UUID   `json:"id"`
	Level        int32       `json:"level"`
	HpMax        int32       `json:"hp_max"`
	HpCurrent    int32       `json:"hp_current"`
	Strength     *int16      `json:"strength"`
	Dexterity    *int16      `json:"dexterity"`
	Constitution *int16      `json:"constitution"`
	Intelligence *int16      `json:"intelligence"`
	Wisdom       *int16      `json:"wisdom"`
	Charisma     *int16      `json:"charisma"`
	SubclassID   pgtype.UUID `json:"subclass_id"`
	Feats        []string    `json:"feats"`
}

// Apply one level: new level/HP, any ability increases (ASI), the chosen
// subclass when the class reaches it, and any feat taken along the way.
func (q *Queries) LevelUpCharacter(ctx context.Context, arg LevelUpCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, levelUpCharacter,
		arg.ID,
		arg.Level,
		arg.HpMax,
		arg.HpCurrent,
		arg.Strength,
		arg.Dexterity,
		arg.Constitution,
		arg.Intelligence,
		arg.Wisdom,
		arg.Charisma,
		arg.SubclassID,
		arg.Feats,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const listCharacterReveals = `-- name: ListCharacterReveals :many
SELECT character_id FROM character_reveals WHERE campaign_id = $1
`

// The heroes standing in the light at this table — their sheets are open to
// the party even while the veil is drawn.
func (q *Queries) ListCharacterReveals(ctx context.Context, campaignID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCharacterReveals, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var character_id uuid.UUID
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByCampaign = `-- name: ListCharactersByCampaign :many
SELECT c.id, c.campaign_id, c.owner_user_id, c.name, c.class, c.level, c.hp_current, c.hp_max, c.created_at, c.updated_at, c.strength, c.dexterity, c.constitution, c.intelligence, c.wisdom, c.charisma, c.skills, c.class_id, c.species_id, c.background_id, c.subclass_id, c.feats, c.spell_slots_used, c.xp, c.pending_levels, c.table_born, c.species_choices, c.forge_key, c.hit_dice_used, u.name AS owner_name, rc_class.data AS class_data
FROM characters c
JOIN users u ON u.id = c.owner_user_id
LEFT JOIN rules_content rc_class ON rc_class.id = c.class_id
WHERE c.campaign_id = $1
ORDER BY c.created_at ASC
`

type ListCharactersByCampaignRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     pgtype.UUID        `json:"campaign_id"`
	OwnerUserID    uuid.UUID          `json:"owner_user_id"`
	Name           string             `json:"name"`
	Class          string             `json:"class"`
	Level          int32              `json:"level"`
	HpCurrent      int32              `json:"hp_current"`
	HpMax          int32              `json:"hp_max"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Strength       *int16             `json:"strength"`
	Dexterity      *int16             `json:"dexterity"`
	Constitution   *int16             `json:"constitution"`
	Intelligence   *int16             `json:"intelligence"`
	Wisdom         *int16             `json:"wisdom"`
	Charisma       *int16             `json:"charisma"`
	Skills         []string           `json:"skills"`
	ClassID        pgtype.UUID        `json:"class_id"`
	SpeciesID      pgtype.UUID        `json:"species_id"`
	BackgroundID   pgtype.UUID        `json:"background_id"`
	SubclassID     pgtype.UUID        `json:"subclass_id"`
	Feats          []string           `json:"feats"`
	SpellSlotsUsed []int16            `json:"spell_slots_used"`
	Xp             int32              `json:"xp"`
	PendingLevels  int16              `json:"pending_levels"`
	TableBorn      bool               `json:"table_born"`
	SpeciesChoices []byte             `json:"species_choices"`
	ForgeKey       pgtype.UUID        `json:"forge_key"`
	HitDiceUsed    int16              `json:"hit_dice_used"`
	OwnerName      string             `json:"owner_name"`
	ClassData      []byte             `json:"class_data"`
}

func (q *Queries) ListCharactersByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]ListCharactersByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listCharactersByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersByCampaignRow
	for rows.Next() {
		var i ListCharactersByCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.OwnerUserID,
			&i.Name,
			&i.Class,
			&i.Level,
			&i.HpCurrent,
			&i.HpMax,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.Skills,
			&i.ClassID,
			&i.SpeciesID,
			&i.BackgroundID,
			&i.SubclassID,
			&i.Feats,
			&i.SpellSlotsUsed,
			&i.Xp,
			&i.PendingLevels,
			&i.TableBorn,
			&i.SpeciesChoices,
			&i.ForgeKey,
			&i.HitDiceUsed,
			&i.OwnerName,
			&i.ClassData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByOwner = `-- name: ListCharactersByOwner :many
SELECT c.id, c.campaign_id, c.owner_user_id, c.name, c.class, c.level, c.hp_current, c.hp_max, c.created_at, c.updated_at, c.strength, c.dexterity, c.constitution, c.intelligence, c.wisdom, c.charisma, c.skills, c.class_id, c.species_id, c.background_id, c.subclass_id, c.feats, c.spell_slots_used, c.xp, c.pending_levels, c.table_born, c.species_choices, c.forge_key, c.hit_dice_used, camp.name AS campaign_name, rc_class.data AS class_data
FROM characters c
LEFT JOIN campaigns camp ON camp.id = c.campaign_id
LEFT JOIN rules_content rc_class ON rc_class.id = c.class_id
WHERE c.owner_user_id = $1 AND NOT c.table_born
ORDER BY c.created_at ASC
`

type ListCharactersByOwnerRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     pgtype.UUID        `json:"campaign_id"`
	OwnerUserID    uuid.UUID          `json:"owner_user_id"`
	Name           string             `json:"name"`
	Class          string             `json:"class"`
	Level          int32              `json:"level"`
	HpCurrent      int32              `json:"hp_current"`
	HpMax          int32              `json:"hp_max"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Strength       *int16             `json:"strength"`
	Dexterity      *int16             `json:"dexterity"`
	Constitution   *int16             `json:"constitution"`
	Intelligence   *int16             `json:"intelligence"`
	Wisdom         *int16             `json:"wisdom"`
	Charisma       *int16             `json:"charisma"`
	Skills         []string           `json:"skills"`
	ClassID        pgtype.UUID        `json:"class_id"`
	SpeciesID      pgtype.UUID        `json:"species_id"`
	BackgroundID   pgtype.UUID        `json:"background_id"`
	SubclassID     pgtype.UUID        `json:"subclass_id"`
	Feats          []string           `json:"feats"`
	SpellSlotsUsed []int16            `json:"spell_slots_used"`
	Xp             int32              `json:"xp"`
	PendingLevels  int16              `json:"pending_levels"`
	TableBorn      bool               `json:"table_born"`
	SpeciesChoices []byte             `json:"species_choices"`
	ForgeKey       pgtype.UUID        `json:"forge_key"`
	HitDiceUsed    int16              `json:"hit_dice_used"`
	CampaignName   *string            `json:"campaign_name"`
	ClassData      []byte             `json:"class_data"`
}

// The user's heroes across all campaigns, including unseated ones.
// Table-born characters belong to their roster, not to My Heroes.
func (q *Queries) ListCharactersByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListCharactersByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listCharactersByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersByOwnerRow
	for rows.Next() {
		var i ListCharactersByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.OwnerUserID,
			&i.Name,
			&i.Class,
			&i.Level,
			&i.HpCurrent,
			&i.HpMax,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Strength,
			&i.Dexterity,
			&i.Constitution,
			&i.Intelligence,
			&i.Wisdom,
			&i.Charisma,
			&i.Skills,
			&i.ClassID,
			&i.SpeciesID,
			&i.BackgroundID,
			&i.SubclassID,
			&i.Feats,
			&i.SpellSlotsUsed,
			&i.Xp,
			&i.PendingLevels,
			&i.TableBorn,
			&i.SpeciesChoices,
			&i.ForgeKey,
			&i.HitDiceUsed,
			&i.CampaignName,
			&i.ClassData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restCharacter = `-- name: RestCharacter :one
UPDATE characters
SET hp_current = $2,
    spell_slots_used = $3,
    hit_dice_used = GREATEST($4::smallint, 0),
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type RestCharacterParams struct {
	ID             uuid.UUID `json:"id"`
	HpCurrent      int32     `json:"hp_current"`
	SpellSlotsUsed []int16   `json:"spell_slots_used"`
	HitDiceUsed    int16     `json:"hit_dice_used"`
}

// One rest, written as one row change (#118). HP, spent slots and spent hit
// dice move together or not at all — a hero left with their slots back but
// their hit points where they were has had half a rest, which is a state the
// rules have no name for.
func (q *Queries) RestCharacter(ctx context.Context, arg RestCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, restCharacter,
		arg.ID,
		arg.HpCurrent,
		arg.SpellSlotsUsed,
		arg.HitDiceUsed,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const revealCharacter = `-- name: RevealCharacter :exec
INSERT INTO character_reveals (campaign_id, character_id)
VALUES ($1, $2)
ON CONFLICT (campaign_id, character_id) DO NOTHING
`

type RevealCharacterParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) RevealCharacter(ctx context.Context, arg RevealCharacterParams) error {
	_, err := q.db.Exec(ctx, revealCharacter, arg.CampaignID, arg.CharacterID)
	return err
}

const revokeMilestone = `-- name: RevokeMilestone :exec
UPDATE characters
SET pending_levels = pending_levels - 1, updated_at = now()
WHERE campaign_id = $1 AND pending_levels > 0
`

// Take back one unspent level-up from everyone at the table.
func (q *Queries) RevokeMilestone(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeMilestone, campaignID)
	return err
}

const revokeMilestoneFrom = `-- name: RevokeMilestoneFrom :exec
UPDATE characters
SET pending_levels = pending_levels - 1, updated_at = now()
WHERE campaign_id = $1
  AND pending_levels > 0
  AND id = ANY($2::uuid[])
`

type RevokeMilestoneFromParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	Ids        []uuid.UUID `json:"ids"`
}

// Take back one unspent level-up from the chosen seated heroes.
func (q *Queries) RevokeMilestoneFrom(ctx context.Context, arg RevokeMilestoneFromParams) error {
	_, err := q.db.Exec(ctx, revokeMilestoneFrom, arg.CampaignID, arg.Ids)
	return err
}

const seatCharacter = `-- name: SeatCharacter :one
UPDATE characters SET campaign_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type SeatCharacterParams struct {
	ID         uuid.UUID   `json:"id"`
	CampaignID pgtype.UUID `json:"campaign_id"`
}

// Seat a hero at a campaign (or NULL to return them to My Heroes).
func (q *Queries) SeatCharacter(ctx context.Context, arg SeatCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, seatCharacter, arg.ID, arg.CampaignID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const setSpellSlotsUsed = `-- name: SetSpellSlotsUsed :one
UPDATE characters
SET spell_slots_used = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type SetSpellSlotsUsedParams struct {
	ID             uuid.UUID `json:"id"`
	SpellSlotsUsed []int16   `json:"spell_slots_used"`
}

func (q *Queries) SetSpellSlotsUsed(ctx context.Context, arg SetSpellSlotsUsedParams) (Character, error) {
	row := q.db.QueryRow(ctx, setSpellSlotsUsed, arg.ID, arg.SpellSlotsUsed)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}

const spendPendingLevel = `-- name: SpendPendingLevel :exec
UPDATE characters
SET pending_levels = pending_levels - 1, updated_at = now()
WHERE id = $1 AND pending_levels > 0
`

func (q *Queries) SpendPendingLevel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, spendPendingLevel, id)
	return err
}

const unseatCharactersOfCampaign = `-- name: UnseatCharactersOfCampaign :exec
UPDATE characters SET campaign_id = NULL, updated_at = now()
WHERE campaign_id = $1
`

// A struck campaign's remaining heroes return to their owners' My Heroes shelf.
func (q *Queries) UnseatCharactersOfCampaign(ctx context.Context, campaignID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unseatCharactersOfCampaign, campaignID)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET name       = $2,
    class      = $3,
    level      = $4,
    hp_current = $5,
    hp_max     = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, hit_dice_used
`

type UpdateCharacterParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Class     string    `json:"class"`
	Level     int32     `json:"level"`
	HpCurrent int32     `json:"hp_current"`
	HpMax     int32     `json:"hp_max"`
}

func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.ID,
		arg.Name,
		arg.Class,
		arg.Level,
		arg.HpCurrent,
		arg.HpMax,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.HitDiceUsed,
	)
	return i, err
}
