// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: codex.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCodexEntry = `-- name: DeleteCodexEntry :exec
DELETE FROM campaign_content WHERE campaign_id = $1 AND content_id = $2
`

type DeleteCodexEntryParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	ContentID  uuid.UUID `json:"content_id"`
}

// Back to the default: SRD legal, homebrew invisible.
func (q *Queries) DeleteCodexEntry(ctx context.Context, arg DeleteCodexEntryParams) error {
	_, err := q.db.Exec(ctx, deleteCodexEntry, arg.CampaignID, arg.ContentID)
	return err
}

const getCodexStatuses = `-- name: GetCodexStatuses :many
SELECT content_id, status FROM campaign_content
WHERE campaign_id = $1 AND content_id = ANY($2::uuid[])
`

type GetCodexStatusesParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	Column2    []uuid.UUID `json:"column_2"`
}

type GetCodexStatusesRow struct {
	ContentID uuid.UUID   `json:"content_id"`
	Status    CodexStatus `json:"status"`
}

// Statuses for a set of entries in one campaign (seat/level-up legality).
func (q *Queries) GetCodexStatuses(ctx context.Context, arg GetCodexStatusesParams) ([]GetCodexStatusesRow, error) {
	rows, err := q.db.Query(ctx, getCodexStatuses, arg.CampaignID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCodexStatusesRow
	for rows.Next() {
		var i GetCodexStatusesRow
		if err := rows.Scan(&i.ContentID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodex = `-- name: ListCodex :many
SELECT cc.content_id, cc.status, cc.created_at,
       rc.kind, rc.source, rc.name, rc.summary, rc.data, rc.created_by,
       u.name AS proposer_name
FROM campaign_content cc
JOIN rules_content rc ON rc.id = cc.content_id
LEFT JOIN users u ON u.id = cc.proposed_by
WHERE cc.campaign_id = $1
ORDER BY rc.kind, rc.name
`

type ListCodexRow struct {
	ContentID    uuid.UUID          `json:"content_id"`
	Status       CodexStatus        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Kind         ContentKind        `json:"kind"`
	Source       ContentSource      `json:"source"`
	Name         string             `json:"name"`
	Summary      string             `json:"summary"`
	Data         []byte             `json:"data"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	ProposerName *string            `json:"proposer_name"`
}

// Every codex row for a campaign, with its content and proposer.
func (q *Queries) ListCodex(ctx context.Context, campaignID uuid.UUID) ([]ListCodexRow, error) {
	rows, err := q.db.Query(ctx, listCodex, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCodexRow
	for rows.Next() {
		var i ListCodexRow
		if err := rows.Scan(
			&i.ContentID,
			&i.Status,
			&i.CreatedAt,
			&i.Kind,
			&i.Source,
			&i.Name,
			&i.Summary,
			&i.Data,
			&i.CreatedBy,
			&i.ProposerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proposeCodexContent = `-- name: ProposeCodexContent :exec
INSERT INTO campaign_content (campaign_id, content_id, status, proposed_by)
VALUES ($1, $2, 'proposed', $3)
ON CONFLICT (campaign_id, content_id) DO NOTHING
`

type ProposeCodexContentParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	ContentID  uuid.UUID   `json:"content_id"`
	ProposedBy pgtype.UUID `json:"proposed_by"`
}

// A member offers their homebrew to the table; never downgrades a DM verdict.
func (q *Queries) ProposeCodexContent(ctx context.Context, arg ProposeCodexContentParams) error {
	_, err := q.db.Exec(ctx, proposeCodexContent, arg.CampaignID, arg.ContentID, arg.ProposedBy)
	return err
}

const setCodexStatus = `-- name: SetCodexStatus :exec
INSERT INTO campaign_content (campaign_id, content_id, status, proposed_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, content_id)
DO UPDATE SET status = EXCLUDED.status
`

type SetCodexStatusParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	ContentID  uuid.UUID   `json:"content_id"`
	Status     CodexStatus `json:"status"`
	ProposedBy pgtype.UUID `json:"proposed_by"`
}

// DM verdicts: enable homebrew, ban/unban SRD, approve proposals.
func (q *Queries) SetCodexStatus(ctx context.Context, arg SetCodexStatusParams) error {
	_, err := q.db.Exec(ctx, setCodexStatus,
		arg.CampaignID,
		arg.ContentID,
		arg.Status,
		arg.ProposedBy,
	)
	return err
}

const setCodexStatusBulk = `-- name: SetCodexStatusBulk :exec
INSERT INTO campaign_content (campaign_id, content_id, status, proposed_by)
SELECT $1, unnest($2::uuid[]), $3, $4
ON CONFLICT (campaign_id, content_id)
DO UPDATE SET status = EXCLUDED.status
`

type SetCodexStatusBulkParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	Column2    []uuid.UUID `json:"column_2"`
	Status     CodexStatus `json:"status"`
	ProposedBy pgtype.UUID `json:"proposed_by"`
}

// One DM verdict over many entries at once (pack admissions).
func (q *Queries) SetCodexStatusBulk(ctx context.Context, arg SetCodexStatusBulkParams) error {
	_, err := q.db.Exec(ctx, setCodexStatusBulk,
		arg.CampaignID,
		arg.Column2,
		arg.Status,
		arg.ProposedBy,
	)
	return err
}
