// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: encounters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCombatant = `-- name: AddCombatant :one
INSERT INTO encounter_combatants (
    encounter_id, kind, content_id, character_id, label, player_label,
    init_mod, hp_current, hp_max, ac, hidden, sort_order, group_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, encounter_id, kind, content_id, character_id, label, player_label, init_mod, initiative, hp_current, hp_max, ac, hidden, sort_order, created_at, group_id
`

type AddCombatantParams struct {
	EncounterID uuid.UUID   `json:"encounter_id"`
	Kind        string      `json:"kind"`
	ContentID   pgtype.UUID `json:"content_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	Label       string      `json:"label"`
	PlayerLabel string      `json:"player_label"`
	InitMod     int32       `json:"init_mod"`
	HpCurrent   int32       `json:"hp_current"`
	HpMax       int32       `json:"hp_max"`
	Ac          int32       `json:"ac"`
	Hidden      bool        `json:"hidden"`
	SortOrder   int32       `json:"sort_order"`
	GroupID     pgtype.UUID `json:"group_id"`
}

func (q *Queries) AddCombatant(ctx context.Context, arg AddCombatantParams) (EncounterCombatant, error) {
	row := q.db.QueryRow(ctx, addCombatant,
		arg.EncounterID,
		arg.Kind,
		arg.ContentID,
		arg.CharacterID,
		arg.Label,
		arg.PlayerLabel,
		arg.InitMod,
		arg.HpCurrent,
		arg.HpMax,
		arg.Ac,
		arg.Hidden,
		arg.SortOrder,
		arg.GroupID,
	)
	var i EncounterCombatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Kind,
		&i.ContentID,
		&i.CharacterID,
		&i.Label,
		&i.PlayerLabel,
		&i.InitMod,
		&i.Initiative,
		&i.HpCurrent,
		&i.HpMax,
		&i.Ac,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const clearEncounterInitiative = `-- name: ClearEncounterInitiative :exec
UPDATE encounter_combatants SET initiative = NULL WHERE encounter_id = $1
`

// Initiative belongs to a running fight and nothing else. It must not survive
// into the builder, where a stale order would look like a rolled one.
func (q *Queries) ClearEncounterInitiative(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearEncounterInitiative, encounterID)
	return err
}

const clearEncounterParty = `-- name: ClearEncounterParty :exec
DELETE FROM encounter_combatants WHERE encounter_id = $1 AND kind = 'pc'
`

// Standing down releases the heroes. Monsters stay, so the encounter is still a
// prepared fight the DM can trigger again; the party is summoned fresh each run.
func (q *Queries) ClearEncounterParty(ctx context.Context, encounterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearEncounterParty, encounterID)
	return err
}

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO encounters (campaign_id, name, tag, location_id)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

type CreateEncounterParams struct {
	CampaignID uuid.UUID   `json:"campaign_id"`
	Name       string      `json:"name"`
	Tag        string      `json:"tag"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, createEncounter,
		arg.CampaignID,
		arg.Name,
		arg.Tag,
		arg.LocationID,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const deleteCombatant = `-- name: DeleteCombatant :execrows
DELETE FROM encounter_combatants WHERE id = $1
`

func (q *Queries) DeleteCombatant(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCombatant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCombatantGroup = `-- name: DeleteCombatantGroup :execrows
DELETE FROM encounter_combatants WHERE encounter_id = $1 AND group_id = $2
`

type DeleteCombatantGroupParams struct {
	EncounterID uuid.UUID   `json:"encounter_id"`
	GroupID     pgtype.UUID `json:"group_id"`
}

// Remove a whole mob at once.
func (q *Queries) DeleteCombatantGroup(ctx context.Context, arg DeleteCombatantGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCombatantGroup, arg.EncounterID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEncounter = `-- name: DeleteEncounter :execrows
DELETE FROM encounters WHERE id = $1
`

func (q *Queries) DeleteEncounter(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEncounter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileEncounter = `-- name: FileEncounter :one
UPDATE encounters SET tag = $2, location_id = $3 WHERE id = $1 RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

type FileEncounterParams struct {
	ID         uuid.UUID   `json:"id"`
	Tag        string      `json:"tag"`
	LocationID pgtype.UUID `json:"location_id"`
}

// Where an encounter belongs: a session tag, a place, both, or neither. Full
// replacement — the caller sends the filing it wants, not a patch of it.
func (q *Queries) FileEncounter(ctx context.Context, arg FileEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, fileEncounter, arg.ID, arg.Tag, arg.LocationID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const getActiveEncounterForUser = `-- name: GetActiveEncounterForUser :one
SELECT DISTINCT ON (e.id) e.id, e.campaign_id, e.name, e.status, e.round, e.turn_index, e.created_at, e.tag, e.location_id
FROM encounters e
JOIN encounter_combatants c ON c.encounter_id = e.id
JOIN characters ch ON ch.id = c.character_id
WHERE e.campaign_id = $1 AND e.status = 'active' AND ch.owner_user_id = $2
ORDER BY e.id, e.created_at DESC
LIMIT 1
`

type GetActiveEncounterForUserParams struct {
	CampaignID  uuid.UUID `json:"campaign_id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// The running fight this player's hero is standing in. A player only ever
// watches their own battle — the other half of a split party is not their
// business — so the join runs through their own characters.
func (q *Queries) GetActiveEncounterForUser(ctx context.Context, arg GetActiveEncounterForUserParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, getActiveEncounterForUser, arg.CampaignID, arg.OwnerUserID)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const getCombatant = `-- name: GetCombatant :one
SELECT c.id, c.encounter_id, c.kind, c.content_id, c.character_id, c.label, c.player_label, c.init_mod, c.initiative, c.hp_current, c.hp_max, c.ac, c.hidden, c.sort_order, c.created_at, c.group_id, e.campaign_id, e.status AS encounter_status
FROM encounter_combatants c
JOIN encounters e ON e.id = c.encounter_id
WHERE c.id = $1
`

type GetCombatantRow struct {
	ID              uuid.UUID          `json:"id"`
	EncounterID     uuid.UUID          `json:"encounter_id"`
	Kind            string             `json:"kind"`
	ContentID       pgtype.UUID        `json:"content_id"`
	CharacterID     pgtype.UUID        `json:"character_id"`
	Label           string             `json:"label"`
	PlayerLabel     string             `json:"player_label"`
	InitMod         int32              `json:"init_mod"`
	Initiative      *int32             `json:"initiative"`
	HpCurrent       int32              `json:"hp_current"`
	HpMax           int32              `json:"hp_max"`
	Ac              int32              `json:"ac"`
	Hidden          bool               `json:"hidden"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	CampaignID      uuid.UUID          `json:"campaign_id"`
	EncounterStatus string             `json:"encounter_status"`
}

// A combatant with its encounter's campaign, so handlers gate in one read.
func (q *Queries) GetCombatant(ctx context.Context, id uuid.UUID) (GetCombatantRow, error) {
	row := q.db.QueryRow(ctx, getCombatant, id)
	var i GetCombatantRow
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Kind,
		&i.ContentID,
		&i.CharacterID,
		&i.Label,
		&i.PlayerLabel,
		&i.InitMod,
		&i.Initiative,
		&i.HpCurrent,
		&i.HpMax,
		&i.Ac,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedAt,
		&i.GroupID,
		&i.CampaignID,
		&i.EncounterStatus,
	)
	return i, err
}

const getEncounter = `-- name: GetEncounter :one
SELECT id, campaign_id, name, status, round, turn_index, created_at, tag, location_id FROM encounters WHERE id = $1
`

func (q *Queries) GetEncounter(ctx context.Context, id uuid.UUID) (Encounter, error) {
	row := q.db.QueryRow(ctx, getEncounter, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const listActiveCombatantsForCharacter = `-- name: ListActiveCombatantsForCharacter :many
SELECT c.id, c.encounter_id, c.kind, c.content_id, c.character_id, c.label, c.player_label, c.init_mod, c.initiative, c.hp_current, c.hp_max, c.ac, c.hidden, c.sort_order, c.created_at, c.group_id FROM encounter_combatants c
JOIN encounters e ON e.id = c.encounter_id
WHERE c.character_id = $1 AND e.status = 'active'
`

// Every live combatant row for one hero. Used to mirror HP into whichever fight
// they're in, and to refuse seating them in a second one.
func (q *Queries) ListActiveCombatantsForCharacter(ctx context.Context, characterID pgtype.UUID) ([]EncounterCombatant, error) {
	rows, err := q.db.Query(ctx, listActiveCombatantsForCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncounterCombatant
	for rows.Next() {
		var i EncounterCombatant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Kind,
			&i.ContentID,
			&i.CharacterID,
			&i.Label,
			&i.PlayerLabel,
			&i.InitMod,
			&i.Initiative,
			&i.HpCurrent,
			&i.HpMax,
			&i.Ac,
			&i.Hidden,
			&i.SortOrder,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveEncounters = `-- name: ListActiveEncounters :many
SELECT id, campaign_id, name, status, round, turn_index, created_at, tag, location_id FROM encounters
WHERE campaign_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

// Every fight currently running in a campaign. More than one is normal: a party
// that splits is two encounters at once.
func (q *Queries) ListActiveEncounters(ctx context.Context, campaignID uuid.UUID) ([]Encounter, error) {
	rows, err := q.db.Query(ctx, listActiveEncounters, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Status,
			&i.Round,
			&i.TurnIndex,
			&i.CreatedAt,
			&i.Tag,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCombatants = `-- name: ListCombatants :many
SELECT id, encounter_id, kind, content_id, character_id, label, player_label, init_mod, initiative, hp_current, hp_max, ac, hidden, sort_order, created_at, group_id FROM encounter_combatants
WHERE encounter_id = $1
ORDER BY (initiative IS NULL), initiative DESC, init_mod DESC,
         COALESCE(group_id, id), sort_order, created_at
`

// Initiative order: highest initiative first, unrolled (NULL) last, then by
// init modifier and add order to break ties. Members of a group always land
// side by side (they share an initiative and a group_id, and coalescing to the
// row's own id keeps loners sorting exactly as they did before) — the tracker
// collapses each run of them into a single entry, so they must never interleave
// with another combatant that happened to roll the same number.
func (q *Queries) ListCombatants(ctx context.Context, encounterID uuid.UUID) ([]EncounterCombatant, error) {
	rows, err := q.db.Query(ctx, listCombatants, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncounterCombatant
	for rows.Next() {
		var i EncounterCombatant
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Kind,
			&i.ContentID,
			&i.CharacterID,
			&i.Label,
			&i.PlayerLabel,
			&i.InitMod,
			&i.Initiative,
			&i.HpCurrent,
			&i.HpMax,
			&i.Ac,
			&i.Hidden,
			&i.SortOrder,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncounters = `-- name: ListEncounters :many
SELECT e.id, e.campaign_id, e.name, e.status, e.round, e.turn_index, e.created_at, e.tag, e.location_id, count(c.id) AS combatant_count, l.name AS location_name
FROM encounters e
LEFT JOIN encounter_combatants c ON c.encounter_id = e.id
LEFT JOIN locations l ON l.id = e.location_id
WHERE e.campaign_id = $1
GROUP BY e.id, l.name
ORDER BY e.created_at DESC
`

type ListEncountersRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Name           string             `json:"name"`
	Status         string             `json:"status"`
	Round          int32              `json:"round"`
	TurnIndex      int32              `json:"turn_index"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Tag            string             `json:"tag"`
	LocationID     pgtype.UUID        `json:"location_id"`
	CombatantCount int64              `json:"combatant_count"`
	LocationName   *string            `json:"location_name"`
}

// The DM's library: every encounter of a campaign, newest first, each with its
// combatant count and the name of the place it is filed under.
func (q *Queries) ListEncounters(ctx context.Context, campaignID uuid.UUID) ([]ListEncountersRow, error) {
	rows, err := q.db.Query(ctx, listEncounters, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersRow
	for rows.Next() {
		var i ListEncountersRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Status,
			&i.Round,
			&i.TurnIndex,
			&i.CreatedAt,
			&i.Tag,
			&i.LocationID,
			&i.CombatantCount,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameEncounter = `-- name: RenameEncounter :one
UPDATE encounters SET name = $2 WHERE id = $1 RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

type RenameEncounterParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameEncounter(ctx context.Context, arg RenameEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, renameEncounter, arg.ID, arg.Name)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const setCombatantInitiative = `-- name: SetCombatantInitiative :one
UPDATE encounter_combatants SET initiative = $2 WHERE id = $1 RETURNING id, encounter_id, kind, content_id, character_id, label, player_label, init_mod, initiative, hp_current, hp_max, ac, hidden, sort_order, created_at, group_id
`

type SetCombatantInitiativeParams struct {
	ID         uuid.UUID `json:"id"`
	Initiative *int32    `json:"initiative"`
}

func (q *Queries) SetCombatantInitiative(ctx context.Context, arg SetCombatantInitiativeParams) (EncounterCombatant, error) {
	row := q.db.QueryRow(ctx, setCombatantInitiative, arg.ID, arg.Initiative)
	var i EncounterCombatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Kind,
		&i.ContentID,
		&i.CharacterID,
		&i.Label,
		&i.PlayerLabel,
		&i.InitMod,
		&i.Initiative,
		&i.HpCurrent,
		&i.HpMax,
		&i.Ac,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const setEncounterStatus = `-- name: SetEncounterStatus :one
UPDATE encounters SET status = $2 WHERE id = $1 RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

type SetEncounterStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetEncounterStatus(ctx context.Context, arg SetEncounterStatusParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, setEncounterStatus, arg.ID, arg.Status)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}

const setGroupInitiative = `-- name: SetGroupInitiative :exec
UPDATE encounter_combatants SET initiative = $2
WHERE encounter_id = $1 AND group_id = $3
`

type SetGroupInitiativeParams struct {
	EncounterID uuid.UUID   `json:"encounter_id"`
	Initiative  *int32      `json:"initiative"`
	GroupID     pgtype.UUID `json:"group_id"`
}

// A group acts as one creature, so its members share a single roll.
func (q *Queries) SetGroupInitiative(ctx context.Context, arg SetGroupInitiativeParams) error {
	_, err := q.db.Exec(ctx, setGroupInitiative, arg.EncounterID, arg.Initiative, arg.GroupID)
	return err
}

const standDownEncounters = `-- name: StandDownEncounters :many
UPDATE encounters SET status = 'inactive', round = 1, turn_index = 0
WHERE campaign_id = $1 AND status = 'active'
RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

// Send every running fight in a campaign back to inactive at once. The DM's
// panic button: with several fights open, hunting down which one still holds a
// player is exactly the chore this avoids.
func (q *Queries) StandDownEncounters(ctx context.Context, campaignID uuid.UUID) ([]Encounter, error) {
	rows, err := q.db.Query(ctx, standDownEncounters, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Status,
			&i.Round,
			&i.TurnIndex,
			&i.CreatedAt,
			&i.Tag,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCombatant = `-- name: UpdateCombatant :one
UPDATE encounter_combatants
SET label = $2, player_label = $3, initiative = $4, hp_current = $5,
    hp_max = $6, ac = $7, hidden = $8
WHERE id = $1
RETURNING id, encounter_id, kind, content_id, character_id, label, player_label, init_mod, initiative, hp_current, hp_max, ac, hidden, sort_order, created_at, group_id
`

type UpdateCombatantParams struct {
	ID          uuid.UUID `json:"id"`
	Label       string    `json:"label"`
	PlayerLabel string    `json:"player_label"`
	Initiative  *int32    `json:"initiative"`
	HpCurrent   int32     `json:"hp_current"`
	HpMax       int32     `json:"hp_max"`
	Ac          int32     `json:"ac"`
	Hidden      bool      `json:"hidden"`
}

func (q *Queries) UpdateCombatant(ctx context.Context, arg UpdateCombatantParams) (EncounterCombatant, error) {
	row := q.db.QueryRow(ctx, updateCombatant,
		arg.ID,
		arg.Label,
		arg.PlayerLabel,
		arg.Initiative,
		arg.HpCurrent,
		arg.HpMax,
		arg.Ac,
		arg.Hidden,
	)
	var i EncounterCombatant
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Kind,
		&i.ContentID,
		&i.CharacterID,
		&i.Label,
		&i.PlayerLabel,
		&i.InitMod,
		&i.Initiative,
		&i.HpCurrent,
		&i.HpMax,
		&i.Ac,
		&i.Hidden,
		&i.SortOrder,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const updateEncounterProgress = `-- name: UpdateEncounterProgress :one
UPDATE encounters SET round = $2, turn_index = $3 WHERE id = $1 RETURNING id, campaign_id, name, status, round, turn_index, created_at, tag, location_id
`

type UpdateEncounterProgressParams struct {
	ID        uuid.UUID `json:"id"`
	Round     int32     `json:"round"`
	TurnIndex int32     `json:"turn_index"`
}

func (q *Queries) UpdateEncounterProgress(ctx context.Context, arg UpdateEncounterProgressParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, updateEncounterProgress, arg.ID, arg.Round, arg.TurnIndex)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Status,
		&i.Round,
		&i.TurnIndex,
		&i.CreatedAt,
		&i.Tag,
		&i.LocationID,
	)
	return i, err
}
