// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handouts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addHandoutEvent = `-- name: AddHandoutEvent :one
INSERT INTO campaign_events (campaign_id, actor_user_id, kind, message, handout_id)
VALUES ($1, $2, 'handout', $3, $4)
RETURNING id, campaign_id, actor_user_id, kind, message, created_at, handout_id
`

type AddHandoutEventParams struct {
	CampaignID  uuid.UUID   `json:"campaign_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Message     string      `json:"message"`
	HandoutID   pgtype.UUID `json:"handout_id"`
}

// The chronicle line for a handout being handed over. Its own query rather
// than a fifth argument on AddEvent, which every other logged moment calls.
func (q *Queries) AddHandoutEvent(ctx context.Context, arg AddHandoutEventParams) (CampaignEvent, error) {
	row := q.db.QueryRow(ctx, addHandoutEvent,
		arg.CampaignID,
		arg.ActorUserID,
		arg.Message,
		arg.HandoutID,
	)
	var i CampaignEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ActorUserID,
		&i.Kind,
		&i.Message,
		&i.CreatedAt,
		&i.HandoutID,
	)
	return i, err
}

const clearHandoutOverrides = `-- name: ClearHandoutOverrides :exec
DELETE FROM handout_visibility WHERE handout_id = $1
`

func (q *Queries) ClearHandoutOverrides(ctx context.Context, handoutID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearHandoutOverrides, handoutID)
	return err
}

const createHandout = `-- name: CreateHandout :one

INSERT INTO handouts (campaign_id, title, caption, image, content_type, width, height, visible_to_party)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, campaign_id, title, caption, content_type, width, height, visible_to_party, created_at
`

type CreateHandoutParams struct {
	CampaignID     uuid.UUID `json:"campaign_id"`
	Title          string    `json:"title"`
	Caption        string    `json:"caption"`
	Image          []byte    `json:"image"`
	ContentType    string    `json:"content_type"`
	Width          int32     `json:"width"`
	Height         int32     `json:"height"`
	VisibleToParty bool      `json:"visible_to_party"`
}

type CreateHandoutRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Title          string             `json:"title"`
	Caption        string             `json:"caption"`
	ContentType    string             `json:"content_type"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	VisibleToParty bool               `json:"visible_to_party"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Handouts. Every read here deliberately omits `image`: the bytes go out over
// the raw /api/handouts/{id}/image route, never inside a JSON payload, so a
// listing stays small however many letters the campaign has accumulated.
func (q *Queries) CreateHandout(ctx context.Context, arg CreateHandoutParams) (CreateHandoutRow, error) {
	row := q.db.QueryRow(ctx, createHandout,
		arg.CampaignID,
		arg.Title,
		arg.Caption,
		arg.Image,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.VisibleToParty,
	)
	var i CreateHandoutRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Caption,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.VisibleToParty,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHandout = `-- name: DeleteHandout :execrows
DELETE FROM handouts WHERE id = $1
`

func (q *Queries) DeleteHandout(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHandout, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHandoutOverride = `-- name: DeleteHandoutOverride :exec
DELETE FROM handout_visibility WHERE handout_id = $1 AND character_id = $2
`

type DeleteHandoutOverrideParams struct {
	HandoutID   uuid.UUID `json:"handout_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteHandoutOverride(ctx context.Context, arg DeleteHandoutOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteHandoutOverride, arg.HandoutID, arg.CharacterID)
	return err
}

const getHandoutEvent = `-- name: GetHandoutEvent :one
SELECT id FROM campaign_events WHERE handout_id = $1 LIMIT 1
`

// Does this handout already have its line? Handing it to one more hero later
// must not write a second one.
func (q *Queries) GetHandoutEvent(ctx context.Context, handoutID pgtype.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getHandoutEvent, handoutID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getHandoutImage = `-- name: GetHandoutImage :one
SELECT image, content_type, created_at
FROM handouts
WHERE id = $1
`

type GetHandoutImageRow struct {
	Image       []byte             `json:"image"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetHandoutImage(ctx context.Context, id uuid.UUID) (GetHandoutImageRow, error) {
	row := q.db.QueryRow(ctx, getHandoutImage, id)
	var i GetHandoutImageRow
	err := row.Scan(&i.Image, &i.ContentType, &i.CreatedAt)
	return i, err
}

const getHandoutMeta = `-- name: GetHandoutMeta :one
SELECT id, campaign_id, title, caption, content_type, width, height, visible_to_party, created_at
FROM handouts
WHERE id = $1
`

type GetHandoutMetaRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Title          string             `json:"title"`
	Caption        string             `json:"caption"`
	ContentType    string             `json:"content_type"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	VisibleToParty bool               `json:"visible_to_party"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetHandoutMeta(ctx context.Context, id uuid.UUID) (GetHandoutMetaRow, error) {
	row := q.db.QueryRow(ctx, getHandoutMeta, id)
	var i GetHandoutMetaRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Caption,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.VisibleToParty,
		&i.CreatedAt,
	)
	return i, err
}

const listHandoutVisibility = `-- name: ListHandoutVisibility :many
SELECT v.handout_id, v.character_id, v.visible, c.name AS character_name
FROM handout_visibility v
JOIN characters c ON c.id = v.character_id
WHERE v.handout_id = $1
`

type ListHandoutVisibilityRow struct {
	HandoutID     uuid.UUID `json:"handout_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListHandoutVisibility(ctx context.Context, handoutID uuid.UUID) ([]ListHandoutVisibilityRow, error) {
	rows, err := q.db.Query(ctx, listHandoutVisibility, handoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoutVisibilityRow
	for rows.Next() {
		var i ListHandoutVisibilityRow
		if err := rows.Scan(
			&i.HandoutID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandoutVisibilityByCampaign = `-- name: ListHandoutVisibilityByCampaign :many
SELECT v.handout_id, v.character_id, v.visible, c.name AS character_name
FROM handout_visibility v
JOIN handouts h ON h.id = v.handout_id
JOIN characters c ON c.id = v.character_id
WHERE h.campaign_id = $1
`

type ListHandoutVisibilityByCampaignRow struct {
	HandoutID     uuid.UUID `json:"handout_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListHandoutVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListHandoutVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listHandoutVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoutVisibilityByCampaignRow
	for rows.Next() {
		var i ListHandoutVisibilityByCampaignRow
		if err := rows.Scan(
			&i.HandoutID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandoutsByCampaign = `-- name: ListHandoutsByCampaign :many
SELECT id, campaign_id, title, caption, content_type, width, height, visible_to_party, created_at
FROM handouts
WHERE campaign_id = $1
ORDER BY created_at DESC
`

type ListHandoutsByCampaignRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Title          string             `json:"title"`
	Caption        string             `json:"caption"`
	ContentType    string             `json:"content_type"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	VisibleToParty bool               `json:"visible_to_party"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// The satchel, newest first — the order the table met them in, reversed.
func (q *Queries) ListHandoutsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListHandoutsByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listHandoutsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHandoutsByCampaignRow
	for rows.Next() {
		var i ListHandoutsByCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Title,
			&i.Caption,
			&i.ContentType,
			&i.Width,
			&i.Height,
			&i.VisibleToParty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHandoutOverride = `-- name: SetHandoutOverride :exec

INSERT INTO handout_visibility (handout_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (handout_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetHandoutOverrideParams struct {
	HandoutID   uuid.UUID `json:"handout_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

// Per-hero exceptions. Setting the party-wide flag clears these, so a
// party-wide reveal or hide always wins over stale per-hero rows.
func (q *Queries) SetHandoutOverride(ctx context.Context, arg SetHandoutOverrideParams) error {
	_, err := q.db.Exec(ctx, setHandoutOverride, arg.HandoutID, arg.CharacterID, arg.Visible)
	return err
}

const setHandoutPartyVisibility = `-- name: SetHandoutPartyVisibility :one
UPDATE handouts
SET visible_to_party = $2
WHERE id = $1
RETURNING id, campaign_id, title, caption, content_type, width, height, visible_to_party, created_at
`

type SetHandoutPartyVisibilityParams struct {
	ID             uuid.UUID `json:"id"`
	VisibleToParty bool      `json:"visible_to_party"`
}

type SetHandoutPartyVisibilityRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Title          string             `json:"title"`
	Caption        string             `json:"caption"`
	ContentType    string             `json:"content_type"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	VisibleToParty bool               `json:"visible_to_party"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SetHandoutPartyVisibility(ctx context.Context, arg SetHandoutPartyVisibilityParams) (SetHandoutPartyVisibilityRow, error) {
	row := q.db.QueryRow(ctx, setHandoutPartyVisibility, arg.ID, arg.VisibleToParty)
	var i SetHandoutPartyVisibilityRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Caption,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.VisibleToParty,
		&i.CreatedAt,
	)
	return i, err
}

const updateHandout = `-- name: UpdateHandout :one
UPDATE handouts
SET title = $2, caption = $3
WHERE id = $1
RETURNING id, campaign_id, title, caption, content_type, width, height, visible_to_party, created_at
`

type UpdateHandoutParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Caption string    `json:"caption"`
}

type UpdateHandoutRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	Title          string             `json:"title"`
	Caption        string             `json:"caption"`
	ContentType    string             `json:"content_type"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	VisibleToParty bool               `json:"visible_to_party"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateHandout(ctx context.Context, arg UpdateHandoutParams) (UpdateHandoutRow, error) {
	row := q.db.QueryRow(ctx, updateHandout, arg.ID, arg.Title, arg.Caption)
	var i UpdateHandoutRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Caption,
		&i.ContentType,
		&i.Width,
		&i.Height,
		&i.VisibleToParty,
		&i.CreatedAt,
	)
	return i, err
}
