// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearLocationOverrides = `-- name: ClearLocationOverrides :exec
DELETE FROM location_visibility WHERE location_id = $1
`

func (q *Queries) ClearLocationOverrides(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLocationOverrides, locationID)
	return err
}

const countQuestsInLocation = `-- name: CountQuestsInLocation :one
SELECT count(*) FROM quests WHERE location_id = $1
`

func (q *Queries) CountQuestsInLocation(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestsInLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (campaign_id, parent_id, name, description, visible_to_party)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, parent_id, name, description, visible_to_party, created_at, updated_at
`

type CreateLocationParams struct {
	CampaignID     uuid.UUID   `json:"campaign_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	VisibleToParty bool        `json:"visible_to_party"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.CampaignID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.VisibleToParty,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.VisibleToParty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deleteLocationOverride = `-- name: DeleteLocationOverride :exec
DELETE FROM location_visibility WHERE location_id = $1 AND character_id = $2
`

type DeleteLocationOverrideParams struct {
	LocationID  uuid.UUID `json:"location_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteLocationOverride(ctx context.Context, arg DeleteLocationOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteLocationOverride, arg.LocationID, arg.CharacterID)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, campaign_id, parent_id, name, description, visible_to_party, created_at, updated_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.VisibleToParty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocationVisibilityByCampaign = `-- name: ListLocationVisibilityByCampaign :many
SELECT v.location_id, v.character_id, v.visible, c.name AS character_name
FROM location_visibility v
JOIN locations l ON l.id = v.location_id
JOIN characters c ON c.id = v.character_id
WHERE l.campaign_id = $1
`

type ListLocationVisibilityByCampaignRow struct {
	LocationID    uuid.UUID `json:"location_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListLocationVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListLocationVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listLocationVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationVisibilityByCampaignRow
	for rows.Next() {
		var i ListLocationVisibilityByCampaignRow
		if err := rows.Scan(
			&i.LocationID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByCampaign = `-- name: ListLocationsByCampaign :many
SELECT id, campaign_id, parent_id, name, description, visible_to_party, created_at, updated_at FROM locations WHERE campaign_id = $1 ORDER BY name
`

func (q *Queries) ListLocationsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.VisibleToParty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rememberLocationNamesBeforeDelete = `-- name: RememberLocationNamesBeforeDelete :exec
WITH RECURSIVE subtree(loc_id, loc_name) AS (
    SELECT root.id, root.name FROM locations root WHERE root.id = $1
    UNION ALL
    SELECT child.id, child.name
    FROM locations child
    JOIN subtree ON child.parent_id = subtree.loc_id
)
UPDATE quests q
SET location = subtree.loc_name
FROM subtree
WHERE q.location_id = subtree.loc_id
`

// Erasing a place cascades to the places nested inside it and unpins every
// notice hanging in any of them. Stamp the current names onto those notices
// first, so a notice still remembers where it hung — by the right name.
func (q *Queries) RememberLocationNamesBeforeDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, rememberLocationNamesBeforeDelete, id)
	return err
}

const setLocationOverride = `-- name: SetLocationOverride :exec

INSERT INTO location_visibility (location_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (location_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetLocationOverrideParams struct {
	LocationID  uuid.UUID `json:"location_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

// Per-hero exceptions. Setting the party-wide flag clears these, so a
// party-wide reveal or hide always wins over stale per-hero rows.
func (q *Queries) SetLocationOverride(ctx context.Context, arg SetLocationOverrideParams) error {
	_, err := q.db.Exec(ctx, setLocationOverride, arg.LocationID, arg.CharacterID, arg.Visible)
	return err
}

const setLocationPartyVisibility = `-- name: SetLocationPartyVisibility :one
UPDATE locations
SET visible_to_party = $2,
    updated_at       = now()
WHERE id = $1
RETURNING id, campaign_id, parent_id, name, description, visible_to_party, created_at, updated_at
`

type SetLocationPartyVisibilityParams struct {
	ID             uuid.UUID `json:"id"`
	VisibleToParty bool      `json:"visible_to_party"`
}

func (q *Queries) SetLocationPartyVisibility(ctx context.Context, arg SetLocationPartyVisibilityParams) (Location, error) {
	row := q.db.QueryRow(ctx, setLocationPartyVisibility, arg.ID, arg.VisibleToParty)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.VisibleToParty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name        = $2,
    description = $3,
    parent_id   = $4,
    updated_at  = now()
WHERE id = $1
RETURNING id, campaign_id, parent_id, name, description, visible_to_party, created_at, updated_at
`

type UpdateLocationParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.VisibleToParty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
