// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearLocationOverrides = `-- name: ClearLocationOverrides :exec
DELETE FROM location_visibility WHERE location_id = $1
`

func (q *Queries) ClearLocationOverrides(ctx context.Context, locationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLocationOverrides, locationID)
	return err
}

const countQuestsInLocation = `-- name: CountQuestsInLocation :one
SELECT count(*) FROM quests WHERE location_id = $1
`

func (q *Queries) CountQuestsInLocation(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestsInLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (realm_id, parent_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, parent_id, name, description, created_at, updated_at, realm_id
`

type CreateLocationParams struct {
	RealmID     uuid.UUID   `json:"realm_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

// Ground: the place is charted onto the realm (#234). What the charting table
// knows of it is written separately, into location_campaign_state.
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.RealmID,
		arg.ParentID,
		arg.Name,
		arg.Description,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealmID,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deleteLocationOverride = `-- name: DeleteLocationOverride :exec
DELETE FROM location_visibility WHERE location_id = $1 AND character_id = $2
`

type DeleteLocationOverrideParams struct {
	LocationID  uuid.UUID `json:"location_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteLocationOverride(ctx context.Context, arg DeleteLocationOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteLocationOverride, arg.LocationID, arg.CharacterID)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, parent_id, name, description, created_at, updated_at, realm_id FROM locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealmID,
	)
	return i, err
}

const getLocationForCampaign = `-- name: GetLocationForCampaign :one
SELECT l.id, l.parent_id, l.name, l.description, l.created_at, l.updated_at, l.realm_id, COALESCE(s.visible_to_party, false)::boolean AS visible_to_party
FROM locations l
JOIN campaigns c ON c.realm_id = l.realm_id
LEFT JOIN location_campaign_state s ON s.location_id = l.id AND s.campaign_id = c.id
WHERE l.id = $1 AND c.id = $2
`

type GetLocationForCampaignParams struct {
	LocationID uuid.UUID `json:"location_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

type GetLocationForCampaignRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RealmID        uuid.UUID          `json:"realm_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

// A place THROUGH one table (#234): the row plus that table's flag — and no
// row at all when the place is not on the campaign's realm, so a place you do
// not stand on cannot be told from one that never was.
func (q *Queries) GetLocationForCampaign(ctx context.Context, arg GetLocationForCampaignParams) (GetLocationForCampaignRow, error) {
	row := q.db.QueryRow(ctx, getLocationForCampaign, arg.LocationID, arg.CampaignID)
	var i GetLocationForCampaignRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealmID,
		&i.VisibleToParty,
	)
	return i, err
}

const listLocationVisibilityByCampaign = `-- name: ListLocationVisibilityByCampaign :many
SELECT v.location_id, v.character_id, v.visible, c.name AS character_name
FROM location_visibility v
JOIN characters c ON c.id = v.character_id
WHERE c.campaign_id = $1::uuid
`

type ListLocationVisibilityByCampaignRow struct {
	LocationID    uuid.UUID `json:"location_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

// Per-hero exceptions for one table: the overrides of heroes SEATED at this
// campaign (#234). A hero sits at one table, so the rows were always its.
func (q *Queries) ListLocationVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListLocationVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listLocationVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationVisibilityByCampaignRow
	for rows.Next() {
		var i ListLocationVisibilityByCampaignRow
		if err := rows.Scan(
			&i.LocationID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByCampaign = `-- name: ListLocationsByCampaign :many
SELECT l.id, l.parent_id, l.name, l.description, l.created_at, l.updated_at, l.realm_id, COALESCE(s.visible_to_party, false)::boolean AS visible_to_party
FROM locations l
JOIN campaigns c ON c.realm_id = l.realm_id
LEFT JOIN location_campaign_state s ON s.location_id = l.id AND s.campaign_id = c.id
WHERE c.id = $1
ORDER BY l.name
`

type ListLocationsByCampaignRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RealmID        uuid.UUID          `json:"realm_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

// The realm's places as ONE table knows them (#234): every place on the
// campaign's realm, with this campaign's own visible_to_party overlaid. No
// state row reads as veiled — a table founded on old ground starts dark, and
// its DM reveals as the party finds things.
func (q *Queries) ListLocationsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListLocationsByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listLocationsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsByCampaignRow
	for rows.Next() {
		var i ListLocationsByCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RealmID,
			&i.VisibleToParty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveLocation = `-- name: MoveLocation :one
UPDATE locations
SET parent_id  = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, parent_id, name, description, created_at, updated_at, realm_id
`

type MoveLocationParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) MoveLocation(ctx context.Context, arg MoveLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, moveLocation, arg.ID, arg.ParentID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealmID,
	)
	return i, err
}

const rememberLocationNamesBeforeDelete = `-- name: RememberLocationNamesBeforeDelete :exec
WITH RECURSIVE subtree(loc_id, loc_name) AS (
    SELECT root.id, root.name FROM locations root WHERE root.id = $1
    UNION ALL
    SELECT child.id, child.name
    FROM locations child
    JOIN subtree ON child.parent_id = subtree.loc_id
)
UPDATE quests q
SET location = subtree.loc_name
FROM subtree
WHERE q.location_id = subtree.loc_id
`

// Erasing a place cascades to the places nested inside it and unpins every
// notice hanging in any of them. Stamp the current names onto those notices
// first, so a notice still remembers where it hung — by the right name.
func (q *Queries) RememberLocationNamesBeforeDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, rememberLocationNamesBeforeDelete, id)
	return err
}

const setLocationOverride = `-- name: SetLocationOverride :exec

INSERT INTO location_visibility (location_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (location_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetLocationOverrideParams struct {
	LocationID  uuid.UUID `json:"location_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

// Per-hero exceptions. Setting the party-wide flag clears these, so a
// party-wide reveal or hide always wins over stale per-hero rows.
func (q *Queries) SetLocationOverride(ctx context.Context, arg SetLocationOverrideParams) error {
	_, err := q.db.Exec(ctx, setLocationOverride, arg.LocationID, arg.CharacterID, arg.Visible)
	return err
}

const setLocationPartyVisibility = `-- name: SetLocationPartyVisibility :exec
INSERT INTO location_campaign_state (location_id, campaign_id, visible_to_party)
VALUES ($1, $2, $3)
ON CONFLICT (location_id, campaign_id)
DO UPDATE SET visible_to_party = EXCLUDED.visible_to_party, updated_at = now()
`

type SetLocationPartyVisibilityParams struct {
	LocationID     uuid.UUID `json:"location_id"`
	CampaignID     uuid.UUID `json:"campaign_id"`
	VisibleToParty bool      `json:"visible_to_party"`
}

// One table's flag on a place (#234) — an upsert, because "no row" is the
// veiled default and a first reveal is what creates the row.
func (q *Queries) SetLocationPartyVisibility(ctx context.Context, arg SetLocationPartyVisibilityParams) error {
	_, err := q.db.Exec(ctx, setLocationPartyVisibility, arg.LocationID, arg.CampaignID, arg.VisibleToParty)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name        = $2,
    description = $3,
    updated_at  = now()
WHERE id = $1
RETURNING id, parent_id, name, description, created_at, updated_at, realm_id
`

type UpdateLocationParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

// Text only. Moving a place is MoveLocation, so that a rename can never touch
// the tree — see the note on UpdateLocationRequest in openapi.yaml.
func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation, arg.ID, arg.Name, arg.Description)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RealmID,
	)
	return i, err
}
