// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maps.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMapOverrides = `-- name: ClearMapOverrides :exec
DELETE FROM map_visibility WHERE map_id = $1
`

func (q *Queries) ClearMapOverrides(ctx context.Context, mapID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMapOverrides, mapID)
	return err
}

const createMap = `-- name: CreateMap :one
INSERT INTO maps (campaign_id, parent_map_id, name, image, content_type, width, height, location_id, visible_to_party)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, campaign_id, parent_map_id, name, fog_enabled, width, height, created_at, location_id, visible_to_party
`

type CreateMapParams struct {
	CampaignID     uuid.UUID   `json:"campaign_id"`
	ParentMapID    pgtype.UUID `json:"parent_map_id"`
	Name           string      `json:"name"`
	Image          []byte      `json:"image"`
	ContentType    string      `json:"content_type"`
	Width          int32       `json:"width"`
	Height         int32       `json:"height"`
	LocationID     pgtype.UUID `json:"location_id"`
	VisibleToParty bool        `json:"visible_to_party"`
}

type CreateMapRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	ParentMapID    pgtype.UUID        `json:"parent_map_id"`
	Name           string             `json:"name"`
	FogEnabled     bool               `json:"fog_enabled"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LocationID     pgtype.UUID        `json:"location_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (CreateMapRow, error) {
	row := q.db.QueryRow(ctx, createMap,
		arg.CampaignID,
		arg.ParentMapID,
		arg.Name,
		arg.Image,
		arg.ContentType,
		arg.Width,
		arg.Height,
		arg.LocationID,
		arg.VisibleToParty,
	)
	var i CreateMapRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentMapID,
		&i.Name,
		&i.FogEnabled,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.LocationID,
		&i.VisibleToParty,
	)
	return i, err
}

const createMapPin = `-- name: CreateMapPin :one
INSERT INTO map_pins (map_id, label, note, x, y, dm_only, link_map_id, shape)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, map_id, label, note, x, y, dm_only, link_map_id, created_at, shape
`

type CreateMapPinParams struct {
	MapID     uuid.UUID   `json:"map_id"`
	Label     string      `json:"label"`
	Note      string      `json:"note"`
	X         float64     `json:"x"`
	Y         float64     `json:"y"`
	DmOnly    bool        `json:"dm_only"`
	LinkMapID pgtype.UUID `json:"link_map_id"`
	Shape     string      `json:"shape"`
}

func (q *Queries) CreateMapPin(ctx context.Context, arg CreateMapPinParams) (MapPin, error) {
	row := q.db.QueryRow(ctx, createMapPin,
		arg.MapID,
		arg.Label,
		arg.Note,
		arg.X,
		arg.Y,
		arg.DmOnly,
		arg.LinkMapID,
		arg.Shape,
	)
	var i MapPin
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Label,
		&i.Note,
		&i.X,
		&i.Y,
		&i.DmOnly,
		&i.LinkMapID,
		&i.CreatedAt,
		&i.Shape,
	)
	return i, err
}

const createMapShape = `-- name: CreateMapShape :one
INSERT INTO map_shapes (map_id, kind, label, points, color, dashed, width, opacity, dm_only, location_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, map_id, kind, label, points, color, dashed, width, opacity, dm_only, location_id, created_at, updated_at
`

type CreateMapShapeParams struct {
	MapID      uuid.UUID    `json:"map_id"`
	Kind       MapShapeKind `json:"kind"`
	Label      string       `json:"label"`
	Points     []byte       `json:"points"`
	Color      string       `json:"color"`
	Dashed     bool         `json:"dashed"`
	Width      float64      `json:"width"`
	Opacity    float64      `json:"opacity"`
	DmOnly     bool         `json:"dm_only"`
	LocationID pgtype.UUID  `json:"location_id"`
}

func (q *Queries) CreateMapShape(ctx context.Context, arg CreateMapShapeParams) (MapShape, error) {
	row := q.db.QueryRow(ctx, createMapShape,
		arg.MapID,
		arg.Kind,
		arg.Label,
		arg.Points,
		arg.Color,
		arg.Dashed,
		arg.Width,
		arg.Opacity,
		arg.DmOnly,
		arg.LocationID,
	)
	var i MapShape
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Label,
		&i.Points,
		&i.Color,
		&i.Dashed,
		&i.Width,
		&i.Opacity,
		&i.DmOnly,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMap = `-- name: DeleteMap :execrows
DELETE FROM maps WHERE id = $1
`

func (q *Queries) DeleteMap(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMapOverride = `-- name: DeleteMapOverride :exec
DELETE FROM map_visibility WHERE map_id = $1 AND character_id = $2
`

type DeleteMapOverrideParams struct {
	MapID       uuid.UUID `json:"map_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteMapOverride(ctx context.Context, arg DeleteMapOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteMapOverride, arg.MapID, arg.CharacterID)
	return err
}

const deleteMapPin = `-- name: DeleteMapPin :execrows
DELETE FROM map_pins WHERE id = $1
`

func (q *Queries) DeleteMapPin(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMapPin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMapShape = `-- name: DeleteMapShape :execrows
DELETE FROM map_shapes WHERE id = $1
`

func (q *Queries) DeleteMapShape(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMapShape, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMapImage = `-- name: GetMapImage :one
SELECT image, content_type, created_at
FROM maps
WHERE id = $1
`

type GetMapImageRow struct {
	Image       []byte             `json:"image"`
	ContentType string             `json:"content_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMapImage(ctx context.Context, id uuid.UUID) (GetMapImageRow, error) {
	row := q.db.QueryRow(ctx, getMapImage, id)
	var i GetMapImageRow
	err := row.Scan(&i.Image, &i.ContentType, &i.CreatedAt)
	return i, err
}

const getMapMeta = `-- name: GetMapMeta :one
SELECT id, campaign_id, parent_map_id, name, fog_enabled, width, height, created_at, location_id,
       visible_to_party
FROM maps
WHERE id = $1
`

type GetMapMetaRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	ParentMapID    pgtype.UUID        `json:"parent_map_id"`
	Name           string             `json:"name"`
	FogEnabled     bool               `json:"fog_enabled"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LocationID     pgtype.UUID        `json:"location_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

func (q *Queries) GetMapMeta(ctx context.Context, id uuid.UUID) (GetMapMetaRow, error) {
	row := q.db.QueryRow(ctx, getMapMeta, id)
	var i GetMapMetaRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentMapID,
		&i.Name,
		&i.FogEnabled,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.LocationID,
		&i.VisibleToParty,
	)
	return i, err
}

const getMapPin = `-- name: GetMapPin :one
SELECT p.id, p.map_id, p.label, p.note, p.x, p.y, p.dm_only, p.link_map_id, p.created_at, p.shape, m.campaign_id
FROM map_pins p
JOIN maps m ON m.id = p.map_id
WHERE p.id = $1
`

type GetMapPinRow struct {
	ID         uuid.UUID          `json:"id"`
	MapID      uuid.UUID          `json:"map_id"`
	Label      string             `json:"label"`
	Note       string             `json:"note"`
	X          float64            `json:"x"`
	Y          float64            `json:"y"`
	DmOnly     bool               `json:"dm_only"`
	LinkMapID  pgtype.UUID        `json:"link_map_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Shape      string             `json:"shape"`
	CampaignID uuid.UUID          `json:"campaign_id"`
}

// A pin with its map's campaign, so handlers can gate on membership in one read.
func (q *Queries) GetMapPin(ctx context.Context, id uuid.UUID) (GetMapPinRow, error) {
	row := q.db.QueryRow(ctx, getMapPin, id)
	var i GetMapPinRow
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Label,
		&i.Note,
		&i.X,
		&i.Y,
		&i.DmOnly,
		&i.LinkMapID,
		&i.CreatedAt,
		&i.Shape,
		&i.CampaignID,
	)
	return i, err
}

const getMapShape = `-- name: GetMapShape :one
SELECT s.id, s.map_id, s.kind, s.label, s.points, s.color, s.dashed, s.width, s.opacity, s.dm_only, s.location_id, s.created_at, s.updated_at, m.campaign_id
FROM map_shapes s
JOIN maps m ON m.id = s.map_id
WHERE s.id = $1
`

type GetMapShapeRow struct {
	ID         uuid.UUID          `json:"id"`
	MapID      uuid.UUID          `json:"map_id"`
	Kind       MapShapeKind       `json:"kind"`
	Label      string             `json:"label"`
	Points     []byte             `json:"points"`
	Color      string             `json:"color"`
	Dashed     bool               `json:"dashed"`
	Width      float64            `json:"width"`
	Opacity    float64            `json:"opacity"`
	DmOnly     bool               `json:"dm_only"`
	LocationID pgtype.UUID        `json:"location_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	CampaignID uuid.UUID          `json:"campaign_id"`
}

// A shape with its map's campaign, so handlers gate on membership in one read.
func (q *Queries) GetMapShape(ctx context.Context, id uuid.UUID) (GetMapShapeRow, error) {
	row := q.db.QueryRow(ctx, getMapShape, id)
	var i GetMapShapeRow
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Label,
		&i.Points,
		&i.Color,
		&i.Dashed,
		&i.Width,
		&i.Opacity,
		&i.DmOnly,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CampaignID,
	)
	return i, err
}

const listMapPins = `-- name: ListMapPins :many
SELECT id, map_id, label, note, x, y, dm_only, link_map_id, created_at, shape FROM map_pins WHERE map_id = $1 ORDER BY created_at
`

func (q *Queries) ListMapPins(ctx context.Context, mapID uuid.UUID) ([]MapPin, error) {
	rows, err := q.db.Query(ctx, listMapPins, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapPin
	for rows.Next() {
		var i MapPin
		if err := rows.Scan(
			&i.ID,
			&i.MapID,
			&i.Label,
			&i.Note,
			&i.X,
			&i.Y,
			&i.DmOnly,
			&i.LinkMapID,
			&i.CreatedAt,
			&i.Shape,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapShapes = `-- name: ListMapShapes :many
SELECT id, map_id, kind, label, points, color, dashed, width, opacity, dm_only, location_id, created_at, updated_at FROM map_shapes WHERE map_id = $1 ORDER BY created_at
`

func (q *Queries) ListMapShapes(ctx context.Context, mapID uuid.UUID) ([]MapShape, error) {
	rows, err := q.db.Query(ctx, listMapShapes, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MapShape
	for rows.Next() {
		var i MapShape
		if err := rows.Scan(
			&i.ID,
			&i.MapID,
			&i.Kind,
			&i.Label,
			&i.Points,
			&i.Color,
			&i.Dashed,
			&i.Width,
			&i.Opacity,
			&i.DmOnly,
			&i.LocationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapVisibilityByCampaign = `-- name: ListMapVisibilityByCampaign :many
SELECT v.map_id, v.character_id, v.visible, c.name AS character_name
FROM map_visibility v
JOIN maps m ON m.id = v.map_id
JOIN characters c ON c.id = v.character_id
WHERE m.campaign_id = $1
`

type ListMapVisibilityByCampaignRow struct {
	MapID         uuid.UUID `json:"map_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListMapVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListMapVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listMapVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapVisibilityByCampaignRow
	for rows.Next() {
		var i ListMapVisibilityByCampaignRow
		if err := rows.Scan(
			&i.MapID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapsByCampaign = `-- name: ListMapsByCampaign :many
SELECT m.id, m.campaign_id, m.parent_map_id, m.name, m.fog_enabled, m.width, m.height, m.created_at,
       m.location_id, m.visible_to_party, l.name AS location_name
FROM maps m
LEFT JOIN locations l ON l.id = m.location_id
WHERE m.campaign_id = $1
ORDER BY m.created_at
`

type ListMapsByCampaignRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	ParentMapID    pgtype.UUID        `json:"parent_map_id"`
	Name           string             `json:"name"`
	FogEnabled     bool               `json:"fog_enabled"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LocationID     pgtype.UUID        `json:"location_id"`
	VisibleToParty bool               `json:"visible_to_party"`
	LocationName   *string            `json:"location_name"`
}

// The atlas shelf: every map of the campaign, oldest first, no image bytes.
// The place a map depicts rides along by name (#229).
func (q *Queries) ListMapsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListMapsByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listMapsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMapsByCampaignRow
	for rows.Next() {
		var i ListMapsByCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ParentMapID,
			&i.Name,
			&i.FogEnabled,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.LocationID,
			&i.VisibleToParty,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMapOverride = `-- name: SetMapOverride :exec
INSERT INTO map_visibility (map_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (map_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetMapOverrideParams struct {
	MapID       uuid.UUID `json:"map_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

func (q *Queries) SetMapOverride(ctx context.Context, arg SetMapOverrideParams) error {
	_, err := q.db.Exec(ctx, setMapOverride, arg.MapID, arg.CharacterID, arg.Visible)
	return err
}

const setMapPartyVisibility = `-- name: SetMapPartyVisibility :one

UPDATE maps
SET visible_to_party = $2
WHERE id = $1
RETURNING id, campaign_id, parent_map_id, name, fog_enabled, width, height, created_at, location_id,
          visible_to_party
`

type SetMapPartyVisibilityParams struct {
	ID             uuid.UUID `json:"id"`
	VisibleToParty bool      `json:"visible_to_party"`
}

type SetMapPartyVisibilityRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	ParentMapID    pgtype.UUID        `json:"parent_map_id"`
	Name           string             `json:"name"`
	FogEnabled     bool               `json:"fog_enabled"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LocationID     pgtype.UUID        `json:"location_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

// The veil over a map's very existence (#276). Same two layers as everything
// else in a campaign: one party-wide flag, per-hero exceptions over it.
func (q *Queries) SetMapPartyVisibility(ctx context.Context, arg SetMapPartyVisibilityParams) (SetMapPartyVisibilityRow, error) {
	row := q.db.QueryRow(ctx, setMapPartyVisibility, arg.ID, arg.VisibleToParty)
	var i SetMapPartyVisibilityRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentMapID,
		&i.Name,
		&i.FogEnabled,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.LocationID,
		&i.VisibleToParty,
	)
	return i, err
}

const updateMapMeta = `-- name: UpdateMapMeta :one
UPDATE maps
SET name = $2, parent_map_id = $3, fog_enabled = $4, location_id = $5
WHERE id = $1
RETURNING id, campaign_id, parent_map_id, name, fog_enabled, width, height, created_at, location_id,
          visible_to_party
`

type UpdateMapMetaParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	ParentMapID pgtype.UUID `json:"parent_map_id"`
	FogEnabled  bool        `json:"fog_enabled"`
	LocationID  pgtype.UUID `json:"location_id"`
}

type UpdateMapMetaRow struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     uuid.UUID          `json:"campaign_id"`
	ParentMapID    pgtype.UUID        `json:"parent_map_id"`
	Name           string             `json:"name"`
	FogEnabled     bool               `json:"fog_enabled"`
	Width          int32              `json:"width"`
	Height         int32              `json:"height"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LocationID     pgtype.UUID        `json:"location_id"`
	VisibleToParty bool               `json:"visible_to_party"`
}

func (q *Queries) UpdateMapMeta(ctx context.Context, arg UpdateMapMetaParams) (UpdateMapMetaRow, error) {
	row := q.db.QueryRow(ctx, updateMapMeta,
		arg.ID,
		arg.Name,
		arg.ParentMapID,
		arg.FogEnabled,
		arg.LocationID,
	)
	var i UpdateMapMetaRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ParentMapID,
		&i.Name,
		&i.FogEnabled,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.LocationID,
		&i.VisibleToParty,
	)
	return i, err
}

const updateMapPin = `-- name: UpdateMapPin :one
UPDATE map_pins
SET label = $2, note = $3, x = $4, y = $5, dm_only = $6, link_map_id = $7, shape = $8
WHERE id = $1
RETURNING id, map_id, label, note, x, y, dm_only, link_map_id, created_at, shape
`

type UpdateMapPinParams struct {
	ID        uuid.UUID   `json:"id"`
	Label     string      `json:"label"`
	Note      string      `json:"note"`
	X         float64     `json:"x"`
	Y         float64     `json:"y"`
	DmOnly    bool        `json:"dm_only"`
	LinkMapID pgtype.UUID `json:"link_map_id"`
	Shape     string      `json:"shape"`
}

func (q *Queries) UpdateMapPin(ctx context.Context, arg UpdateMapPinParams) (MapPin, error) {
	row := q.db.QueryRow(ctx, updateMapPin,
		arg.ID,
		arg.Label,
		arg.Note,
		arg.X,
		arg.Y,
		arg.DmOnly,
		arg.LinkMapID,
		arg.Shape,
	)
	var i MapPin
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Label,
		&i.Note,
		&i.X,
		&i.Y,
		&i.DmOnly,
		&i.LinkMapID,
		&i.CreatedAt,
		&i.Shape,
	)
	return i, err
}

const updateMapShape = `-- name: UpdateMapShape :one
UPDATE map_shapes
SET label = $2, points = $3, color = $4, dashed = $5, width = $6,
    opacity = $7, dm_only = $8, location_id = $9, updated_at = now()
WHERE id = $1
RETURNING id, map_id, kind, label, points, color, dashed, width, opacity, dm_only, location_id, created_at, updated_at
`

type UpdateMapShapeParams struct {
	ID         uuid.UUID   `json:"id"`
	Label      string      `json:"label"`
	Points     []byte      `json:"points"`
	Color      string      `json:"color"`
	Dashed     bool        `json:"dashed"`
	Width      float64     `json:"width"`
	Opacity    float64     `json:"opacity"`
	DmOnly     bool        `json:"dm_only"`
	LocationID pgtype.UUID `json:"location_id"`
}

func (q *Queries) UpdateMapShape(ctx context.Context, arg UpdateMapShapeParams) (MapShape, error) {
	row := q.db.QueryRow(ctx, updateMapShape,
		arg.ID,
		arg.Label,
		arg.Points,
		arg.Color,
		arg.Dashed,
		arg.Width,
		arg.Opacity,
		arg.DmOnly,
		arg.LocationID,
	)
	var i MapShape
	err := row.Scan(
		&i.ID,
		&i.MapID,
		&i.Kind,
		&i.Label,
		&i.Points,
		&i.Color,
		&i.Dashed,
		&i.Width,
		&i.Opacity,
		&i.DmOnly,
		&i.LocationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
