// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CodexStatus string

const (
	CodexStatusProposed CodexStatus = "proposed"
	CodexStatusEnabled  CodexStatus = "enabled"
	CodexStatusBanned   CodexStatus = "banned"
)

func (e *CodexStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CodexStatus(s)
	case string:
		*e = CodexStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CodexStatus: %T", src)
	}
	return nil
}

type NullCodexStatus struct {
	CodexStatus CodexStatus `json:"codex_status"`
	Valid       bool        `json:"valid"` // Valid is true if CodexStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCodexStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CodexStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CodexStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCodexStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CodexStatus), nil
}

type ContentKind string

const (
	ContentKindClass      ContentKind = "class"
	ContentKindSpecies    ContentKind = "species"
	ContentKindBackground ContentKind = "background"
	ContentKindSubclass   ContentKind = "subclass"
	ContentKindFeat       ContentKind = "feat"
	ContentKindSpell      ContentKind = "spell"
	ContentKindItem       ContentKind = "item"
	ContentKindMonster    ContentKind = "monster"
)

func (e *ContentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentKind(s)
	case string:
		*e = ContentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentKind: %T", src)
	}
	return nil
}

type NullContentKind struct {
	ContentKind ContentKind `json:"content_kind"`
	Valid       bool        `json:"valid"` // Valid is true if ContentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentKind) Scan(value interface{}) error {
	if value == nil {
		ns.ContentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentKind), nil
}

type ContentSource string

const (
	ContentSourceSrd      ContentSource = "srd"
	ContentSourceHomebrew ContentSource = "homebrew"
)

func (e *ContentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentSource(s)
	case string:
		*e = ContentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentSource: %T", src)
	}
	return nil
}

type NullContentSource struct {
	ContentSource ContentSource `json:"content_source"`
	Valid         bool          `json:"valid"` // Valid is true if ContentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentSource) Scan(value interface{}) error {
	if value == nil {
		ns.ContentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentSource), nil
}

type MembershipRole string

const (
	MembershipRoleDm     MembershipRole = "dm"
	MembershipRolePlayer MembershipRole = "player"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type NodeRarity string

const (
	NodeRarityMinor    NodeRarity = "minor"
	NodeRarityKeystone NodeRarity = "keystone"
)

func (e *NodeRarity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeRarity(s)
	case string:
		*e = NodeRarity(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeRarity: %T", src)
	}
	return nil
}

type NullNodeRarity struct {
	NodeRarity NodeRarity `json:"node_rarity"`
	Valid      bool       `json:"valid"` // Valid is true if NodeRarity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeRarity) Scan(value interface{}) error {
	if value == nil {
		ns.NodeRarity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeRarity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeRarity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeRarity), nil
}

type ProgressionMode string

const (
	ProgressionModeMilestone ProgressionMode = "milestone"
	ProgressionModeXp        ProgressionMode = "xp"
)

func (e *ProgressionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressionMode(s)
	case string:
		*e = ProgressionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressionMode: %T", src)
	}
	return nil
}

type NullProgressionMode struct {
	ProgressionMode ProgressionMode `json:"progression_mode"`
	Valid           bool            `json:"valid"` // Valid is true if ProgressionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressionMode) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressionMode), nil
}

type QuestDifficulty string

const (
	QuestDifficultyTrivial QuestDifficulty = "trivial"
	QuestDifficultyEasy    QuestDifficulty = "easy"
	QuestDifficultyMedium  QuestDifficulty = "medium"
	QuestDifficultyHard    QuestDifficulty = "hard"
	QuestDifficultyDeadly  QuestDifficulty = "deadly"
)

func (e *QuestDifficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestDifficulty(s)
	case string:
		*e = QuestDifficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestDifficulty: %T", src)
	}
	return nil
}

type NullQuestDifficulty struct {
	QuestDifficulty QuestDifficulty `json:"quest_difficulty"`
	Valid           bool            `json:"valid"` // Valid is true if QuestDifficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.QuestDifficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestDifficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestDifficulty), nil
}

type QuestStatus string

const (
	QuestStatusAvailable QuestStatus = "available"
	QuestStatusActive    QuestStatus = "active"
	QuestStatusCompleted QuestStatus = "completed"
	QuestStatusFailed    QuestStatus = "failed"
)

func (e *QuestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestStatus(s)
	case string:
		*e = QuestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestStatus: %T", src)
	}
	return nil
}

type NullQuestStatus struct {
	QuestStatus QuestStatus `json:"quest_status"`
	Valid       bool        `json:"valid"` // Valid is true if QuestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestStatus), nil
}

type RewardType string

const (
	RewardTypeGold       RewardType = "gold"
	RewardTypeItem       RewardType = "item"
	RewardTypeXp         RewardType = "xp"
	RewardTypeReputation RewardType = "reputation"
	RewardTypeOther      RewardType = "other"
)

func (e *RewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RewardType(s)
	case string:
		*e = RewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for RewardType: %T", src)
	}
	return nil
}

type NullRewardType struct {
	RewardType RewardType `json:"reward_type"`
	Valid      bool       `json:"valid"` // Valid is true if RewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.RewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RewardType), nil
}

type BestiaryEntry struct {
	ID         uuid.UUID          `json:"id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	ContentID  pgtype.UUID        `json:"content_id"`
	Title      string             `json:"title"`
	Revealed   []string           `json:"revealed"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type BestiaryNote struct {
	ID        uuid.UUID          `json:"id"`
	EntryID   uuid.UUID          `json:"entry_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Campaign struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	InviteCode    string             `json:"invite_code"`
	NextSessionAt pgtype.Timestamptz `json:"next_session_at"`
	Progression   ProgressionMode    `json:"progression"`
}

type CampaignContent struct {
	CampaignID uuid.UUID          `json:"campaign_id"`
	ContentID  uuid.UUID          `json:"content_id"`
	Status     CodexStatus        `json:"status"`
	ProposedBy pgtype.UUID        `json:"proposed_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CampaignEvent struct {
	ID          uuid.UUID          `json:"id"`
	CampaignID  uuid.UUID          `json:"campaign_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Kind        string             `json:"kind"`
	Message     string             `json:"message"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Character struct {
	ID             uuid.UUID          `json:"id"`
	CampaignID     pgtype.UUID        `json:"campaign_id"`
	OwnerUserID    uuid.UUID          `json:"owner_user_id"`
	Name           string             `json:"name"`
	Class          string             `json:"class"`
	Level          int32              `json:"level"`
	HpCurrent      int32              `json:"hp_current"`
	HpMax          int32              `json:"hp_max"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Strength       *int16             `json:"strength"`
	Dexterity      *int16             `json:"dexterity"`
	Constitution   *int16             `json:"constitution"`
	Intelligence   *int16             `json:"intelligence"`
	Wisdom         *int16             `json:"wisdom"`
	Charisma       *int16             `json:"charisma"`
	Skills         []string           `json:"skills"`
	ClassID        pgtype.UUID        `json:"class_id"`
	SpeciesID      pgtype.UUID        `json:"species_id"`
	BackgroundID   pgtype.UUID        `json:"background_id"`
	SubclassID     pgtype.UUID        `json:"subclass_id"`
	Feats          []string           `json:"feats"`
	SpellSlotsUsed []int16            `json:"spell_slots_used"`
	Xp             int32              `json:"xp"`
	PendingLevels  int16              `json:"pending_levels"`
}

type CharacterItem struct {
	ID          uuid.UUID          `json:"id"`
	CharacterID uuid.UUID          `json:"character_id"`
	ContentID   pgtype.UUID        `json:"content_id"`
	Name        string             `json:"name"`
	Qty         int32              `json:"qty"`
	Equipped    bool               `json:"equipped"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Slot        string             `json:"slot"`
}

type CharacterNode struct {
	CharacterID uuid.UUID          `json:"character_id"`
	NodeID      uuid.UUID          `json:"node_id"`
	PickedAt    pgtype.Timestamptz `json:"picked_at"`
}

type CharacterSpell struct {
	CharacterID uuid.UUID          `json:"character_id"`
	ContentID   uuid.UUID          `json:"content_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CharacterTree struct {
	CharacterID  uuid.UUID `json:"character_id"`
	TreeID       uuid.UUID `json:"tree_id"`
	PicksGranted int32     `json:"picks_granted"`
}

type KnowledgePool struct {
	ID         uuid.UUID          `json:"id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	Name       string             `json:"name"`
	IsParty    bool               `json:"is_party"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type KnowledgePoolMember struct {
	PoolID uuid.UUID `json:"pool_id"`
	UserID uuid.UUID `json:"user_id"`
}

type Map struct {
	ID          uuid.UUID          `json:"id"`
	CampaignID  uuid.UUID          `json:"campaign_id"`
	ParentMapID pgtype.UUID        `json:"parent_map_id"`
	Name        string             `json:"name"`
	Image       []byte             `json:"image"`
	ContentType string             `json:"content_type"`
	Width       int32              `json:"width"`
	Height      int32              `json:"height"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	FogEnabled  bool               `json:"fog_enabled"`
}

type MapPin struct {
	ID        uuid.UUID          `json:"id"`
	MapID     uuid.UUID          `json:"map_id"`
	Label     string             `json:"label"`
	Note      string             `json:"note"`
	X         float64            `json:"x"`
	Y         float64            `json:"y"`
	DmOnly    bool               `json:"dm_only"`
	LinkMapID pgtype.UUID        `json:"link_map_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	UserID     uuid.UUID          `json:"user_id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	Role       MembershipRole     `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Quest struct {
	ID          uuid.UUID          `json:"id"`
	CampaignID  uuid.UUID          `json:"campaign_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Giver       *string            `json:"giver"`
	Location    *string            `json:"location"`
	Difficulty  QuestDifficulty    `json:"difficulty"`
	Status      QuestStatus        `json:"status"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type QuestClaim struct {
	QuestID   uuid.UUID          `json:"quest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

type QuestReward struct {
	ID      uuid.UUID  `json:"id"`
	QuestID uuid.UUID  `json:"quest_id"`
	Type    RewardType `json:"type"`
	Label   string     `json:"label"`
	Value   *string    `json:"value"`
}

type RevealBatch struct {
	ID        uuid.UUID          `json:"id"`
	MapID     uuid.UUID          `json:"map_id"`
	PoolID    uuid.UUID          `json:"pool_id"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RevealCircle struct {
	ID      uuid.UUID `json:"id"`
	BatchID uuid.UUID `json:"batch_id"`
	X       float64   `json:"x"`
	Y       float64   `json:"y"`
	R       float64   `json:"r"`
}

type RulesContent struct {
	ID        uuid.UUID          `json:"id"`
	Kind      ContentKind        `json:"kind"`
	Source    ContentSource      `json:"source"`
	Name      string             `json:"name"`
	Summary   string             `json:"summary"`
	Data      []byte             `json:"data"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Data   []byte             `json:"data"`
	Expiry pgtype.Timestamptz `json:"expiry"`
}

type SkillEdge struct {
	TreeID uuid.UUID `json:"tree_id"`
	NodeA  uuid.UUID `json:"node_a"`
	NodeB  uuid.UUID `json:"node_b"`
}

type SkillNode struct {
	ID          uuid.UUID          `json:"id"`
	TreeID      uuid.UUID          `json:"tree_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Tradeoff    *string            `json:"tradeoff"`
	Rarity      NodeRarity         `json:"rarity"`
	Limb        string             `json:"limb"`
	IsEntry     bool               `json:"is_entry"`
	PosX        *float32           `json:"pos_x"`
	PosY        *float32           `json:"pos_y"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SkillTree struct {
	ID               uuid.UUID          `json:"id"`
	CampaignID       uuid.UUID          `json:"campaign_id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	KeystonePickCost int32              `json:"keystone_pick_cost"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        *string            `json:"email"`
	Image        *string            `json:"image"`
	Provider     string             `json:"provider"`
	ProviderID   string             `json:"provider_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     *string            `json:"username"`
	PasswordHash *string            `json:"password_hash"`
}
