// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: npcs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearNpcOverrides = `-- name: ClearNpcOverrides :exec
DELETE FROM npc_visibility WHERE npc_id = $1
`

func (q *Queries) ClearNpcOverrides(ctx context.Context, npcID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearNpcOverrides, npcID)
	return err
}

const clearNpcStatOverrides = `-- name: ClearNpcStatOverrides :exec
DELETE FROM npc_stat_visibility WHERE npc_id = $1
`

func (q *Queries) ClearNpcStatOverrides(ctx context.Context, npcID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearNpcStatOverrides, npcID)
	return err
}

const createNpc = `-- name: CreateNpc :one
INSERT INTO npcs (campaign_id, name, description, location_id, content_id, character_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, name, description, location_id, content_id, character_id, visible_to_party, stats_visible_to_party, created_by, created_at, updated_at
`

type CreateNpcParams struct {
	CampaignID  uuid.UUID   `json:"campaign_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	LocationID  pgtype.UUID `json:"location_id"`
	ContentID   pgtype.UUID `json:"content_id"`
	CharacterID pgtype.UUID `json:"character_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateNpc(ctx context.Context, arg CreateNpcParams) (Npc, error) {
	row := q.db.QueryRow(ctx, createNpc,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.ContentID,
		arg.CharacterID,
		arg.CreatedBy,
	)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.ContentID,
		&i.CharacterID,
		&i.VisibleToParty,
		&i.StatsVisibleToParty,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNpc = `-- name: DeleteNpc :execrows
DELETE FROM npcs WHERE id = $1
`

func (q *Queries) DeleteNpc(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNpc, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNpcOverride = `-- name: DeleteNpcOverride :exec
DELETE FROM npc_visibility WHERE npc_id = $1 AND character_id = $2
`

type DeleteNpcOverrideParams struct {
	NpcID       uuid.UUID `json:"npc_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteNpcOverride(ctx context.Context, arg DeleteNpcOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteNpcOverride, arg.NpcID, arg.CharacterID)
	return err
}

const deleteNpcStatOverride = `-- name: DeleteNpcStatOverride :exec
DELETE FROM npc_stat_visibility WHERE npc_id = $1 AND character_id = $2
`

type DeleteNpcStatOverrideParams struct {
	NpcID       uuid.UUID `json:"npc_id"`
	CharacterID uuid.UUID `json:"character_id"`
}

func (q *Queries) DeleteNpcStatOverride(ctx context.Context, arg DeleteNpcStatOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteNpcStatOverride, arg.NpcID, arg.CharacterID)
	return err
}

const getNpc = `-- name: GetNpc :one
SELECT id, campaign_id, name, description, location_id, content_id, character_id, visible_to_party, stats_visible_to_party, created_by, created_at, updated_at FROM npcs WHERE id = $1
`

func (q *Queries) GetNpc(ctx context.Context, id uuid.UUID) (Npc, error) {
	row := q.db.QueryRow(ctx, getNpc, id)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.ContentID,
		&i.CharacterID,
		&i.VisibleToParty,
		&i.StatsVisibleToParty,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNpcStatVisibilityByCampaign = `-- name: ListNpcStatVisibilityByCampaign :many
SELECT v.npc_id, v.character_id, v.visible, c.name AS character_name
FROM npc_stat_visibility v
JOIN npcs n ON n.id = v.npc_id
JOIN characters c ON c.id = v.character_id
WHERE n.campaign_id = $1
`

type ListNpcStatVisibilityByCampaignRow struct {
	NpcID         uuid.UUID `json:"npc_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListNpcStatVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListNpcStatVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listNpcStatVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNpcStatVisibilityByCampaignRow
	for rows.Next() {
		var i ListNpcStatVisibilityByCampaignRow
		if err := rows.Scan(
			&i.NpcID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNpcVisibilityByCampaign = `-- name: ListNpcVisibilityByCampaign :many
SELECT v.npc_id, v.character_id, v.visible, c.name AS character_name
FROM npc_visibility v
JOIN npcs n ON n.id = v.npc_id
JOIN characters c ON c.id = v.character_id
WHERE n.campaign_id = $1
`

type ListNpcVisibilityByCampaignRow struct {
	NpcID         uuid.UUID `json:"npc_id"`
	CharacterID   uuid.UUID `json:"character_id"`
	Visible       bool      `json:"visible"`
	CharacterName string    `json:"character_name"`
}

func (q *Queries) ListNpcVisibilityByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListNpcVisibilityByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listNpcVisibilityByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNpcVisibilityByCampaignRow
	for rows.Next() {
		var i ListNpcVisibilityByCampaignRow
		if err := rows.Scan(
			&i.NpcID,
			&i.CharacterID,
			&i.Visible,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNpcs = `-- name: ListNpcs :many
SELECT n.id, n.campaign_id, n.name, n.description, n.location_id, n.content_id, n.character_id, n.visible_to_party, n.stats_visible_to_party, n.created_by, n.created_at, n.updated_at,
       l.name AS location_name,
       c.name AS character_name,
       rc.kind AS content_kind, rc.source AS content_source,
       rc.name AS content_name, rc.summary AS content_summary,
       rc.data AS content_data
FROM npcs n
LEFT JOIN locations l ON l.id = n.location_id
LEFT JOIN characters c ON c.id = n.character_id
LEFT JOIN rules_content rc ON rc.id = n.content_id
WHERE n.campaign_id = $1
ORDER BY l.name NULLS LAST, n.name
`

type ListNpcsRow struct {
	ID                  uuid.UUID          `json:"id"`
	CampaignID          uuid.UUID          `json:"campaign_id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	LocationID          pgtype.UUID        `json:"location_id"`
	ContentID           pgtype.UUID        `json:"content_id"`
	CharacterID         pgtype.UUID        `json:"character_id"`
	VisibleToParty      bool               `json:"visible_to_party"`
	StatsVisibleToParty bool               `json:"stats_visible_to_party"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LocationName        *string            `json:"location_name"`
	CharacterName       *string            `json:"character_name"`
	ContentKind         *ContentKind       `json:"content_kind"`
	ContentSource       *ContentSource     `json:"content_source"`
	ContentName         *string            `json:"content_name"`
	ContentSummary      *string            `json:"content_summary"`
	ContentData         []byte             `json:"content_data"`
}

// Everyone in a campaign, with the place they are found in, the Den block or
// the sheet behind them. Redaction is the handler's job — this hands over
// everything and the caller decides what the viewer is allowed to see.
func (q *Queries) ListNpcs(ctx context.Context, campaignID uuid.UUID) ([]ListNpcsRow, error) {
	rows, err := q.db.Query(ctx, listNpcs, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNpcsRow
	for rows.Next() {
		var i ListNpcsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.LocationID,
			&i.ContentID,
			&i.CharacterID,
			&i.VisibleToParty,
			&i.StatsVisibleToParty,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationName,
			&i.CharacterName,
			&i.ContentKind,
			&i.ContentSource,
			&i.ContentName,
			&i.ContentSummary,
			&i.ContentData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNpcOverride = `-- name: SetNpcOverride :exec

INSERT INTO npc_visibility (npc_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (npc_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetNpcOverrideParams struct {
	NpcID       uuid.UUID `json:"npc_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

// Per-hero exceptions. Setting the party-wide flag clears these, so a
// party-wide reveal or hide always wins over stale per-hero rows.
func (q *Queries) SetNpcOverride(ctx context.Context, arg SetNpcOverrideParams) error {
	_, err := q.db.Exec(ctx, setNpcOverride, arg.NpcID, arg.CharacterID, arg.Visible)
	return err
}

const setNpcPartyVisibility = `-- name: SetNpcPartyVisibility :one
UPDATE npcs
SET visible_to_party = $2,
    updated_at       = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, location_id, content_id, character_id, visible_to_party, stats_visible_to_party, created_by, created_at, updated_at
`

type SetNpcPartyVisibilityParams struct {
	ID             uuid.UUID `json:"id"`
	VisibleToParty bool      `json:"visible_to_party"`
}

func (q *Queries) SetNpcPartyVisibility(ctx context.Context, arg SetNpcPartyVisibilityParams) (Npc, error) {
	row := q.db.QueryRow(ctx, setNpcPartyVisibility, arg.ID, arg.VisibleToParty)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.ContentID,
		&i.CharacterID,
		&i.VisibleToParty,
		&i.StatsVisibleToParty,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setNpcStatOverride = `-- name: SetNpcStatOverride :exec
INSERT INTO npc_stat_visibility (npc_id, character_id, visible)
VALUES ($1, $2, $3)
ON CONFLICT (npc_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetNpcStatOverrideParams struct {
	NpcID       uuid.UUID `json:"npc_id"`
	CharacterID uuid.UUID `json:"character_id"`
	Visible     bool      `json:"visible"`
}

func (q *Queries) SetNpcStatOverride(ctx context.Context, arg SetNpcStatOverrideParams) error {
	_, err := q.db.Exec(ctx, setNpcStatOverride, arg.NpcID, arg.CharacterID, arg.Visible)
	return err
}

const setNpcStatsPartyVisibility = `-- name: SetNpcStatsPartyVisibility :one
UPDATE npcs
SET stats_visible_to_party = $2,
    updated_at             = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, location_id, content_id, character_id, visible_to_party, stats_visible_to_party, created_by, created_at, updated_at
`

type SetNpcStatsPartyVisibilityParams struct {
	ID                  uuid.UUID `json:"id"`
	StatsVisibleToParty bool      `json:"stats_visible_to_party"`
}

func (q *Queries) SetNpcStatsPartyVisibility(ctx context.Context, arg SetNpcStatsPartyVisibilityParams) (Npc, error) {
	row := q.db.QueryRow(ctx, setNpcStatsPartyVisibility, arg.ID, arg.StatsVisibleToParty)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.ContentID,
		&i.CharacterID,
		&i.VisibleToParty,
		&i.StatsVisibleToParty,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNpc = `-- name: UpdateNpc :one
UPDATE npcs
SET name = $2, description = $3, location_id = $4, content_id = $5, character_id = $6, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, location_id, content_id, character_id, visible_to_party, stats_visible_to_party, created_by, created_at, updated_at
`

type UpdateNpcParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	LocationID  pgtype.UUID `json:"location_id"`
	ContentID   pgtype.UUID `json:"content_id"`
	CharacterID pgtype.UUID `json:"character_id"`
}

func (q *Queries) UpdateNpc(ctx context.Context, arg UpdateNpcParams) (Npc, error) {
	row := q.db.QueryRow(ctx, updateNpc,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.ContentID,
		arg.CharacterID,
	)
	var i Npc
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.ContentID,
		&i.CharacterID,
		&i.VisibleToParty,
		&i.StatsVisibleToParty,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
