// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createParty = `-- name: CreateParty :one
INSERT INTO parties (campaign_id, name) VALUES ($1, $2) RETURNING id, campaign_id, name, created_at
`

type CreatePartyParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	Name       string    `json:"name"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty, arg.CampaignID, arg.Name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteParty = `-- name: DeleteParty :execrows
DELETE FROM parties WHERE id = $1
`

// Disbanding takes nothing from anybody: the heroes' party_id falls to NULL
// and every stamp they were ever given stays exactly where it is (#232).
func (q *Queries) DeleteParty(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParty = `-- name: GetParty :one
SELECT id, campaign_id, name, created_at FROM parties WHERE id = $1
`

func (q *Queries) GetParty(ctx context.Context, id uuid.UUID) (Party, error) {
	row := q.db.QueryRow(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listHeroPartiesByCampaign = `-- name: ListHeroPartiesByCampaign :many
SELECT id, owner_user_id, party_id FROM characters
WHERE campaign_id = $1 AND kind = 'hero'
`

type ListHeroPartiesByCampaignRow struct {
	ID          uuid.UUID   `json:"id"`
	OwnerUserID uuid.UUID   `json:"owner_user_id"`
	PartyID     pgtype.UUID `json:"party_id"`
}

// Every seated hero and the party they ride with, for resolving "may this
// viewer see that hero / that ally" in one read (#232).
func (q *Queries) ListHeroPartiesByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]ListHeroPartiesByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listHeroPartiesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeroPartiesByCampaignRow
	for rows.Next() {
		var i ListHeroPartiesByCampaignRow
		if err := rows.Scan(&i.ID, &i.OwnerUserID, &i.PartyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParties = `-- name: ListParties :many
SELECT p.id, p.campaign_id, p.name, p.created_at, count(c.id) AS hero_count
FROM parties p
LEFT JOIN characters c ON c.party_id = p.id AND c.kind = 'hero'
WHERE p.campaign_id = $1
GROUP BY p.id
ORDER BY p.created_at
`

type ListPartiesRow struct {
	ID         uuid.UUID          `json:"id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	HeroCount  int64              `json:"hero_count"`
}

// The campaign's parties, each with how many heroes ride with it.
func (q *Queries) ListParties(ctx context.Context, campaignID uuid.UUID) ([]ListPartiesRow, error) {
	rows, err := q.db.Query(ctx, listParties, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartiesRow
	for rows.Next() {
		var i ListPartiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.CreatedAt,
			&i.HeroCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyHeroIDs = `-- name: ListPartyHeroIDs :many
SELECT id FROM characters WHERE party_id = $1 AND kind = 'hero' ORDER BY created_at
`

// The heroes riding with a party right now. This is read at the moment of a
// grant and never again: a party is the brush, the per-hero rows are the paint.
func (q *Queries) ListPartyHeroIDs(ctx context.Context, partyID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPartyHeroIDs, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameParty = `-- name: RenameParty :one
UPDATE parties SET name = $2 WHERE id = $1 RETURNING id, campaign_id, name, created_at
`

type RenamePartyParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameParty(ctx context.Context, arg RenamePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, renameParty, arg.ID, arg.Name)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const setCharacterParty = `-- name: SetCharacterParty :one
UPDATE characters SET party_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, owner_user_id, name, class, level, hp_current, hp_max, created_at, updated_at, strength, dexterity, constitution, intelligence, wisdom, charisma, skills, class_id, species_id, background_id, subclass_id, feats, spell_slots_used, xp, pending_levels, table_born, species_choices, forge_key, pools_used, hit_dice_spent, pact_slots_used, kind, party_id
`

type SetCharacterPartyParams struct {
	ID      uuid.UUID   `json:"id"`
	PartyID pgtype.UUID `json:"party_id"`
}

// Move a hero between parties, or out of all of them (NULL).
func (q *Queries) SetCharacterParty(ctx context.Context, arg SetCharacterPartyParams) (Character, error) {
	row := q.db.QueryRow(ctx, setCharacterParty, arg.ID, arg.PartyID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OwnerUserID,
		&i.Name,
		&i.Class,
		&i.Level,
		&i.HpCurrent,
		&i.HpMax,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strength,
		&i.Dexterity,
		&i.Constitution,
		&i.Intelligence,
		&i.Wisdom,
		&i.Charisma,
		&i.Skills,
		&i.ClassID,
		&i.SpeciesID,
		&i.BackgroundID,
		&i.SubclassID,
		&i.Feats,
		&i.SpellSlotsUsed,
		&i.Xp,
		&i.PendingLevels,
		&i.TableBorn,
		&i.SpeciesChoices,
		&i.ForgeKey,
		&i.PoolsUsed,
		&i.HitDiceSpent,
		&i.PactSlotsUsed,
		&i.Kind,
		&i.PartyID,
	)
	return i, err
}

const setHandoutOverridesForParty = `-- name: SetHandoutOverridesForParty :exec
INSERT INTO handout_visibility (handout_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (handout_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetHandoutOverridesForPartyParams struct {
	HandoutID uuid.UUID   `json:"handout_id"`
	PartyID   pgtype.UUID `json:"party_id"`
	Visible   bool        `json:"visible"`
}

func (q *Queries) SetHandoutOverridesForParty(ctx context.Context, arg SetHandoutOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setHandoutOverridesForParty, arg.HandoutID, arg.PartyID, arg.Visible)
	return err
}

const setLocationOverridesForParty = `-- name: SetLocationOverridesForParty :exec
INSERT INTO location_visibility (location_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (location_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetLocationOverridesForPartyParams struct {
	LocationID uuid.UUID   `json:"location_id"`
	PartyID    pgtype.UUID `json:"party_id"`
	Visible    bool        `json:"visible"`
}

func (q *Queries) SetLocationOverridesForParty(ctx context.Context, arg SetLocationOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setLocationOverridesForParty, arg.LocationID, arg.PartyID, arg.Visible)
	return err
}

const setMapOverridesForParty = `-- name: SetMapOverridesForParty :exec
INSERT INTO map_visibility (map_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (map_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetMapOverridesForPartyParams struct {
	MapID   uuid.UUID   `json:"map_id"`
	PartyID pgtype.UUID `json:"party_id"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SetMapOverridesForParty(ctx context.Context, arg SetMapOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setMapOverridesForParty, arg.MapID, arg.PartyID, arg.Visible)
	return err
}

const setNpcOverridesForParty = `-- name: SetNpcOverridesForParty :exec
INSERT INTO npc_visibility (npc_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (npc_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetNpcOverridesForPartyParams struct {
	NpcID   uuid.UUID   `json:"npc_id"`
	PartyID pgtype.UUID `json:"party_id"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SetNpcOverridesForParty(ctx context.Context, arg SetNpcOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setNpcOverridesForParty, arg.NpcID, arg.PartyID, arg.Visible)
	return err
}

const setNpcStatOverridesForParty = `-- name: SetNpcStatOverridesForParty :exec
INSERT INTO npc_stat_visibility (npc_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (npc_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetNpcStatOverridesForPartyParams struct {
	NpcID   uuid.UUID   `json:"npc_id"`
	PartyID pgtype.UUID `json:"party_id"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SetNpcStatOverridesForParty(ctx context.Context, arg SetNpcStatOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setNpcStatOverridesForParty, arg.NpcID, arg.PartyID, arg.Visible)
	return err
}

const setQuestOverridesForParty = `-- name: SetQuestOverridesForParty :exec
INSERT INTO quest_visibility (quest_id, character_id, visible)
SELECT $1, c.id, $3 FROM characters c WHERE c.party_id = $2 AND c.kind = 'hero'
ON CONFLICT (quest_id, character_id)
DO UPDATE SET visible = EXCLUDED.visible, updated_at = now()
`

type SetQuestOverridesForPartyParams struct {
	QuestID uuid.UUID   `json:"quest_id"`
	PartyID pgtype.UUID `json:"party_id"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SetQuestOverridesForParty(ctx context.Context, arg SetQuestOverridesForPartyParams) error {
	_, err := q.db.Exec(ctx, setQuestOverridesForParty, arg.QuestID, arg.PartyID, arg.Visible)
	return err
}
