// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReward = `-- name: AddReward :one
INSERT INTO quest_rewards (quest_id, type, label, value)
VALUES ($1, $2, $3, $4)
RETURNING id, quest_id, type, label, value
`

type AddRewardParams struct {
	QuestID uuid.UUID  `json:"quest_id"`
	Type    RewardType `json:"type"`
	Label   string     `json:"label"`
	Value   *string    `json:"value"`
}

func (q *Queries) AddReward(ctx context.Context, arg AddRewardParams) (QuestReward, error) {
	row := q.db.QueryRow(ctx, addReward,
		arg.QuestID,
		arg.Type,
		arg.Label,
		arg.Value,
	)
	var i QuestReward
	err := row.Scan(
		&i.ID,
		&i.QuestID,
		&i.Type,
		&i.Label,
		&i.Value,
	)
	return i, err
}

const claimQuest = `-- name: ClaimQuest :exec
INSERT INTO quest_claims (quest_id, user_id)
VALUES ($1, $2)
ON CONFLICT (quest_id, user_id) DO NOTHING
`

type ClaimQuestParams struct {
	QuestID uuid.UUID `json:"quest_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ClaimQuest(ctx context.Context, arg ClaimQuestParams) error {
	_, err := q.db.Exec(ctx, claimQuest, arg.QuestID, arg.UserID)
	return err
}

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests (campaign_id, title, description, giver, location, difficulty, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, campaign_id, title, description, giver, location, difficulty, status, created_by, created_at, updated_at
`

type CreateQuestParams struct {
	CampaignID  uuid.UUID       `json:"campaign_id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Giver       *string         `json:"giver"`
	Location    *string         `json:"location"`
	Difficulty  QuestDifficulty `json:"difficulty"`
	Status      QuestStatus     `json:"status"`
	CreatedBy   uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.CampaignID,
		arg.Title,
		arg.Description,
		arg.Giver,
		arg.Location,
		arg.Difficulty,
		arg.Status,
		arg.CreatedBy,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.Giver,
		&i.Location,
		&i.Difficulty,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuest = `-- name: DeleteQuest :exec
DELETE FROM quests WHERE id = $1
`

func (q *Queries) DeleteQuest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuest, id)
	return err
}

const deleteRewardsForQuest = `-- name: DeleteRewardsForQuest :exec
DELETE FROM quest_rewards WHERE quest_id = $1
`

func (q *Queries) DeleteRewardsForQuest(ctx context.Context, questID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRewardsForQuest, questID)
	return err
}

const getQuest = `-- name: GetQuest :one
SELECT id, campaign_id, title, description, giver, location, difficulty, status, created_by, created_at, updated_at FROM quests WHERE id = $1
`

func (q *Queries) GetQuest(ctx context.Context, id uuid.UUID) (Quest, error) {
	row := q.db.QueryRow(ctx, getQuest, id)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.Giver,
		&i.Location,
		&i.Difficulty,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClaimsByCampaign = `-- name: ListClaimsByCampaign :many
SELECT c.quest_id, c.user_id, c.claimed_at, u.name AS user_name
FROM quest_claims c
JOIN users u ON u.id = c.user_id
JOIN quests q ON q.id = c.quest_id
WHERE q.campaign_id = $1
`

type ListClaimsByCampaignRow struct {
	QuestID   uuid.UUID          `json:"quest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
	UserName  string             `json:"user_name"`
}

func (q *Queries) ListClaimsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListClaimsByCampaignRow, error) {
	rows, err := q.db.Query(ctx, listClaimsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimsByCampaignRow
	for rows.Next() {
		var i ListClaimsByCampaignRow
		if err := rows.Scan(
			&i.QuestID,
			&i.UserID,
			&i.ClaimedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestsByCampaign = `-- name: ListQuestsByCampaign :many
SELECT id, campaign_id, title, description, giver, location, difficulty, status, created_by, created_at, updated_at FROM quests WHERE campaign_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListQuestsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]Quest, error) {
	rows, err := q.db.Query(ctx, listQuestsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quest
	for rows.Next() {
		var i Quest
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Title,
			&i.Description,
			&i.Giver,
			&i.Location,
			&i.Difficulty,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewardsByCampaign = `-- name: ListRewardsByCampaign :many
SELECT r.id, r.quest_id, r.type, r.label, r.value FROM quest_rewards r
JOIN quests q ON q.id = r.quest_id
WHERE q.campaign_id = $1
`

func (q *Queries) ListRewardsByCampaign(ctx context.Context, campaignID uuid.UUID) ([]QuestReward, error) {
	rows, err := q.db.Query(ctx, listRewardsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestReward
	for rows.Next() {
		var i QuestReward
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.Type,
			&i.Label,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewardsForQuest = `-- name: ListRewardsForQuest :many
SELECT id, quest_id, type, label, value FROM quest_rewards WHERE quest_id = $1
`

func (q *Queries) ListRewardsForQuest(ctx context.Context, questID uuid.UUID) ([]QuestReward, error) {
	rows, err := q.db.Query(ctx, listRewardsForQuest, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestReward
	for rows.Next() {
		var i QuestReward
		if err := rows.Scan(
			&i.ID,
			&i.QuestID,
			&i.Type,
			&i.Label,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unclaimQuest = `-- name: UnclaimQuest :exec
DELETE FROM quest_claims WHERE quest_id = $1 AND user_id = $2
`

type UnclaimQuestParams struct {
	QuestID uuid.UUID `json:"quest_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) UnclaimQuest(ctx context.Context, arg UnclaimQuestParams) error {
	_, err := q.db.Exec(ctx, unclaimQuest, arg.QuestID, arg.UserID)
	return err
}

const updateQuest = `-- name: UpdateQuest :one
UPDATE quests
SET title       = $2,
    description = $3,
    giver       = $4,
    location    = $5,
    difficulty  = $6,
    status      = $7,
    updated_at  = now()
WHERE id = $1
RETURNING id, campaign_id, title, description, giver, location, difficulty, status, created_by, created_at, updated_at
`

type UpdateQuestParams struct {
	ID          uuid.UUID       `json:"id"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Giver       *string         `json:"giver"`
	Location    *string         `json:"location"`
	Difficulty  QuestDifficulty `json:"difficulty"`
	Status      QuestStatus     `json:"status"`
}

func (q *Queries) UpdateQuest(ctx context.Context, arg UpdateQuestParams) (Quest, error) {
	row := q.db.QueryRow(ctx, updateQuest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Giver,
		arg.Location,
		arg.Difficulty,
		arg.Status,
	)
	var i Quest
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.Giver,
		&i.Location,
		&i.Difficulty,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
