// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCampaignsInRealm = `-- name: CountCampaignsInRealm :one
SELECT count(*) FROM campaigns WHERE realm_id = $1
`

func (q *Queries) CountCampaignsInRealm(ctx context.Context, realmID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsInRealm, realmID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRealm = `-- name: CreateRealm :one
INSERT INTO realms (name, owner_user_id) VALUES ($1, $2) RETURNING id, name, owner_user_id, created_at, updated_at, named
`

type CreateRealmParams struct {
	Name        string    `json:"name"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

// A realm is only ever born beside a campaign — either the one being founded
// ("a realm of its own") or the one being moved out of a shared one. There is
// no door for an empty realm, because a container with nothing in it is not a
// thing anyone sets out to make.
func (q *Queries) CreateRealm(ctx context.Context, arg CreateRealmParams) (Realm, error) {
	row := q.db.QueryRow(ctx, createRealm, arg.Name, arg.OwnerUserID)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Named,
	)
	return i, err
}

const deleteRealm = `-- name: DeleteRealm :execrows
DELETE FROM realms r
WHERE r.id = $1 AND NOT EXISTS (SELECT 1 FROM campaigns c WHERE c.realm_id = r.id)
`

// Refuses while anything stands in it, which the FK would enforce anyway — but
// a 500 is not an answer, so the handler counts first and this is the backstop.
func (q *Queries) DeleteRealm(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRealm, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRealm = `-- name: GetRealm :one
SELECT id, name, owner_user_id, created_at, updated_at, named FROM realms WHERE id = $1
`

func (q *Queries) GetRealm(ctx context.Context, id uuid.UUID) (Realm, error) {
	row := q.db.QueryRow(ctx, getRealm, id)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Named,
	)
	return i, err
}

const listCampaignIDsByRealm = `-- name: ListCampaignIDsByRealm :many
SELECT id FROM campaigns WHERE realm_id = $1
`

// Every table standing on a realm — the fan-out for a change to shared
// ground (#234): a place renamed or a road drawn must refresh every atlas
// open on that realm, not only the one it was drawn from.
func (q *Queries) ListCampaignIDsByRealm(ctx context.Context, realmID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCampaignIDsByRealm, realmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRealms = `-- name: ListRealms :many
SELECT r.id, r.name, r.owner_user_id, r.created_at, r.updated_at, r.named, (SELECT count(*) FROM campaigns c WHERE c.realm_id = r.id) AS campaign_count
FROM realms r
WHERE r.owner_user_id = $1
ORDER BY r.created_at
`

type ListRealmsRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Named         bool               `json:"named"`
	CampaignCount int64              `json:"campaign_count"`
}

// The caller's own realms, with how many campaigns stand in each (#233).
// Empty realms are listed too: an emptied realm is where the next campaign on
// this ground begins, which is the whole point of the container outliving the
// campaign.
func (q *Queries) ListRealms(ctx context.Context, ownerUserID uuid.UUID) ([]ListRealmsRow, error) {
	rows, err := q.db.Query(ctx, listRealms, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRealmsRow
	for rows.Next() {
		var i ListRealmsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Named,
			&i.CampaignCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameRealm = `-- name: RenameRealm :one
UPDATE realms SET name = $2, named = TRUE, updated_at = now() WHERE id = $1 RETURNING id, name, owner_user_id, created_at, updated_at, named
`

type RenameRealmParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameRealm(ctx context.Context, arg RenameRealmParams) (Realm, error) {
	row := q.db.QueryRow(ctx, renameRealm, arg.ID, arg.Name)
	var i Realm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Named,
	)
	return i, err
}

const setCampaignRealm = `-- name: SetCampaignRealm :one
UPDATE campaigns SET realm_id = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval, hidden_sheets, max_seated_per_player, realm_id, coinage
`

type SetCampaignRealmParams struct {
	ID      uuid.UUID `json:"id"`
	RealmID uuid.UUID `json:"realm_id"`
}

func (q *Queries) SetCampaignRealm(ctx context.Context, arg SetCampaignRealmParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setCampaignRealm, arg.ID, arg.RealmID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
		&i.HiddenSheets,
		&i.MaxSeatedPerPlayer,
		&i.RealmID,
		&i.Coinage,
	)
	return i, err
}
