// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seating.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSeatRequest = `-- name: DeleteSeatRequest :execrows
DELETE FROM seat_requests WHERE character_id = $1
`

func (q *Queries) DeleteSeatRequest(ctx context.Context, characterID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeatRequest, characterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSeatRequestsOfUser = `-- name: DeleteSeatRequestsOfUser :exec
DELETE FROM seat_requests sr
USING characters c
WHERE c.id = sr.character_id
  AND c.owner_user_id = $1
  AND sr.campaign_id = $2
`

type DeleteSeatRequestsOfUserParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	CampaignID  uuid.UUID `json:"campaign_id"`
}

// A kicked or banned player's heroes leave the door queue too.
func (q *Queries) DeleteSeatRequestsOfUser(ctx context.Context, arg DeleteSeatRequestsOfUserParams) error {
	_, err := q.db.Exec(ctx, deleteSeatRequestsOfUser, arg.OwnerUserID, arg.CampaignID)
	return err
}

const getSeatRequest = `-- name: GetSeatRequest :one
SELECT character_id, campaign_id, created_at FROM seat_requests WHERE character_id = $1
`

func (q *Queries) GetSeatRequest(ctx context.Context, characterID uuid.UUID) (SeatRequest, error) {
	row := q.db.QueryRow(ctx, getSeatRequest, characterID)
	var i SeatRequest
	err := row.Scan(&i.CharacterID, &i.CampaignID, &i.CreatedAt)
	return i, err
}

const listMySeatRequests = `-- name: ListMySeatRequests :many
SELECT sr.character_id, sr.campaign_id, ca.name AS campaign_name
FROM seat_requests sr
JOIN characters c ON c.id = sr.character_id
JOIN campaigns ca ON ca.id = sr.campaign_id
WHERE c.owner_user_id = $1
ORDER BY sr.created_at
`

type ListMySeatRequestsRow struct {
	CharacterID  uuid.UUID `json:"character_id"`
	CampaignID   uuid.UUID `json:"campaign_id"`
	CampaignName string    `json:"campaign_name"`
}

// The caller's own heroes still waiting at a door.
func (q *Queries) ListMySeatRequests(ctx context.Context, ownerUserID uuid.UUID) ([]ListMySeatRequestsRow, error) {
	rows, err := q.db.Query(ctx, listMySeatRequests, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMySeatRequestsRow
	for rows.Next() {
		var i ListMySeatRequestsRow
		if err := rows.Scan(&i.CharacterID, &i.CampaignID, &i.CampaignName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatRequests = `-- name: ListSeatRequests :many
SELECT sr.character_id, sr.created_at, c.name, c.class, c.level, u.name AS owner_name
FROM seat_requests sr
JOIN characters c ON c.id = sr.character_id
JOIN users u ON u.id = c.owner_user_id
WHERE sr.campaign_id = $1
ORDER BY sr.created_at
`

type ListSeatRequestsRow struct {
	CharacterID uuid.UUID          `json:"character_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Name        string             `json:"name"`
	Class       string             `json:"class"`
	Level       int32              `json:"level"`
	OwnerName   string             `json:"owner_name"`
}

// Everyone waiting at this campaign's door, oldest first.
func (q *Queries) ListSeatRequests(ctx context.Context, campaignID uuid.UUID) ([]ListSeatRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSeatRequests, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatRequestsRow
	for rows.Next() {
		var i ListSeatRequestsRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.CreatedAt,
			&i.Name,
			&i.Class,
			&i.Level,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeatingApproval = `-- name: SetSeatingApproval :one

UPDATE campaigns SET require_seating_approval = $2 WHERE id = $1 RETURNING id, name, owner_user_id, created_at, invite_code, next_session_at, progression, max_level, require_seating_approval
`

type SetSeatingApprovalParams struct {
	ID                     uuid.UUID `json:"id"`
	RequireSeatingApproval bool      `json:"require_seating_approval"`
}

// Seating approval: the barred door and the heroes waiting at it.
func (q *Queries) SetSeatingApproval(ctx context.Context, arg SetSeatingApprovalParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, setSeatingApproval, arg.ID, arg.RequireSeatingApproval)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.InviteCode,
		&i.NextSessionAt,
		&i.Progression,
		&i.MaxLevel,
		&i.RequireSeatingApproval,
	)
	return i, err
}

const upsertSeatRequest = `-- name: UpsertSeatRequest :exec
INSERT INTO seat_requests (character_id, campaign_id)
VALUES ($1, $2)
ON CONFLICT (character_id) DO UPDATE SET campaign_id = EXCLUDED.campaign_id, created_at = now()
`

type UpsertSeatRequestParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	CampaignID  uuid.UUID `json:"campaign_id"`
}

// A hero waits at one door at a time; asking elsewhere moves the request.
func (q *Queries) UpsertSeatRequest(ctx context.Context, arg UpsertSeatRequestParams) error {
	_, err := q.db.Exec(ctx, upsertSeatRequest, arg.CharacterID, arg.CampaignID)
	return err
}
