// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sheet.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCharacterItem = `-- name: AddCharacterItem :one
INSERT INTO character_items (character_id, content_id, name, qty)
VALUES ($1, $2, $3, $4)
RETURNING id, character_id, content_id, name, qty, equipped, created_at, slot
`

type AddCharacterItemParams struct {
	CharacterID uuid.UUID   `json:"character_id"`
	ContentID   pgtype.UUID `json:"content_id"`
	Name        string      `json:"name"`
	Qty         int32       `json:"qty"`
}

func (q *Queries) AddCharacterItem(ctx context.Context, arg AddCharacterItemParams) (CharacterItem, error) {
	row := q.db.QueryRow(ctx, addCharacterItem,
		arg.CharacterID,
		arg.ContentID,
		arg.Name,
		arg.Qty,
	)
	var i CharacterItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.ContentID,
		&i.Name,
		&i.Qty,
		&i.Equipped,
		&i.CreatedAt,
		&i.Slot,
	)
	return i, err
}

const addCharacterSpells = `-- name: AddCharacterSpells :exec
INSERT INTO character_spells (character_id, content_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type AddCharacterSpellsParams struct {
	CharacterID uuid.UUID   `json:"character_id"`
	Column2     []uuid.UUID `json:"column_2"`
}

// Add spell picks; re-adding an existing spell is a no-op.
func (q *Queries) AddCharacterSpells(ctx context.Context, arg AddCharacterSpellsParams) error {
	_, err := q.db.Exec(ctx, addCharacterSpells, arg.CharacterID, arg.Column2)
	return err
}

const deleteCharacterItem = `-- name: DeleteCharacterItem :exec
DELETE FROM character_items WHERE id = $1
`

func (q *Queries) DeleteCharacterItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterItem, id)
	return err
}

const getCharacterItem = `-- name: GetCharacterItem :one
SELECT id, character_id, content_id, name, qty, equipped, created_at, slot FROM character_items WHERE id = $1
`

func (q *Queries) GetCharacterItem(ctx context.Context, id uuid.UUID) (CharacterItem, error) {
	row := q.db.QueryRow(ctx, getCharacterItem, id)
	var i CharacterItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.ContentID,
		&i.Name,
		&i.Qty,
		&i.Equipped,
		&i.CreatedAt,
		&i.Slot,
	)
	return i, err
}

const listCharacterContentRefs = `-- name: ListCharacterContentRefs :many
SELECT cs.content_id FROM character_spells cs WHERE cs.character_id = $1
UNION
SELECT ci.content_id FROM character_items ci
WHERE ci.character_id = $1 AND ci.content_id IS NOT NULL
`

// Every rules reference a hero carries beyond the sheet columns:
// spell picks and content-backed inventory rows (for codex checks).
func (q *Queries) ListCharacterContentRefs(ctx context.Context, characterID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCharacterContentRefs, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var content_id uuid.UUID
		if err := rows.Scan(&content_id); err != nil {
			return nil, err
		}
		items = append(items, content_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterItems = `-- name: ListCharacterItems :many
SELECT ci.id, ci.character_id, ci.content_id, ci.qty, ci.equipped, ci.slot,
       COALESCE(rc.name, ci.name) AS name,
       rc.kind, rc.source, rc.summary, rc.data, rc.created_by,
       u.name AS creator_name
FROM character_items ci
LEFT JOIN rules_content rc ON rc.id = ci.content_id
LEFT JOIN users u ON u.id = rc.created_by
WHERE ci.character_id = $1
ORDER BY ci.equipped DESC, ci.created_at ASC
`

type ListCharacterItemsRow struct {
	ID          uuid.UUID      `json:"id"`
	CharacterID uuid.UUID      `json:"character_id"`
	ContentID   pgtype.UUID    `json:"content_id"`
	Qty         int32          `json:"qty"`
	Equipped    bool           `json:"equipped"`
	Slot        string         `json:"slot"`
	Name        string         `json:"name"`
	Kind        *ContentKind   `json:"kind"`
	Source      *ContentSource `json:"source"`
	Summary     *string        `json:"summary"`
	Data        []byte         `json:"data"`
	CreatedBy   pgtype.UUID    `json:"created_by"`
	CreatorName *string        `json:"creator_name"`
}

// Inventory with live content; a snapshot name covers deleted content.
func (q *Queries) ListCharacterItems(ctx context.Context, characterID uuid.UUID) ([]ListCharacterItemsRow, error) {
	rows, err := q.db.Query(ctx, listCharacterItems, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterItemsRow
	for rows.Next() {
		var i ListCharacterItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.ContentID,
			&i.Qty,
			&i.Equipped,
			&i.Slot,
			&i.Name,
			&i.Kind,
			&i.Source,
			&i.Summary,
			&i.Data,
			&i.CreatedBy,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterSpells = `-- name: ListCharacterSpells :many
SELECT rc.id, rc.kind, rc.source, rc.name, rc.summary, rc.data, rc.created_by, rc.created_at, rc.updated_at, u.name AS creator_name
FROM character_spells cs
JOIN rules_content rc ON rc.id = cs.content_id
LEFT JOIN users u ON u.id = rc.created_by
WHERE cs.character_id = $1
ORDER BY (rc.data->>'level')::int, rc.name
`

type ListCharacterSpellsRow struct {
	ID          uuid.UUID          `json:"id"`
	Kind        ContentKind        `json:"kind"`
	Source      ContentSource      `json:"source"`
	Name        string             `json:"name"`
	Summary     string             `json:"summary"`
	Data        []byte             `json:"data"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatorName *string            `json:"creator_name"`
}

// A hero's spells with their content and author, cantrips first.
func (q *Queries) ListCharacterSpells(ctx context.Context, characterID uuid.UUID) ([]ListCharacterSpellsRow, error) {
	rows, err := q.db.Query(ctx, listCharacterSpells, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterSpellsRow
	for rows.Next() {
		var i ListCharacterSpellsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Source,
			&i.Name,
			&i.Summary,
			&i.Data,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unequipItems = `-- name: UnequipItems :exec
UPDATE character_items
SET equipped = false, slot = ''
WHERE character_id = $1 AND id = ANY($2::uuid[])
`

type UnequipItemsParams struct {
	CharacterID uuid.UUID   `json:"character_id"`
	Column2     []uuid.UUID `json:"column_2"`
}

// Stows a set of rows: equip flag off, slot vacated.
func (q *Queries) UnequipItems(ctx context.Context, arg UnequipItemsParams) error {
	_, err := q.db.Exec(ctx, unequipItems, arg.CharacterID, arg.Column2)
	return err
}

const updateCharacterItem = `-- name: UpdateCharacterItem :one
UPDATE character_items
SET qty = $2, equipped = $3, slot = $4
WHERE id = $1
RETURNING id, character_id, content_id, name, qty, equipped, created_at, slot
`

type UpdateCharacterItemParams struct {
	ID       uuid.UUID `json:"id"`
	Qty      int32     `json:"qty"`
	Equipped bool      `json:"equipped"`
	Slot     string    `json:"slot"`
}

func (q *Queries) UpdateCharacterItem(ctx context.Context, arg UpdateCharacterItemParams) (CharacterItem, error) {
	row := q.db.QueryRow(ctx, updateCharacterItem,
		arg.ID,
		arg.Qty,
		arg.Equipped,
		arg.Slot,
	)
	var i CharacterItem
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.ContentID,
		&i.Name,
		&i.Qty,
		&i.Equipped,
		&i.CreatedAt,
		&i.Slot,
	)
	return i, err
}
