// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_trees.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addEdge = `-- name: AddEdge :exec
INSERT INTO skill_edges (tree_id, node_a, node_b)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddEdgeParams struct {
	TreeID uuid.UUID `json:"tree_id"`
	NodeA  uuid.UUID `json:"node_a"`
	NodeB  uuid.UUID `json:"node_b"`
}

func (q *Queries) AddEdge(ctx context.Context, arg AddEdgeParams) error {
	_, err := q.db.Exec(ctx, addEdge, arg.TreeID, arg.NodeA, arg.NodeB)
	return err
}

const addPick = `-- name: AddPick :exec
INSERT INTO character_nodes (character_id, node_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPickParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	NodeID      uuid.UUID `json:"node_id"`
}

func (q *Queries) AddPick(ctx context.Context, arg AddPickParams) error {
	_, err := q.db.Exec(ctx, addPick, arg.CharacterID, arg.NodeID)
	return err
}

const createNode = `-- name: CreateNode :one
INSERT INTO skill_nodes (tree_id, name, description, tradeoff, rarity, limb, is_entry, pos_x, pos_y)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tree_id, name, description, tradeoff, rarity, limb, is_entry, pos_x, pos_y, created_at
`

type CreateNodeParams struct {
	TreeID      uuid.UUID  `json:"tree_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Tradeoff    *string    `json:"tradeoff"`
	Rarity      NodeRarity `json:"rarity"`
	Limb        string     `json:"limb"`
	IsEntry     bool       `json:"is_entry"`
	PosX        *float32   `json:"pos_x"`
	PosY        *float32   `json:"pos_y"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (SkillNode, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.TreeID,
		arg.Name,
		arg.Description,
		arg.Tradeoff,
		arg.Rarity,
		arg.Limb,
		arg.IsEntry,
		arg.PosX,
		arg.PosY,
	)
	var i SkillNode
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Name,
		&i.Description,
		&i.Tradeoff,
		&i.Rarity,
		&i.Limb,
		&i.IsEntry,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
	)
	return i, err
}

const createTree = `-- name: CreateTree :one
INSERT INTO skill_trees (campaign_id, name, description, keystone_pick_cost)
VALUES ($1, $2, $3, $4)
RETURNING id, campaign_id, name, description, keystone_pick_cost, created_at
`

type CreateTreeParams struct {
	CampaignID       uuid.UUID `json:"campaign_id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	KeystonePickCost int32     `json:"keystone_pick_cost"`
}

func (q *Queries) CreateTree(ctx context.Context, arg CreateTreeParams) (SkillTree, error) {
	row := q.db.QueryRow(ctx, createTree,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.KeystonePickCost,
	)
	var i SkillTree
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.KeystonePickCost,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEdgesForTree = `-- name: DeleteEdgesForTree :exec
DELETE FROM skill_edges WHERE tree_id = $1
`

func (q *Queries) DeleteEdgesForTree(ctx context.Context, treeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdgesForTree, treeID)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM skill_nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const deletePicksForCharacter = `-- name: DeletePicksForCharacter :exec
DELETE FROM character_nodes WHERE character_id = $1
`

func (q *Queries) DeletePicksForCharacter(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePicksForCharacter, characterID)
	return err
}

const deleteTree = `-- name: DeleteTree :exec
DELETE FROM skill_trees WHERE id = $1
`

func (q *Queries) DeleteTree(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTree, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, tree_id, name, description, tradeoff, rarity, limb, is_entry, pos_x, pos_y, created_at FROM skill_nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (SkillNode, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i SkillNode
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Name,
		&i.Description,
		&i.Tradeoff,
		&i.Rarity,
		&i.Limb,
		&i.IsEntry,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
	)
	return i, err
}

const getPact = `-- name: GetPact :one
SELECT character_id, tree_id, picks_granted FROM character_trees WHERE character_id = $1
`

func (q *Queries) GetPact(ctx context.Context, characterID uuid.UUID) (CharacterTree, error) {
	row := q.db.QueryRow(ctx, getPact, characterID)
	var i CharacterTree
	err := row.Scan(&i.CharacterID, &i.TreeID, &i.PicksGranted)
	return i, err
}

const getTree = `-- name: GetTree :one
SELECT id, campaign_id, name, description, keystone_pick_cost, created_at FROM skill_trees WHERE id = $1
`

func (q *Queries) GetTree(ctx context.Context, id uuid.UUID) (SkillTree, error) {
	row := q.db.QueryRow(ctx, getTree, id)
	var i SkillTree
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.KeystonePickCost,
		&i.CreatedAt,
	)
	return i, err
}

const grantPicks = `-- name: GrantPicks :one
UPDATE character_trees
SET picks_granted = picks_granted + $2
WHERE character_id = $1
RETURNING character_id, tree_id, picks_granted
`

type GrantPicksParams struct {
	CharacterID  uuid.UUID `json:"character_id"`
	PicksGranted int32     `json:"picks_granted"`
}

func (q *Queries) GrantPicks(ctx context.Context, arg GrantPicksParams) (CharacterTree, error) {
	row := q.db.QueryRow(ctx, grantPicks, arg.CharacterID, arg.PicksGranted)
	var i CharacterTree
	err := row.Scan(&i.CharacterID, &i.TreeID, &i.PicksGranted)
	return i, err
}

const listEdgesByTree = `-- name: ListEdgesByTree :many
SELECT tree_id, node_a, node_b FROM skill_edges WHERE tree_id = $1
`

func (q *Queries) ListEdgesByTree(ctx context.Context, treeID uuid.UUID) ([]SkillEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByTree, treeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillEdge
	for rows.Next() {
		var i SkillEdge
		if err := rows.Scan(&i.TreeID, &i.NodeA, &i.NodeB); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByTree = `-- name: ListNodesByTree :many
SELECT id, tree_id, name, description, tradeoff, rarity, limb, is_entry, pos_x, pos_y, created_at FROM skill_nodes WHERE tree_id = $1 ORDER BY limb, created_at
`

func (q *Queries) ListNodesByTree(ctx context.Context, treeID uuid.UUID) ([]SkillNode, error) {
	rows, err := q.db.Query(ctx, listNodesByTree, treeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillNode
	for rows.Next() {
		var i SkillNode
		if err := rows.Scan(
			&i.ID,
			&i.TreeID,
			&i.Name,
			&i.Description,
			&i.Tradeoff,
			&i.Rarity,
			&i.Limb,
			&i.IsEntry,
			&i.PosX,
			&i.PosY,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickedNodes = `-- name: ListPickedNodes :many
SELECT n.id, n.tree_id, n.name, n.description, n.tradeoff, n.rarity, n.limb, n.is_entry, n.pos_x, n.pos_y, n.created_at FROM character_nodes cn
JOIN skill_nodes n ON n.id = cn.node_id
WHERE cn.character_id = $1
`

func (q *Queries) ListPickedNodes(ctx context.Context, characterID uuid.UUID) ([]SkillNode, error) {
	rows, err := q.db.Query(ctx, listPickedNodes, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillNode
	for rows.Next() {
		var i SkillNode
		if err := rows.Scan(
			&i.ID,
			&i.TreeID,
			&i.Name,
			&i.Description,
			&i.Tradeoff,
			&i.Rarity,
			&i.Limb,
			&i.IsEntry,
			&i.PosX,
			&i.PosY,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTreesByCampaign = `-- name: ListTreesByCampaign :many
SELECT id, campaign_id, name, description, keystone_pick_cost, created_at FROM skill_trees WHERE campaign_id = $1 ORDER BY created_at
`

func (q *Queries) ListTreesByCampaign(ctx context.Context, campaignID uuid.UUID) ([]SkillTree, error) {
	rows, err := q.db.Query(ctx, listTreesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillTree
	for rows.Next() {
		var i SkillTree
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.KeystonePickCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPact = `-- name: SetPact :one
INSERT INTO character_trees (character_id, tree_id, picks_granted)
VALUES ($1, $2, 0)
ON CONFLICT (character_id) DO UPDATE
SET tree_id = EXCLUDED.tree_id,
    -- Re-pledging to the same tree keeps progress; a new tree resets it.
    picks_granted = CASE
        WHEN character_trees.tree_id = EXCLUDED.tree_id THEN character_trees.picks_granted
        ELSE 0
    END
RETURNING character_id, tree_id, picks_granted
`

type SetPactParams struct {
	CharacterID uuid.UUID `json:"character_id"`
	TreeID      uuid.UUID `json:"tree_id"`
}

func (q *Queries) SetPact(ctx context.Context, arg SetPactParams) (CharacterTree, error) {
	row := q.db.QueryRow(ctx, setPact, arg.CharacterID, arg.TreeID)
	var i CharacterTree
	err := row.Scan(&i.CharacterID, &i.TreeID, &i.PicksGranted)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE skill_nodes
SET name = $2, description = $3, tradeoff = $4, rarity = $5, limb = $6,
    is_entry = $7, pos_x = $8, pos_y = $9
WHERE id = $1
RETURNING id, tree_id, name, description, tradeoff, rarity, limb, is_entry, pos_x, pos_y, created_at
`

type UpdateNodeParams struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Tradeoff    *string    `json:"tradeoff"`
	Rarity      NodeRarity `json:"rarity"`
	Limb        string     `json:"limb"`
	IsEntry     bool       `json:"is_entry"`
	PosX        *float32   `json:"pos_x"`
	PosY        *float32   `json:"pos_y"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (SkillNode, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tradeoff,
		arg.Rarity,
		arg.Limb,
		arg.IsEntry,
		arg.PosX,
		arg.PosY,
	)
	var i SkillNode
	err := row.Scan(
		&i.ID,
		&i.TreeID,
		&i.Name,
		&i.Description,
		&i.Tradeoff,
		&i.Rarity,
		&i.Limb,
		&i.IsEntry,
		&i.PosX,
		&i.PosY,
		&i.CreatedAt,
	)
	return i, err
}

const updateTree = `-- name: UpdateTree :one
UPDATE skill_trees
SET name = $2, description = $3, keystone_pick_cost = $4
WHERE id = $1
RETURNING id, campaign_id, name, description, keystone_pick_cost, created_at
`

type UpdateTreeParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	KeystonePickCost int32     `json:"keystone_pick_cost"`
}

func (q *Queries) UpdateTree(ctx context.Context, arg UpdateTreeParams) (SkillTree, error) {
	row := q.db.QueryRow(ctx, updateTree,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.KeystonePickCost,
	)
	var i SkillTree
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.KeystonePickCost,
		&i.CreatedAt,
	)
	return i, err
}
