// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStock = `-- name: AddStock :one
INSERT INTO vendor_stock (vendor_id, content_id, name, price, qty, sort_order)
VALUES ($1, $2, $3, $4, $5,
        COALESCE((SELECT MAX(sort_order) + 1 FROM vendor_stock WHERE vendor_id = $1), 0))
RETURNING id, vendor_id, content_id, name, price, qty, revealed, sort_order, created_at
`

type AddStockParams struct {
	VendorID  uuid.UUID   `json:"vendor_id"`
	ContentID pgtype.UUID `json:"content_id"`
	Name      string      `json:"name"`
	Price     string      `json:"price"`
	Qty       *int32      `json:"qty"`
}

func (q *Queries) AddStock(ctx context.Context, arg AddStockParams) (VendorStock, error) {
	row := q.db.QueryRow(ctx, addStock,
		arg.VendorID,
		arg.ContentID,
		arg.Name,
		arg.Price,
		arg.Qty,
	)
	var i VendorStock
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.ContentID,
		&i.Name,
		&i.Price,
		&i.Qty,
		&i.Revealed,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (campaign_id, name, description, location_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, campaign_id, name, description, location_id, revealed, created_by, created_at, updated_at
`

type CreateVendorParams struct {
	CampaignID  uuid.UUID   `json:"campaign_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	LocationID  pgtype.UUID `json:"location_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.CampaignID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.CreatedBy,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.Revealed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStock = `-- name: DeleteStock :execrows
DELETE FROM vendor_stock WHERE id = $1
`

func (q *Queries) DeleteStock(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStock, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteVendor = `-- name: DeleteVendor :execrows
DELETE FROM vendors WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVendor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStock = `-- name: GetStock :one
SELECT s.id, s.vendor_id, s.content_id, s.name, s.price, s.qty, s.revealed, s.sort_order, s.created_at, v.campaign_id
FROM vendor_stock s
JOIN vendors v ON v.id = s.vendor_id
WHERE s.id = $1
`

type GetStockRow struct {
	ID         uuid.UUID          `json:"id"`
	VendorID   uuid.UUID          `json:"vendor_id"`
	ContentID  pgtype.UUID        `json:"content_id"`
	Name       string             `json:"name"`
	Price      string             `json:"price"`
	Qty        *int32             `json:"qty"`
	Revealed   bool               `json:"revealed"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CampaignID uuid.UUID          `json:"campaign_id"`
}

func (q *Queries) GetStock(ctx context.Context, id uuid.UUID) (GetStockRow, error) {
	row := q.db.QueryRow(ctx, getStock, id)
	var i GetStockRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.ContentID,
		&i.Name,
		&i.Price,
		&i.Qty,
		&i.Revealed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CampaignID,
	)
	return i, err
}

const getVendor = `-- name: GetVendor :one
SELECT id, campaign_id, name, description, location_id, revealed, created_by, created_at, updated_at FROM vendors WHERE id = $1
`

func (q *Queries) GetVendor(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendor, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.Revealed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStockForCampaign = `-- name: ListStockForCampaign :many
SELECT s.id, s.vendor_id, s.content_id, s.name, s.price, s.qty, s.revealed, s.sort_order, s.created_at, rc.kind, rc.source, rc.summary, rc.data
FROM vendor_stock s
JOIN vendors v ON v.id = s.vendor_id
LEFT JOIN rules_content rc ON rc.id = s.content_id
WHERE v.campaign_id = $1
ORDER BY s.sort_order, s.created_at
`

type ListStockForCampaignRow struct {
	ID        uuid.UUID          `json:"id"`
	VendorID  uuid.UUID          `json:"vendor_id"`
	ContentID pgtype.UUID        `json:"content_id"`
	Name      string             `json:"name"`
	Price     string             `json:"price"`
	Qty       *int32             `json:"qty"`
	Revealed  bool               `json:"revealed"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Kind      *ContentKind       `json:"kind"`
	Source    *ContentSource     `json:"source"`
	Summary   *string            `json:"summary"`
	Data      []byte             `json:"data"`
}

// Every shelf in the campaign at once, so listing the shops does not become one
// query per shop.
func (q *Queries) ListStockForCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListStockForCampaignRow, error) {
	rows, err := q.db.Query(ctx, listStockForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockForCampaignRow
	for rows.Next() {
		var i ListStockForCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.ContentID,
			&i.Name,
			&i.Price,
			&i.Qty,
			&i.Revealed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.Kind,
			&i.Source,
			&i.Summary,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorStock = `-- name: ListVendorStock :many
SELECT s.id, s.vendor_id, s.content_id, s.name, s.price, s.qty, s.revealed, s.sort_order, s.created_at, rc.kind, rc.source, rc.summary, rc.data
FROM vendor_stock s
LEFT JOIN rules_content rc ON rc.id = s.content_id
WHERE s.vendor_id = $1
ORDER BY s.sort_order, s.created_at
`

type ListVendorStockRow struct {
	ID        uuid.UUID          `json:"id"`
	VendorID  uuid.UUID          `json:"vendor_id"`
	ContentID pgtype.UUID        `json:"content_id"`
	Name      string             `json:"name"`
	Price     string             `json:"price"`
	Qty       *int32             `json:"qty"`
	Revealed  bool               `json:"revealed"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Kind      *ContentKind       `json:"kind"`
	Source    *ContentSource     `json:"source"`
	Summary   *string            `json:"summary"`
	Data      []byte             `json:"data"`
}

// The shelves of one shop, in the order the DM arranged them. `mine` on the
// joined content is not needed here: what a shop sells is the campaign's
// business, not the author's.
func (q *Queries) ListVendorStock(ctx context.Context, vendorID uuid.UUID) ([]ListVendorStockRow, error) {
	rows, err := q.db.Query(ctx, listVendorStock, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorStockRow
	for rows.Next() {
		var i ListVendorStockRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.ContentID,
			&i.Name,
			&i.Price,
			&i.Qty,
			&i.Revealed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.Kind,
			&i.Source,
			&i.Summary,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT v.id, v.campaign_id, v.name, v.description, v.location_id, v.revealed, v.created_by, v.created_at, v.updated_at, l.name AS location_name
FROM vendors v
LEFT JOIN locations l ON l.id = v.location_id
WHERE v.campaign_id = $1
ORDER BY l.name NULLS LAST, v.name
`

type ListVendorsRow struct {
	ID           uuid.UUID          `json:"id"`
	CampaignID   uuid.UUID          `json:"campaign_id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	LocationID   pgtype.UUID        `json:"location_id"`
	Revealed     bool               `json:"revealed"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LocationName *string            `json:"location_name"`
}

// Every shop in a campaign, with the place it trades in. Redaction is the
// handler's job — this hands over everything and the caller decides what the
// viewer is allowed to see.
func (q *Queries) ListVendors(ctx context.Context, campaignID uuid.UUID) ([]ListVendorsRow, error) {
	rows, err := q.db.Query(ctx, listVendors, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVendorsRow
	for rows.Next() {
		var i ListVendorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.Description,
			&i.LocationID,
			&i.Revealed,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStock = `-- name: UpdateStock :one
UPDATE vendor_stock
SET price = $2, qty = $3, revealed = $4
WHERE id = $1
RETURNING id, vendor_id, content_id, name, price, qty, revealed, sort_order, created_at
`

type UpdateStockParams struct {
	ID       uuid.UUID `json:"id"`
	Price    string    `json:"price"`
	Qty      *int32    `json:"qty"`
	Revealed bool      `json:"revealed"`
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) (VendorStock, error) {
	row := q.db.QueryRow(ctx, updateStock,
		arg.ID,
		arg.Price,
		arg.Qty,
		arg.Revealed,
	)
	var i VendorStock
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.ContentID,
		&i.Name,
		&i.Price,
		&i.Qty,
		&i.Revealed,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET name = $2, description = $3, location_id = $4, revealed = $5, updated_at = now()
WHERE id = $1
RETURNING id, campaign_id, name, description, location_id, revealed, created_by, created_at, updated_at
`

type UpdateVendorParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	LocationID  pgtype.UUID `json:"location_id"`
	Revealed    bool        `json:"revealed"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LocationID,
		arg.Revealed,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.Description,
		&i.LocationID,
		&i.Revealed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
