// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueWebhookDeliveries = `-- name: ClaimDueWebhookDeliveries :many
SELECT d.id, d.webhook_id, d.event_id, d.name, d.body, d.attempts, d.next_attempt_at, d.delivered_at, d.dead_at, d.last_status, d.last_error, d.created_at, w.url, w.secret, w.user_id
FROM webhook_deliveries d
JOIN webhooks w ON w.id = d.webhook_id
WHERE d.delivered_at IS NULL AND d.dead_at IS NULL AND d.next_attempt_at <= now()
  AND w.disabled_at IS NULL
ORDER BY d.next_attempt_at
LIMIT $1
FOR UPDATE OF d SKIP LOCKED
`

type ClaimDueWebhookDeliveriesRow struct {
	ID            uuid.UUID          `json:"id"`
	WebhookID     uuid.UUID          `json:"webhook_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	Name          string             `json:"name"`
	Body          []byte             `json:"body"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	DeadAt        pgtype.Timestamptz `json:"dead_at"`
	LastStatus    *int32             `json:"last_status"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Url           string             `json:"url"`
	Secret        string             `json:"secret"`
	UserID        uuid.UUID          `json:"user_id"`
}

// The worker's claim: due, not done, on a live hook, locked so a second
// worker (there is none today) could never send the same one twice.
func (q *Queries) ClaimDueWebhookDeliveries(ctx context.Context, limit int32) ([]ClaimDueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDueWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueWebhookDeliveriesRow
	for rows.Next() {
		var i ClaimDueWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Name,
			&i.Body,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.DeadAt,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
			&i.Url,
			&i.Secret,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhooksByUser = `-- name: CountWebhooksByUser :one
SELECT count(*) FROM webhooks WHERE user_id = $1
`

func (q *Queries) CountWebhooksByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhooksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one

INSERT INTO webhooks (user_id, url, secret, events, campaign_id, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, url, secret, events, campaign_id, scopes, created_at, failures, disabled_at, disabled_reason
`

type CreateWebhookParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Url        string      `json:"url"`
	Secret     string      `json:"secret"`
	Events     []string    `json:"events"`
	CampaignID pgtype.UUID `json:"campaign_id"`
	Scopes     []string    `json:"scopes"`
}

// Webhooks (#295): subscriptions and their deliveries.
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.UserID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.CampaignID,
		arg.Scopes,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.CampaignID,
		&i.Scopes,
		&i.CreatedAt,
		&i.Failures,
		&i.DisabledAt,
		&i.DisabledReason,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :one
DELETE FROM webhooks WHERE id = $1 AND user_id = $2 RETURNING id
`

type DeleteWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteWebhook, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const disableWebhook = `-- name: DisableWebhook :exec
UPDATE webhooks SET disabled_at = now(), disabled_reason = $2
WHERE id = $1 AND disabled_at IS NULL
`

type DisableWebhookParams struct {
	ID             uuid.UUID `json:"id"`
	DisabledReason *string   `json:"disabled_reason"`
}

func (q *Queries) DisableWebhook(ctx context.Context, arg DisableWebhookParams) error {
	_, err := q.db.Exec(ctx, disableWebhook, arg.ID, arg.DisabledReason)
	return err
}

const enableWebhook = `-- name: EnableWebhook :exec
UPDATE webhooks SET disabled_at = NULL, disabled_reason = NULL, failures = 0
WHERE id = $1 AND user_id = $2
`

type EnableWebhookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) EnableWebhook(ctx context.Context, arg EnableWebhookParams) error {
	_, err := q.db.Exec(ctx, enableWebhook, arg.ID, arg.UserID)
	return err
}

const getWebhookForUser = `-- name: GetWebhookForUser :one
SELECT w.id, w.user_id, w.url, w.secret, w.events, w.campaign_id, w.scopes, w.created_at, w.failures, w.disabled_at, w.disabled_reason, c.name AS campaign_name,
    (SELECT max(d.delivered_at) FROM webhook_deliveries d WHERE d.webhook_id = w.id)::timestamptz AS last_delivered_at
FROM webhooks w
LEFT JOIN campaigns c ON c.id = w.campaign_id
WHERE w.id = $1 AND w.user_id = $2
`

type GetWebhookForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetWebhookForUserRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Url             string             `json:"url"`
	Secret          string             `json:"secret"`
	Events          []string           `json:"events"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	Scopes          []string           `json:"scopes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Failures        int32              `json:"failures"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	DisabledReason  *string            `json:"disabled_reason"`
	CampaignName    *string            `json:"campaign_name"`
	LastDeliveredAt pgtype.Timestamptz `json:"last_delivered_at"`
}

func (q *Queries) GetWebhookForUser(ctx context.Context, arg GetWebhookForUserParams) (GetWebhookForUserRow, error) {
	row := q.db.QueryRow(ctx, getWebhookForUser, arg.ID, arg.UserID)
	var i GetWebhookForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.CampaignID,
		&i.Scopes,
		&i.CreatedAt,
		&i.Failures,
		&i.DisabledAt,
		&i.DisabledReason,
		&i.CampaignName,
		&i.LastDeliveredAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_id, name, body)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event_id, name, body, attempts, next_attempt_at, delivered_at, dead_at, last_status, last_error, created_at
`

type InsertWebhookDeliveryParams struct {
	WebhookID uuid.UUID   `json:"webhook_id"`
	EventID   pgtype.UUID `json:"event_id"`
	Name      string      `json:"name"`
	Body      []byte      `json:"body"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.WebhookID,
		arg.EventID,
		arg.Name,
		arg.Body,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventID,
		&i.Name,
		&i.Body,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.DeadAt,
		&i.LastStatus,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listLiveWebhooksForUsers = `-- name: ListLiveWebhooksForUsers :many
SELECT id, user_id, url, secret, events, campaign_id, scopes, created_at, failures, disabled_at, disabled_reason FROM webhooks
WHERE user_id = ANY($1::uuid[]) AND disabled_at IS NULL
`

// The fan-out (#315 → #295): every live hook of anyone in the audience.
func (q *Queries) ListLiveWebhooksForUsers(ctx context.Context, dollar_1 []uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listLiveWebhooksForUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.CampaignID,
			&i.Scopes,
			&i.CreatedAt,
			&i.Failures,
			&i.DisabledAt,
			&i.DisabledReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event_id, name, body, attempts, next_attempt_at, delivered_at, dead_at, last_status, last_error, created_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventID,
			&i.Name,
			&i.Body,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.DeadAt,
			&i.LastStatus,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByUser = `-- name: ListWebhooksByUser :many
SELECT w.id, w.user_id, w.url, w.secret, w.events, w.campaign_id, w.scopes, w.created_at, w.failures, w.disabled_at, w.disabled_reason, c.name AS campaign_name,
    (SELECT max(d.delivered_at) FROM webhook_deliveries d WHERE d.webhook_id = w.id)::timestamptz AS last_delivered_at
FROM webhooks w
LEFT JOIN campaigns c ON c.id = w.campaign_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type ListWebhooksByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Url             string             `json:"url"`
	Secret          string             `json:"secret"`
	Events          []string           `json:"events"`
	CampaignID      pgtype.UUID        `json:"campaign_id"`
	Scopes          []string           `json:"scopes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Failures        int32              `json:"failures"`
	DisabledAt      pgtype.Timestamptz `json:"disabled_at"`
	DisabledReason  *string            `json:"disabled_reason"`
	CampaignName    *string            `json:"campaign_name"`
	LastDeliveredAt pgtype.Timestamptz `json:"last_delivered_at"`
}

func (q *Queries) ListWebhooksByUser(ctx context.Context, userID uuid.UUID) ([]ListWebhooksByUserRow, error) {
	rows, err := q.db.Query(ctx, listWebhooksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhooksByUserRow
	for rows.Next() {
		var i ListWebhooksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.CampaignID,
			&i.Scopes,
			&i.CreatedAt,
			&i.Failures,
			&i.DisabledAt,
			&i.DisabledReason,
			&i.CampaignName,
			&i.LastDeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDelivered = `-- name: MarkWebhookDelivered :exec
UPDATE webhook_deliveries
SET delivered_at = now(), attempts = attempts + 1, last_status = $2, last_error = NULL
WHERE id = $1
`

type MarkWebhookDeliveredParams struct {
	ID         uuid.UUID `json:"id"`
	LastStatus *int32    `json:"last_status"`
}

func (q *Queries) MarkWebhookDelivered(ctx context.Context, arg MarkWebhookDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDelivered, arg.ID, arg.LastStatus)
	return err
}

const markWebhookDeliveryDead = `-- name: MarkWebhookDeliveryDead :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1, dead_at = now(), last_status = $2, last_error = $3
WHERE id = $1
`

type MarkWebhookDeliveryDeadParams struct {
	ID         uuid.UUID `json:"id"`
	LastStatus *int32    `json:"last_status"`
	LastError  *string   `json:"last_error"`
}

func (q *Queries) MarkWebhookDeliveryDead(ctx context.Context, arg MarkWebhookDeliveryDeadParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryDead, arg.ID, arg.LastStatus, arg.LastError)
	return err
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_deliveries
SET attempts = attempts + 1, next_attempt_at = $2, last_status = $3, last_error = $4
WHERE id = $1
`

type MarkWebhookDeliveryFailedParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastStatus    *int32             `json:"last_status"`
	LastError     *string            `json:"last_error"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastStatus,
		arg.LastError,
	)
	return err
}

const recordWebhookDeadDelivery = `-- name: RecordWebhookDeadDelivery :one
UPDATE webhooks SET failures = failures + 1 WHERE id = $1 RETURNING failures
`

func (q *Queries) RecordWebhookDeadDelivery(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordWebhookDeadDelivery, id)
	var failures int32
	err := row.Scan(&failures)
	return failures, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhooks SET failures = 0 WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}
